### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Sugestão para tela de inclusão.

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#1]
Hoje a tela de inclusão de Tipo de Resposta é apresentada da seguinte maneira:

![detalhar_sicel_cdu](https://cloud.githubusercontent.com/assets/7429018/3512512/dc6b60f2-06b9-11e4-84f2-8475bd2318de.png)

Abaixo é exibida uma imagem com a sugestão do layout para a mesma tela com novos alinhamentos e labels:
![manter_sicel_1](https://cloud.githubusercontent.com/assets/7429018/3512518/ea61900a-06b9-11e4-80db-1067baafdbde.png)

Podemos seguir a implementação com o layout sugerido ?

**Comment by monicaleite** [comment]
Sim podem seguir, mas lembrando que a aprovação vem por parte do cliente, ao meu ver não tem problema que seja como você propôs.

**Comment by monicaleite** [comment]
Em conversa com o líder de projetos Elder, todas as sugestões foram aceitas. o documento já foi atualizado no git.
