### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Campo "Para Executar Em"

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#100]
Quais são os valores que estarão disponíveis no campo?

**Comment by espinola** [comment]
quais campos?

**Comment by jadossantos** [comment]
Quais são os valores que iremos apresentar no campo <b>Para Executar Em</b>?

**Comment by espinola** [comment]
corrigido, valores: ZONA CRE CGE
