### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Tabela da PT4

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#101]
Os campos da tabela PT4 estão sem tamanho definido.

A RN vinculada ao campo "Seguro? Preencha a senha" é a <b>RN32</b> ou <b>RN34</b>?

**Comment by espinola** [comment]
corrigido

**Comment by jadossantos** [comment]
A referência da RN foi corrigida.

Faltou incluir os valores dos campos da PT4 e as outra tabelas também não apresentam nenhum tamanho dos campos.

**Comment by jadossantos** [comment]
Alterando o responsável para Monica.

**Comment by monicaleite** [comment]
Já definimos por telefone.

**Comment by jadossantos** [comment]
É o mesmo problema do #144.
