### ISSUE TITLE
SICEL_CDU_009_Manter Modelo de Documentos - PT1 - Unidade Eleitoral

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#102]
Quais valores irão preencher a combo <b>Unidade Eleitoral</b>?

![unidade-eleitoral](https://cloud.githubusercontent.com/assets/7116054/5681292/08593dc4-97f6-11e4-90cd-9e9958123245.png)

**Comment by monicaleite** [comment]
A mesma tabela que o Leandro indicar na resposta do e-mail encaminhado. O Leandro está de férias então encaminhei para o Elder, ele está em reunião então teremos que esperar a disponibilidade dele em nos responder.

**Comment by jadossantos** [comment]
É necessário atualizar a documentação com essa informação. Já que a mesma informa que o combo apresentará os "Valores cadastrados no sistema".

**Comment by monicaleite** [comment]
Documento foi atualizado.

**Comment by jadossantos** [comment]
ok
