### ISSUE TITLE
SICEL_CDU_010_Manter Documento de Procedimento - PT1 - Tipo de Documento

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#103]
Quais são os valores que serão apresentados no combo <b>Tipo de Documento</b>?

**Comment by espinola** [comment]
como dito no caso de uso : "valores cadastrados no sistema"

**Comment by jadossantos** [comment]
Em qual local esta essa definição? 
Existe algum CDU que faz manutenção a essa informação?

**Comment by espinola** [comment]
Joel para já ficar fico conversei com o gestor e ficou estabelecido os seguintes tipos Ofício
Ata
Portaria
Declaração
Edital
Dados do Cartório
Outros

documentação atualizada
