### ISSUE TITLE
SICEL_CDU_010_Manter Documento de Procedimento - Tabela da PT4

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#104]
Os campos da tabela PT1 estão sem tamanho definido.

**Comment by espinola** [comment]
o tamanho pode ser definido por você.

**Comment by espinola** [comment]
os campos pode ser definido por você de acordo com o padrão do sistema

**Comment by jadossantos** [comment]
Não tenho como definir o tamanho dos campos. 
Precisaremos envolver o cliente para obter essa resposta, pois a própria SEAD irá questionar esse tamanho para validar o Modelo Físico.

**Comment by jadossantos** [comment]
Alterando o responsável para Monica.

**Comment by monicaleite** [comment]
Joel,

Esse foi o que conversamos por telefone e ficou definido Nome 300 e Observação 500.

**Comment by jadossantos** [comment]
Ok. O nome ficou com 100.
