### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - PT2 - Executar Procedimento

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#107]
Monica, 
Poderia detalhar o significado de cada "texto" da imagem abaixo?

![sicel cdu008 executar procedimento](https://cloud.githubusercontent.com/assets/7116054/5729272/001830a4-9b50-11e4-9a77-e089c7e25eb5.png)

Por exemplo, o que é : 
- Um <b>Roteiro (nome)</b>;
- Uma <b>Categoria (nome)</b>;
- Um  <b>Grupo</b>;
- Um <b>Quesito (nome e nota)</b>;

Obs.: Podemos conversar por telefone para um melhor entendimento.

**Comment by monicaleite** [comment]
Joel,

As descrições estão no caso de uso no detalhamento da tela, quando (nome) é o valor cadastrado. Me liga que será melhor.

**Comment by monicaleite** [comment]
Joel,

Para questão de abrir e fechar procedimento encontrei a regra na documentação.

4.3 RAP054 – Opção de fechar e reabrir procedimento
Nome do(s) caso(s) de uso que utiliza(m) essa regra: Executar Procedimento

Assim que o usuário inicia a execução do procedimento, responde e salva pelo menos uma pergunta ele passa para o status “Em execução”.
Quando no procedimento não possuir nenhuma resposta o status será “Instaurado”.
A opção para fechar procedimento estará habilitada somente quando o(s) roteiro(s) que pertence(m) ao procedimento em questão for(em) totalmente respondido(s) e salvo(s). Ao acionar essa opção o procedimento passará para o status “Finalizado”. 
A opção reabrir o procedimento somente estará habilitada quando o roteiro for finalizado e ainda está no prazo para execução. Ao acionar essa opção o procedimento retornará para o status “Em execução” e permitirá responder novamente o procedimento. 
Quando um procedimento tiver passado da data limite para responder, o sistema deverá fechar o procedimento automaticamente e não permitirá que seja reaberto. 
Para que a unidade eleitoral possa continuar respondendo depois do prazo, o titular (criador) do procedimento deverá ir ao caso de uso Manter Procedimento e alterar a data limite do procedimento, neste caso as opções e comportamento voltarão ao estado inicial.
O sistema deverá guardar os procedimentos que foram fechados automaticamente, pois será utilizado nos relatórios.
Quando um procedimento estiver finalizado e o usuário selecionar um procedimento com esse status e acionar a opção executar o sistema deverá exibir as informações para responder como somente leitura, apenas no painel de controle estará habilitada a impressão do procedimento e na parte de anexar documento, as opções de upload, download, não será permitido excluir documento enquanto estiver com status finalizado.

**Comment by monicaleite** [comment]
Em relação a um roteiro diferente de ordinário, teremos um item Quesitos que ficará abaixo da opção painel de controle, e ao ser selecionado ele exibirá todos os quesitos(notas e tipo de resposta) sem nenhum vinculo com categoria e grupo, para serem respondidos.
Para os demais que possuam categoria ou categoria/grupo e quesito, deverá ser exibido conforme o modelo no caso de uso. O caso de uso foi atualizado com a tel PT4 e a RAP051 também foi melhorada.

**Comment by jadossantos** [comment]
Ok.
