### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Exclusão Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#108]
Prezados,

Ao realizar uma exclusão de um procedimento cadastrado para teste na aplição no ambiente de desenvolvimento [ Cadastros > Tipo de Procedimentos ], os dois primeiros itens não estão sendo possivel realizar a exclusão conforme o fluxo. 
FA 3. Excluir tipo de Procedimento. 

![sicel2](https://cloud.githubusercontent.com/assets/9218077/6107571/28d63064-b053-11e4-8dc3-7c33cb926b36.jpg)

![sicel1](https://cloud.githubusercontent.com/assets/9218077/6107579/38430662-b053-11e4-8b68-742a2eb3d6f1.jpg)

**Comment by raynerweb** [comment]
Por gentileza, repasse essa tarefa ao Sávio ou Haber.
Att.
Ráyner

**Comment by kleiberfaria** [comment]
Encaminhado conforme a solicitação para o Analista.

**Comment by jadossantos** [comment]
Alterando para Rogério.

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
