### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Inclusão do caso de uso

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#109]
Verificar a necessidade de inclusão do nome do caso de uso nas regras de apresentações e Regras de Negócios onde são chamados no CDU. Segue exemplo:
Verificar que o nome do caso de uso não foi citado na regra
Obs: Regras que são citadas:
RNs:004, 005, 008, 018, 041.
RAP: 001, 002, 003, 005, 014, 025, 038.
- em algumas o nome do CDU está sendo citado.

![capturar](https://cloud.githubusercontent.com/assets/6584772/6524390/a9c77c2c-c3d7-11e4-874f-d67b98035adb.PNG)

**Comment by monicaleite** [comment]
O caso de uso foi referenciado na RN002.

**Comment by jmatil** [comment]
Confirmado a inclusão
