### ISSUE TITLE
CDU_SICEL_003_Manter Grupo - Comando Incluir Categoria

### ISSUE THREAD

**Issue by imotac** [islssa/SICEL#11]
Na tabela correspondente à "Interface do fluxo de eventos Listar Grupos", existe o comando "Incluir Categoria", mas este comando não está presente no protótipo, provavelmente foi confundido com o comando "Incluir Grupo". Necessário ajustar a documentação.

**Comment by monicaleite** [comment]
Realizado o ajuste.
