### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Referência

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#110]
Confirma a referência sitada para este caso de uso?
![capturar](https://cloud.githubusercontent.com/assets/6584772/6525803/f296994a-c3e8-11e4-9630-a11af199c57e.PNG)

**Comment by monicaleite** [comment]
Corrigido.

**Comment by jmatil** [comment]
Confirmado a inclusão conforme documentação atualizada e disponibilizada no GIT
