### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Quantidade de Registro por Página

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#111]
Há necessidade de inclusão de alguma regra para apresentação máxima de registro(s) por páginas? Pois não foi encontrado algo que referenciasse esse comportamento no caso de uso. Favor avaliar o fluxo 5:

![capturar](https://cloud.githubusercontent.com/assets/6584772/6525990/656027a0-c3eb-11e4-9e3a-07e24ad7f84d.PNG)

**Comment by monicaleite** [comment]
Incluída a RAP008 em todos os casos de uso que possuem esse fluxo alternativo

**Comment by jmatil** [comment]
Confirmado a inclusão conforme documentação atualizada e disponibilizada no GIT
