### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Citações

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#112]
Existem regras de Negócio e de apresentação que citam o caso de uso, mas não há relato na própria documentação "CDU" de que essas regras são chamadas.
Existem citações de regras no próprio caso de uso que não são referenciadas no próprio documento de regras de negócio.
As Regras 1, 2, 3, 4, 13, 14 são citadas na documentação do CDU, mas não há relatos na RN de que este caso de uso utilizará estas regras.
O mesmo ocorre com as RAPs 4, 8.

As RNs 29 e 35 citam que o CDU utiliza estas regras, mas não foram encontrados citações na documentação do "CDU".
O mesmo ocorre com as RAPs 21 e 45.

Favor verificar a necessidade de ajustes destes itens citados acima.

**Comment by monicaleite** [comment]
O caso de uso foi referenciado nas RN's 1, 2, 3, 4, 13, 14
A RN29 foi descontinuada, colocado essa informação no documento de regra.
A RN35 foi referenciada no fluxo de inclusão.
A RAP21 foi referenciada no passo 5 do FB.
A RAP045 foi referencida no passo 2 do FA4.

**Comment by jmatil** [comment]
Confirmado
