### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RAP 48 - Campo ano

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#114]
Boa tarde Mônica,

A RAP 48 não trata do campo <b>ano</b>. Quais são os anos válidos? Como será a exibição do campo, trata-sem de um select?

**Comment by monicaleite** [comment]
Na tela de pesquisa ele pode informar qualquer ano, desde que seja no formato válido, conforme validação feita pelo FE4.

**Comment by rsantanam** [comment]
Môncia, poderia informar alguns exemplos de anos inválidos? Quanto ao calendário ao lado do campo  Ano : 
![image](https://cloud.githubusercontent.com/assets/6524452/6596101/bac949f0-c7cf-11e4-8398-70789a3ae82e.png)
Deve ser removido?

**Comment by monicaleite** [comment]
Rogério,

Corrigindo a validação da data é na pesquisa, nesse campo não terá validação, vou retirar essa calendário e deixa para que o usuário digite o ano.
A única resposta para um ano não existente será de nenhum registro encontrado.

**Comment by rsantanam** [comment]
Ok
