### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RAP 49

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#115]
Mônica,

Na RAP 49 diz que sistema deve executar os procedimentos independente dos status? Caso sim o botão de execução poderia ficar desabilitado caso não exista registro na lista, dessa forma talvez <b>não</b> seja necessário a exibição da mensagem. 

Esse é o entendimento correto?

**Comment by monicaleite** [comment]
Rogério,

O botão estará desabilitado conforme a regra e a mensagem deverá existir como forma de orientação para a unidade logada.

**Comment by rsantanam** [comment]
Ok Mônica
