### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RN43 - Atualização automática

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#116]
Mônica,

A RN043 diz que <i><b>"O procedimento será fechado manualmente pelo painel de controle ou automaticamente quando a data limite for ultrapassada..."</b></i>, para o caso da atualização automática deverá existir uma rotina que será disparada onde esses registros serão atualizados?

**Comment by monicaleite** [comment]
o sistema deverá verificar se a data atual é a data limite para execução do procedimento, assim que ultrapassar o dia o sistema deverá finalizar e guardar o status de finalizado.

**Comment by rsantanam** [comment]
Dessa forma deverá existir uma rotina, que será executada em algum horário, para atualização dessa informação?

**Comment by monicaleite** [comment]
Rogério,

Como será feito eu não sei, isso é definido pelo desenvolvimento, o como a regra será atendida, não foi definido horário de verificação, agora como não pode passar da data limite então a verificação acredito eu deverá ser feita as 23:59, algo do tipo.

**Comment by rsantanam** [comment]
Ok.
