### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Campo CATEGORIA, GRUPO e QUESITO

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#117]
Na tela PT2 existe a descrição dos campos CATEGORIA, GRUPO e QUESITO que não existem na imagem de exemplo do sistema. Onde deveram estar tais campos?

**Comment by monicaleite** [comment]
Rogério,

Retirei a PT4 e coloquei na PT2, pois estava duplicado a tela de painel de controle. O documento está atualizado no git.

**Comment by rsantanam** [comment]
ok
