### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RN43

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#118]
Mônica,

Na RN43, caso o procedimento não tenha sido totalmente preenchido e alcance a data limite como o sistema deve se comportar? O sistema deverá "Finalizar" independente de preenchimento?

**Comment by monicaleite** [comment]
Rogério,

Conforme RN43, alcançando a data limite o sistema irá finalizar mesmo que o usuário não tenha concluído.

**Comment by rsantanam** [comment]
Ok Mônica, obrigado.
