### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Tamanhos das respostas

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#119]
Mônica,

A tela de Executar Procedimento deverá limitar o tamanho das respostas conforme o definido nos  campos de <b>tamanho mínimo</b> e <b>tamanho máximo</b> da tela de Manter Tipo Resposta. A RAP 59, que define os tamanhos de cada campo foi incluída e ainda não foi implementada. Neste caso como devemos proceder no que se refere a limitação dos tamanhos das respostas?

**Comment by monicaleite** [comment]
Rogério,

Para o caso de data já tem o fluxo de exceção de data inválida.
Para o caso de máximo de caracteres o sistema deverá barrar a digitação do usuário quando ele chegar no limite, acredito que não precise de criar exceção para isso.
Para horário que existe a possibilidade de informar de ___ até ____, não tem nenhuma validação quanto a formato, será necessário?

**Comment by rsantanam** [comment]
Neste caso seguiremos a validação de tamanho máximo, conforme cadastrado na tela de cadastro do Tipo Resposta, ok?

**Comment by monicaleite** [comment]
ok, Rogério.
