### ISSUE TITLE
CDU_SICEL_003_Manter Grupo - Descrição do campo "Nome do Grupo"

### ISSUE THREAD

**Issue by imotac** [islssa/SICEL#12]
Nas tabelas correspondentes à “Interface do fluxo de eventos Incluir Grupo” e à “Interface do fluxo de eventos Editar Grupo”, a descrição do campo “Nome do Grupo” está com o texto “Nome da Categoria”. Necessário ajustar a documentação.

**Comment by monicaleite** [comment]
Realizado o ajuste.
