### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Quantidade de Grupos

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#120]
Mônica,

Na tela de <b>Executar Procedimento</b> (PT.2) poderá haver mais de um grupo listado por categoria do procedimento ou apenas um grupo?

**Comment by monicaleite** [comment]
Terá a quantidade de grupos criado no roteiro (CDU005 Manter Roteiro), poderá ter mais de um.

**Comment by rsantanam** [comment]
Ok
