### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Ícones

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#121]
Mônica,

Os ícones que deverão ser exibidos na tela de Executar Procedimento (
![image](https://cloud.githubusercontent.com/assets/6524452/6752686/505ec14a-ceef-11e4-991f-7e2c3326399f.png), ![image](https://cloud.githubusercontent.com/assets/6524452/6752692/554da586-ceef-11e4-8472-a006c008f500.png))  não estão no repositório de ícones do TSE (http://intranet.tse.jus.br/menu_institucional/unidades/secretaria_sgi/coordenadoria_cedip/secao_seapi/padronizacao-sistemas/biblioteca-icones.html) .
Como proceder?

**Comment by monicaleite** [comment]
Rogério,

Para o Executar procedimento pode seguir conforme o protótipo, ainda que fique fora do padrão do TSe, já encaminhei um e-mail para o GP.

**Comment by rsantanam** [comment]
Ok Mônica, assim que tiver a resposta do GP sobre os ícones retorne a issue por favor.

**Comment by monicaleite** [comment]
Conforme conversamos os ícones deverão ser igual ao do protótipo, não tem como seguir o padrão.

**Comment by rsantanam** [comment]
Ok Mônica, obrigado.
