### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Campo Observação

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#127]
Mônica,

O campo <b>Observação</b> é referente ao tipo de resposta ou trata-se de um campo que sempre deverá existir para cada agrupamento do Roteiro?

Essa dúvida surgiu porque existe a possibilidade de cadastro de um "Tipo de Resposta" classificado como <b>Observação</b>.

**Comment by monicaleite** [comment]
No tipo de resposta tem a opção observação e no Executar procedimento a cada "grupo" ou no caso de roteiro só de quesitos também terá automaticamente esse campo observação. Então caso o usuário coloque um quesito observação, além desse observação também terá o observação ao final dos quesitos.
