### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RAP 50

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#128]
Mônica,

Na tela de executar procedimento terá uma aba onde conterá todos os quesitos vinculados diretamente ao roteiro(sem grupo e categoria). A RAP 50 diz que devo exibir o campo "Descrição" como sendo a composição da  [descrição do roteiro] : [nome da categoria].

Como devo exibir para os casos onde onde os quesitos são vinculados diretamente ao roteiro? A mesma dúvida se estende aos demais itens sinalizados na imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/6524452/6952061/aff82d08-d895-11e4-8bca-b3a9e900a26d.png)

**Comment by monicaleite** [comment]
Rogério,

Complementei a RAP050.
No caso quando o roteiro for só de quesitos o sistema irá listar do lado direito os quesitos e na parte superior ele irá exibir a descrição do caso de uso Manter Roteiro e o quesito selecionado.
No campo XXX do exemplo acima ele não existirá, pois é um roteiro só de quesitos então ele começará do item 1 em diante sem o "nome do grupo".

**Comment by rsantanam** [comment]
OK, Mônica.
