### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Validação para resposta

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#129]
Mônica,

Deve ou deverá haver alguma validação para as respostas informadas no momento em que Salvar as respostas na execução do procedimento?

Na tela de Tipo Resposta podemos cadastrar um valor mínimo, por exemplo, e caso usuário informe uma resposta com quantidade menos de caracteres como o sistema ira se comportar?
Espero que tenha ficado claro a minha dúvida!

**Comment by monicaleite** [comment]
Rogério, 

A RAP059 que foi alterada por conta da SM diz sobre apenas campos com tamanho máximo, nesse caso pode ser feito como já havíamos conversado, quando alcançar o limite máximo o sistema não deixa mais o usuário digitar.
Para validação de data já existe o fluxo de exceção FE4.

**Comment by rsantanam** [comment]
...mas e quando tiver tamanho mínimo?

**Comment by monicaleite** [comment]
Não tem tipo de resposta que tem essa opção. Isso foi retirado.

**Comment by rsantanam** [comment]
Ok Môncia.
