### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - RAP027

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#131]
Monica,

A RAP027 só será apresentada na aba dos Procedimentos <b>Finalizados</b>?

**Comment by monicaleite** [comment]
Joel, 

No meu entendimento é uma estatística que fala sobre os procedimentos finalizados e não que será apresentada a estatística apenas aos finalizados, enquanto não finalizado ele exibe o percentual respondido.

**Comment by jadossantos** [comment]
Monica,
Segundo a documentação a RAP027 só é apresentada na aba supracitada.
Sendo que a coluna que faz referência a esta RAP existe nas abas <b>Em execução</b> e <b>Finalizada</b>. 
O icones verde e amarelo serão apresentados apenas na aba <b>Finalizada</b>?

**Comment by monicaleite** [comment]
Isso com a quantidade de 100%.

**Comment by jadossantos** [comment]
Ok.

**Comment by raynerweb** [comment]
poderiam me retirar do islssa ? vlw

Ráyner Carvalho Lima

2015-04-17 9:16 GMT-03:00 Joel Amálio notifications@github.com:
