### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Acessibilidade da aba "Relatório"

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#132]
É possível acessar esta aba a qualquer momento? Mesmo no momento de cadastro de um novo <b>Procedimento</b>?

**Comment by monicaleite** [comment]
Se não existe nenhuma regra que fale o contrário Joel, então sim ela poderá ser acessada, o que ocorrerá é que ao tentar gerar o relatório o sistema emitirá um documento sem nenhuma informação.

**Comment by jadossantos** [comment]
Ok.

**Comment by rsantanam** [comment]
A aba de relatorio e documento só estará ativa após salvar um procedimento e na sua edição, conforme #143.
