### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Campo nome (PT1)

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#133]
Segundo a PT1 o nome do Procedimento será exibido, porém essa campo não existe.

Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
O nome do procedimento está no topo da tela com procedimento XXXXX.

**Comment by jadossantos** [comment]
Eu quis dizer que o campo <b>nome</b> não existe no cadastro do <b>Procedimento</b>. Como iremos obter essa informação?

Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
O campo foi retirado e a documentação atualizada.

**Comment by jadossantos** [comment]
ok
