### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Ações da PT1

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#134]
A descrição das ações da PT1 estão incompletas.

Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
incompletas como Joel, preciso que você seja mais específico para que eu possa ajusta, em caso de relatório se a questão for tamanho de campo não definimos isso nesses casos de uso.

**Comment by jadossantos** [comment]
Segue abaixo a imagem do problema:

![cd011_pt1](https://cloud.githubusercontent.com/assets/7116054/7045138/7cea7308-ddd1-11e4-9989-e13205397d18.png)

**Comment by monicaleite** [comment]
Ajustado. Obrigada.

**Comment by jadossantos** [comment]
Ok.
