### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Botão Voltar da PT2 e PT3

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#136]
Qual será o comportamento da tela caso o usuário selecione algum item e não clique no botão <b>Salvar</b>?

**Comment by monicaleite** [comment]
Caso não tenha nda escrito em regra o sistema não realizará nenhuma ação, permanecerá na tela até alguma ação por parte do usuário seja feita.

**Comment by jadossantos** [comment]
Então os botões <b>Voltar</b> e <b>Salvar</b> terão o mesmo comportamento, ou seja, voltarão para tela principal com os itens que foram selecionados (em memória)?

**Comment by monicaleite** [comment]
Não...se ele está numa tela de seleção, seleciona itens e não faz nada, ele permanece na tela de seleção, agora se ele aciona voltar então ele voltará para a tela anterior ou conforme descrito no passo.

**Comment by rsantanam** [comment]
Ok
