### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Detalhamento da FA8

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#137]
Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
O que é para ser ajustado?

**Comment by jadossantos** [comment]
Os itens <b>4</b> e <b>5</b> estão se referindo ao fluxo <b>FA7</b>.

**Comment by monicaleite** [comment]
A documentação foi ajustada. Obrigada.

**Comment by jadossantos** [comment]
Ok.
