### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Colunas da PT5

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#138]
As colunas "Conforme", "Não Conforme", "Exige Aperfeçoamento" e "Não se aplica" são exemplos de <b>Tipos de Repostas</b> cadastrados pelo "SICEL_CDU_001_Manter Tipo de Resposta"? Caso afirmativo, essa coluna terá um tamanho variável?

**Comment by monicaleite** [comment]
Essa informação vc buscou de qual regra? No caso ele quer um relatório que possua essas respostas.

**Comment by jadossantos** [comment]
O questionamento é exatamente por não existir nenhuma RN ou RAP vinculada ao relatório. 

No "SICEL_CDU_001_Manter Tipo de Resposta" não existe nenhum dos valores abaixo:
- Conforme;
- Não Conforme;
- Exige Aperfeçoamento;
  -Não se aplica;

![image](https://cloud.githubusercontent.com/assets/7116054/7045374/03830022-ddd4-11e4-99b1-a1fa00d46823.png)

Por isso perguntei se esses valores são exemplos de <b>Tipos de Repostas</b> e a tabela do relatório terá uma quantidade variável de colunas. O entendimento é esse?

**Comment by monicaleite** [comment]
Essas informações serão cadastradas no tipo de resposta, por saber que esses tipos de respostas estão em um documento oficial, sabemos que elas existirão dessa forma, assim o cliente assume o risco se não existir não ter como gerar esse quantitativo. É um tipo de resposta "Escolha", onde ele irá cadastrar essas opções e o relatório deverá buscar lá no executar a quantidade que cada unidade eleitoral informou para cada.

**Comment by jadossantos** [comment]
Ok. Você poderia criar uma RAP detalhando isso?

**Comment by monicaleite** [comment]
Criada a RAP068 referenciada no FA2 passo 2.

**Comment by jadossantos** [comment]
Ok.
