### ISSUE TITLE
CDU_SICEL_003_Manter Grupo - Comando "Avançar"

### ISSUE THREAD

**Issue by imotac** [islssa/SICEL#14]
Na tabela correspondente à “Interface do fluxo de eventos Editar Grupo”, existe o comando “Avançar”, mas este comando não está presente no protótipo, provavelmente foi reaproveitado do “CDU_SICEL_002_Manter Categoria”. Necessário ajustar a documentação.

**Comment by monicaleite** [comment]
Documentação foi ajustada.
