### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - PT14 campo Ano

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#141]
Tem uma RAP no campo "Ano" sem numeração.

Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
Ajustado para RAP024.

**Comment by jadossantos** [comment]
Acredito que a <b>RAP024</b> não atende ao propósito do campo <b>Ano</b> na tela de detalhamento.

![git141](https://cloud.githubusercontent.com/assets/7116054/7046035/789b13d6-ddd9-11e4-9850-c5142099715f.png)

Por favor, verificar a documentação.

**Comment by monicaleite** [comment]
Foi retirada a RAP, o ano a ser exibido é o que foi gravado para o procedimento em questão.

**Comment by jadossantos** [comment]
Ok.

**Comment by jadossantos** [comment]
O campo <b>Ano</b> será um campo texto ou um combo?

**Comment by monicaleite** [comment]
Campo para que o usuário digite o ano., não é combo.

**Comment by jadossantos** [comment]
O campo <b>Ano</b> está vinculado a RAP024, que fala: <b>O campo “Ano” deve vim por default preenchido com o ano atual e trazer todos os anos em que possuem um procedimento.</b>. Essa RAP é aplicável à Combos e não a campos Texto.

**Comment by monicaleite** [comment]
Na verdade é sobre a PT14 né, olhei errado, na PT14 não tem regra, é apenas o detalhamento do que já foi informado.

**Comment by jadossantos** [comment]
É que aproveitei essa issue para falar do mesmo campo (Ano) nas PT 4 e 7.

Poderia verificar a regra?

**Comment by monicaleite** [comment]
Joel,

Mexi novamente na regra e retirei a parte que fala que carrega ano, então esse campo será para o usuário informar, porém por default vem com o ano atual, conforme a regra.

**Comment by jadossantos** [comment]
ok.

**Comment by monicaleite** [comment]
JOel,

Conforme conversamos, alterei a RAP024.
