### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Acessibilidade das abas "Documento" e "Relatório"

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#143]
Segundo a documentação as abas "Documento" e "Relatório" só serão apresentadas no momento da edição de um registro.

Por favor, verificar a documentação para tal comportamento.

**Comment by monicaleite** [comment]
Joel,

Onde na documentação existe a referência dessa informação? Tem regra falando isso? Não identifiquei.

**Comment by jadossantos** [comment]
No fluxo <b>FA1</b> existe o passo 2 "O sistema apresenta os campos para inclusão dos dados; [PT 4] [PT 5] [PT 6] [RAP041]", que tem as telas <b>PT4</b> (Incluir Novo Procedimento - Aba Procedimento), <b>PT5</b> (Incluir Novo Procedimento -  Aba Roteiro) e <b>PT6</b> (Incluir Novo Procedimento -  Aba Unidade Eleitoral).

No fluxo <b>FA2</b> existe o passo 2 "O sistema apresenta os campos para edição dos dados; [PT 7] [PT 8] [PT 9] [PE1] [PE2] [RAP041] [RN048]", que tem as telas <b>PT7</b> (Alterar Procedimento -  Aba Procedimento), <b>PT8</b> (Alterar Procedimento -  Aba Roteiro) e <b>PT9</b> (Alterar Procedimento -  Aba Unidade Eleitoral), e os pontos de extensão <b>PE1</b> (Manter Documentos) e <b>PE2</b> (Manter Relatório).

Os PEs só são apresentados no fluxo de edição do <b>Procedimento</b>, ou seja, as abas <b>Documentos</b> e <b>Relatório</b> só serão apresentadas nesse fluxo (FA2).

**Comment by monicaleite** [comment]
Joel,

Entrei em contato com o Elder por telefone e expus a informação acima, ele informou que as abas deverão está disponíveis na inclusão e alteração, logo já corrigi a documentação. Obrigada.

**Comment by jadossantos** [comment]
As abas só ficarão disponíveis após o usuário salvar o registro, conforme contato com o Rogério.

**Comment by monicaleite** [comment]
Correto.
