### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - PT7 (campo "Seguro? Preencha a senha" )

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#144]
O campo "Seguro? Preencha a senha" está associado a RN032. Isso está correto?

**Comment by monicaleite** [comment]
Pelo que vi da regra está correto sim, pq não estaria?

2.34    RN034 – Senha de procedimento
Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Procedimento
A senha cadastrada no incluir procedimento, é a criptografia para executar o procedimento.

**Comment by jadossantos** [comment]
No "SICEL_CDU_007_Manter Procedimento" a regra referenciada é a "RN032 – Status do roteiro" e você apresentou a RN034.

Por favor, ajustar a documentação.

**Comment by monicaleite** [comment]
O documento foi ajustado. Obrigada.

**Comment by jadossantos** [comment]
Ok.

**Comment by jadossantos** [comment]
Quando o usuário digitar um valor no campo <b>senha</b> será visível ou será apresentado o símbolo <b>*</b> em cada carácter digitado?

Qual é o tamanho máximo do campo senha na tela de cadastro?

Como será apresentada a senha no campo na tela de alteração? Favor corrigir a RN referenciada.

**Comment by monicaleite** [comment]
A RN034 foi ajustada e o fluxo FE6 foi criado no caso de uso Manter Procedimento, para atender caso contenha mais ou menos de 8 caracteres e não contenha letra e números. Na edição ele pode alterar a senha se quiser, desde que seja conforme a regra.

**Comment by jadossantos** [comment]
Ok.
