### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Tipo modelo do documento

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#145]
Mônica,

Na inclusão de um anexo, através da funcionalidade Executar Procedimento, deverá existir um tipo modelo de documento associado? O questionamento surgiu pelo fato de que o tipo do modelo é obrigatório para a tela de Manter Procedimento.

**Comment by monicaleite** [comment]
No executar procedimento não é obrigatório documento, se excluir do Executar ele permanece então no Procedimento já que lá é obrigatório.

**Comment by rsantanam** [comment]
O arquivo anexado na funcionalidade Executar não terá obrigatoriedade do Tipo Modelo Documento, essa obrigatoriedade será tratada apenas na funcionalidade Manter Procedimento, correto?

Não entendi quando disse <i>"ele permanece então no Procedimento já que lá é obrigatório"<i/> já que arquivo anexado ao Procedimento é comum as duas funcionalidades conforme a RAP55.

**Comment by monicaleite** [comment]
Não consegui compreender a pergunta, acredito que seja melhor pelo lync ou telefone.

**Comment by monicaleite** [comment]
Rogério o documento foi corrigido, favor verificar.

**Comment by rsantanam** [comment]
Ok, Mônica.
