### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - RAP025 vinculada a PT6 e PT9

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#147]
A RAP025 fala dos roteiros e não das unidades eleitorais.

Favor corrigir a documentação.

**Comment by monicaleite** [comment]
Incluída a RN046 na PT6 e retirada a RAP025 da PT9.

**Comment by jadossantos** [comment]
A RN046 não seria para mudar da aba <b>Roteiro</b> para <b>Unidade Eleitoral</b>?

**Comment by monicaleite** [comment]
JOel,
Eu entendi que poderia ser referenciado pq ele precisaria incluir um roteiro para segui, o que vc acha que precisa ser feito para resolver o problema? Você conseguiu identificar outra que seria melhor para ser informada nesse campo? Tirar somente a regra e não deixar nada ou criar uma nova apenas para informar que ele lista? Eu não consegui achar outra que se encaixa.

**Comment by jadossantos** [comment]
As telas PT6 e PT9 tratam das <b>unidades eleitorais</b> vinculadas ao Procedimento  e as telas PT5 e PT8 falam dos roteiros vinculados ao Procedimento. Portanto, a <b>RN046</b> não se encaixa nas telas das <b>unidades eleitorais</b> e sim nas de Roteiro.

**Comment by monicaleite** [comment]
Regra foi retirada.

**Comment by jadossantos** [comment]
ok.
