### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Botão inserir nas PT 5 e 8

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#148]
Qual será o comportamento do botão <b>inserir</b>, caso o usuário não selecione nenhum roteiro?

**Comment by monicaleite** [comment]
o Roteiro é um campo obrigatório, aplica a exceção de obrigatoriedade de preenchimento.

**Comment by jadossantos** [comment]
Esse fluxo tá descrito no CDU?

**Comment by monicaleite** [comment]
O fluxo é o FE1 e está sendo chamado no incluir e editar procedimento.

**Comment by jadossantos** [comment]
ok.
