### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Campo "Todas as unidades"

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#149]
Qual é a função do check <b>Todas as unidades</b>?

O detalhamento dele no CDU está confuso:

![image](https://cloud.githubusercontent.com/assets/7116054/7121215/59fffe78-e1e9-11e4-8547-a8e612a6a985.png)

**Comment by monicaleite** [comment]
Campo que permite vincular todas as unidades eleitorais ao procedimento que está sendo criado.

**Comment by jadossantos** [comment]
Ok. Precisarei alterar o Modelo Físico, pois inicialmente criamos uma campo para ser persistido.

**Comment by jadossantos** [comment]
Ok. Precisarei alterar o Modelo Físico, pois inicialmente criamos uma campo para ser persistido.

**Comment by monicaleite** [comment]
Voltou pra mim a issue, pq? Preciso alterar algo?

**Comment by jadossantos** [comment]
Não. Irei fechar.
