### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Campos do tipo Data

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#150]
Os campos do tipo <b>Data</b> terão algum tipo de validação?

**Comment by monicaleite** [comment]
Joel,

Não foi inserido para o caso de uso, mas posso colocar o data inválida para validar o formato. Pode ser ou deixamos como foi homologado??

**Comment by jadossantos** [comment]
Apenas estamos alertando possíveis falhas no documento. 
Você juntamente com o cliente irão decidir como o sistema deverá se comportar nas diversas situações e cada correção/alteração apresenta um impacto no desenvolvimento.

**Comment by monicaleite** [comment]
Então apresentei isso pq o Enzo não apresentou essa possibilidade e minha pergunta foi exatamente para saber em relação  a impacto e prazo para esse ajuste, o cliente já homologou e não irá cobrar validação de data visto que no documento não tinha, só que se você me fala que poderá fazer sem grande impacto e que é simples, então eu mudo e nem preciso falar com ele por saber que precisaria sim de uma validação, agora se você me diz que vai atrapalhar muti o prazo, então deixa como está.

**Comment by jadossantos** [comment]
Conforme conversamos por telefone, não iremos fazer essas validações já que não foram solicitadas inicialmente no documento. Caso o cliente ache necessário iremos fazer através de uma Solicitação de Mudança.
