### ISSUE TITLE
SICEL_CDU_011_Relatório do Procedimento - Relatório Consolidado

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#151]
Mônica,

O campo em destaque na imagem (PT.6 Relatório Consolidado) não tem descrição clara na documentação, poderia verificar?

![image](https://cloud.githubusercontent.com/assets/6524452/7122983/67d46eba-e1f5-11e4-919f-8f5f765aedb6.png)

**Comment by monicaleite** [comment]
Rogério,

Entrei em contato com o Elder e foi criada a RAP070 para explicar o campo.

**Comment by rsantanam** [comment]
ok
