### ISSUE TITLE
SICEL_CDU_011_Relatório do Procedimento - Relatório Pontuação

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#152]
Mônica,

O relatório pontuação , PT.7, apresenta diversos campos sem explicação na documentação, segue em destaque:
![image](https://cloud.githubusercontent.com/assets/6524452/7123768/e79524d2-e1fa-11e4-8bde-e22d0c13c3a9.png)

Poderia verificar?

**Comment by monicaleite** [comment]
Rogério,

O Clebson que é o cliente está de férias e o Elder também não soube explicar exatamente como funciona esse relatório, encaminhamos para outra pessoa da área para obtermos a resposta. Assim que tiver um parecer eu te informo.

**Comment by monicaleite** [comment]
Rogério,

Em reunião com o cliente ficou definido que será exibido o número da zona e a quantidade de pontuação que ela fez respondendo todos os quesitos do grupo.
Ex: A Zona 001 respondeu os quesitos abaixo da seguinte forma:
Quesito A = Não se aplica (peso 0)
Quesito B = Conforme  (peso 3)
Quesito C = Não conforme (peso 1)
Quesito D = Exige Aperfeiçoamento (2)

0001(número da zona):6 (pontuação conforme a soma das respostas dada pela zona)

OBS: O nome da Zona e a média serão retirados do relatório.

**Comment by rsantanam** [comment]
O relatório é para quesitos respondidos pelas zonas e que são do tipo escolha, sendo que :
       001        -        XX        :  xx
(nº da zona) - (pontuação) : (?)

O ultimo campo será removido?

**Comment by monicaleite** [comment]
onde está pontuação era o nome da zona era número - nome e pontuação
o Nome será removido a pontuação continua e assume o lugar do nome.

**Comment by rsantanam** [comment]
Ok
