### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Problema no FA10

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#154]
O <b>FA 10</b> está com as informações do <b>FA 9</b>.

Favor corrigir a documentação.

**Comment by monicaleite** [comment]
Joel, 

Acho que está igual e com títulos diferentes pq ele quis mostrar que pode alterar individualmente ou para todas as unidades, mas forma como isso é feito é igual.

**Comment by jadossantos** [comment]
ok.
