### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Acessibilidade dos Fluxos 9 e 10

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#155]
Os fluxos <b>FA 9</b> e <b>FA 10</b> são acessíveis a partir de quais fluxos? 

Segundo a documentação atual, só seria possível no <b>FA 2</b> (edição), mas acredito que poderíamos acessar pelo <b>FA 1</b> (inclusão).

**Comment by monicaleite** [comment]
Referenciado no fluxo FA2.

**Comment by jadossantos** [comment]
Não é possível alterar a data de limite na tela de inclusão?

**Comment by monicaleite** [comment]
FA1 errei na digitação, já está corrigido na documentação.

**Comment by jadossantos** [comment]
ok.
