### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Tela da FA 11

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#156]
Mônica,

Poderia detalhar melhor a geração do gráfico da <b>PT 12</b>?

Obs.: É preciso corrigir a descrição dos campos <b>Carimbo</b>, <b>Data Carimbo</b>.

**Comment by monicaleite** [comment]
Joel, 

Melhorei a descrição do gráfico e criei a RAP071, quanto a descrição dos campos Carimbo, Data Carimbo eu já tinha alterado e até informado no histórico e em outros git's que eles não serão "usados" apesar de constar na aplicação, por falta de definição do gestor.

**Comment by jadossantos** [comment]
ok.
