### ISSUE TITLE
SICEL_CDU_007_Manter_Procedimento -  RAP027

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#157]
Mônica,

Na exibição da grid de procedimento finalizado existe situações onde o ícone tratado na RAP027 não é exibido, esse comportamento é correto?

![image](https://cloud.githubusercontent.com/assets/6524452/7210162/e0d21abe-e525-11e4-93db-1515666e551f.png)

Caso tenha respondido completamente o procedimento e a data atual seja maior que a data fim nenhuma condição é atendida.

**Comment by monicaleite** [comment]
Rogério,

Como é a "aba" de finalizados apenas deve aparecer o ícone para os que foram concluídos, o demais não deve mostrar nada, como não tem uma regra expressa para os finalizados antes do prazo, vamos deixar assim e caso o gestor queira, deverá solicitar que uma nova regra de verificação seja feita.

**Comment by rsantanam** [comment]
Ok,  a RAP27 vai ser alterada?

**Comment by monicaleite** [comment]
Rogério,

Vou verificar na reunião de hoje como ficará essa situação.

**Comment by monicaleite** [comment]
Rogério, 

Em reunião com o cliente, ficou decidido que nesse caso não deverá ser exibido nada, pois a mudança nisso implicaria em nova regra e alterações, com o fim do contrato, optou-se por não tratar essa questão agora.

**Comment by rsantanam** [comment]
OK Mônica, obrigado.
