### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Fluxo FA12

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#158]
O Fluxo <b>FA 12</b> é o mesmo que clicar na aba <b>Documentos</b> (SICEL_CDU_010_Manter Documento de Procedimento)?

**Comment by monicaleite** [comment]
Joel,

Pelo início do fluxo "Este fluxo se inicia quando o ator seleciona a opção “Visualizar Documentos” no passo 2 do fluxo FA 2." e no passo 2 ele chama o ponto de extensão PE1 Manter Documentos, então sim esse fluxo é chamada dos documentos que foram incluídos no caso de uso SICEL_CDU_010_Manter Documento de Procedimento.

**Comment by jadossantos** [comment]
Ok, mas os documentos cadastrados no CDU 10 são do procedimento ou deveriam ser de uma unidade eleitoral?

**Comment by monicaleite** [comment]
Joel,

Na tela PT10 diz que é da "Zona eleitoral - XXX", então é por unidade eleitoral que pertence ao procedimento em questão ao qual o documento foi inserido.

**Comment by jadossantos** [comment]
Ok. Fiz um ajuste (inclusão de FK com a tabela AMBIENTE_ODIN) no MF.
