### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Filtro de Pesquisa_Campo Ano

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#159]
Prezados,

O campo [Ano] conforme tela em anexo, ao colocar caracteres que não sejam números a aplicação exibe a mensagem de erro.
![1](https://cloud.githubusercontent.com/assets/9218077/7326063/04e7b738-ea99-11e4-9da9-5e2c46fe86ed.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !

**Comment by kleiberfaria** [comment]
Item verificado, porém o erro ainda persite conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7658922/b8186164-fb14-11e4-8532-68e3c23515d0.png)
