### ISSUE TITLE
CDU_SICEL_003_Manter Grupo - Divergências entre fluxo e protótipo

### ISSUE THREAD

**Issue by imotac** [islssa/SICEL#16]
O FA 5.1 obriga a seleção da opção “Escolha” no campo “Classe”, mas este campo não está presente no protótipo. Este passo é procedente?

**Comment by monicaleite** [comment]
Documentação foi ajustada.

**Comment by imotac** [comment]
O FA 5.1, após o ajuste realizado, define que os campos só serão apresentados após o acionamento do comando "Adicionar Quesito", mas o que me parece é que os campos já estarão exibidos e limpos e o comando "Adicionar Quesito" seria para adicionar o quesito à tabela  "Quesitos cadastrados" e posteriormente limpar os campos. Meu entendimento está correto?

**Comment by monicaleite** [comment]
o campos serão exibidos, mas a inclusão deles na lista será mediante o acionamento da opção "Adicionar Quesito".

**Comment by vogoncalves** [comment]
A dúvida foi esclarecida. Esta issue será fechada.
