### ISSUE TITLE
SICEL_CDU_006_Manter Tipo de Procedimento - Fluxo FA2 - MSG012

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#160]
Poderia detalhar melhor a mensagem 012?

**Comment by monicaleite** [comment]
Joel,

Conforme conversamos, irei verificar com o Elder se é possível apenas fixar o status para "Em execução"
Mudei a mensagem para ficar assim 
O  <nome do registro> pertence ao (s) roteiro(s)  que está sendo utilizado no procedimento com <status>. Confirma edição?

A definição do status irei verificar com o Elder, que está ausente, encaminhei um e-mail para ele com cópia pra vc.

**Comment by monicaleite** [comment]
Joel,

Conforme e-mail enviado pelo Elder podemos filtrar apenas os procedimentos com status "Em Execução", a documentação estarei alterando posteriormente.

**Comment by rsantanam** [comment]
Ficamos aguardando a atualização da documentação.

**Comment by monicaleite** [comment]
Mas essa alteração não prejudicará o andamento, visto que a decisão já foi definida e já foi repassada, apenas fica pendência de atualizar a documentação.

**Comment by monicaleite** [comment]
Alterado.

**Comment by jadossantos** [comment]
Rogério, por favor, altere a aplicação conforme a nova mensagem.

**Comment by rsantanam** [comment]
Feito.
