### ISSUE TITLE
Geral - RN 003

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#161]
Como será apresentado o trecho abaixo da <b>RN 003</b>?

• Quando o registro a ser excluído estiver sendo usado em um roteiro ou procedimento, o sistema deverá mapear onde está sendo usado, pois será usado como mensagem de alerta/informativa que será apresentada ao usuário;.

A mensagem será apresentada após a exclusão do mesmo?

**Comment by monicaleite** [comment]
Joel, 

Isso foi verificado no fluxo de exclusão no momento em que ele aciona a opção, correto? Nesse caso ele aciona o sistema faz essa validação e exibe a mensagem, após isso realiza exclusão, lembrando que para os registros em execução e finalizados permaneceram com o registros.

**Comment by jadossantos** [comment]
Ok.

**Comment by jadossantos** [comment]
Rogério, por favor, verifique quais CDUs fazem referência a <b>RN003</b> e apresente essa mensagem (lista) após excluir logicamente um determinado registro.

**Comment by rsantanam** [comment]
implementado.
