### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_Procedimento -  RAP018 X RN025

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#162]
Mônica,

A RAP018 diz que os registros <i>Relatório Anual de Atividades, Relatório Mensal de Atividades, Correição Ordinária, Correição Extraordinária e Inspeção serão fixos no banco</i> e a RN025 diz que a CGE pode deletar qualquer tipo de procedimento. Dessa forma, mesmo os itens da carga do banco poderão ser excluídos pela CGE?

**Comment by monicaleite** [comment]
Qualquer tipo exceto os que são fixos no banco.

**Comment by jadossantos** [comment]
Mônica,
Então é necessário alterar a documentação, com a criação de um <b>FE</b> ou <b>RN</b>.

**Comment by monicaleite** [comment]
Não seria necessário fluxo de exceção se não exibir a opção excluir para esses registros, quando a alteração da RN25, irei complementar para informar isso.

**Comment by jadossantos** [comment]
Ok.

**Comment by jadossantos** [comment]
Rogério, por favor, altere a aplicação para não exibir o botão de exclusão nos <b>Tipos de Procedimentos</b> com <i>ST_PREEXISTENTE = EnumSimNao.SIM</i>.

**Comment by rsantanam** [comment]
Ok meu caro, feito.
