### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Fluxo FA 7

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#163]
Mônica,

O que acontece quando salvamos uma nova <b>Categoria</b> na tela <u>Incluir Categoria</u> do <b>Elaborar Roteiro</b>? Esse registro ficará disponível para todos do <b>SICEL</b> ou apenas neste <b>Roteiro</b>?

**Comment by monicaleite** [comment]
A inclusão de uma nova categoria será feito o cadastro no Manter Categoria e será disponível para todos.

**Comment by jadossantos** [comment]
Ok.
