### ISSUE TITLE
SICEL_CDU_006_Manter Tipo de Procedimento - Fluxo FA2 - MSG011

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#164]
Poderia verificar a <b>MSG011</b>? O problema é similar a issue #160.

**Comment by monicaleite** [comment]
Joel,

Foi alterado para seguir o mesmo padrão da MSG012.

**Comment by jadossantos** [comment]
Ok, mas a mensagem <b>MSG011</b> não está sendo referenciada no CDU.

**Comment by monicaleite** [comment]
Joel,

Quem fez esse caso de uso foi o Enzo e ele definiu mensagem e regra diferente, no caso desse o fato de está vinculado é impeditivo então ele precisa retirar o vínculo para excluir, conforme descrito na MSG.

**Comment by jadossantos** [comment]
Monica,

A mensagem <b>MSG011</b> não existe dentro do CDU. 

Favor, atualizar a documentação.

**Comment by monicaleite** [comment]
Joel,

Não é pra ter, existe a MSG006 ou MSG009, conforme descrito no fluxo de exclusão.

**Comment by jadossantos** [comment]
Ok. Então a <b>MSG011</b> não existe no <b>SICEL_CDU_006_Manter Tipo de Procedimento</b>.
