### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - RAP030

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#165]
Monica,

Segue abaixo algumas dúvidas da <b>RAP030</b>:

O trecho abaixo quer diz que é possível <i>pesquisar</i> e <i>adicionar</i> uma <b>Categoria/Grupo/Quesito</b> através da tela de principal de elaboração ou o quê?  
<i>Essa estrutura deverá se repetir sempre que cada um dos itens for preenchido, para caso o usuário deseje possa pesquisar por uma Categoria/Grupo/Quesito para incluir no roteiro.</i>

O item <b>Peso</b> será exibido para todos os <b>Quesitos</b> ou só para os <b>Quesitos</b> vinculados a um <b>Tipo de Resposta</b> da classe <b>Escolha</b>?

**Comment by monicaleite** [comment]
Não entendi ou o que? Ele pode pesquisar e recuperar categoria, grupo ou quesito pela pesquisa autocomplite na tela principal ou pelo adicionar.
Quanto ao peso deve ser exibido apenas para os quesitos com tipo "escolha".

**Comment by jadossantos** [comment]
O CDU não contempla esse fluxo e as exceções de adicionar na tela principal da elaboração?

**Comment by monicaleite** [comment]
o autocomplete não é pra adicionar é para carregar, o adicionar é o botão "mais".

**Comment by jadossantos** [comment]
O botão ![](http://cdn.tse.jus.br/estatico/final/img/adicionar.png) não seria para chamar a tela de inclusão da <b>Categoria/Grupo/Quesito</b>?

**Comment by monicaleite** [comment]
Isso o incluir e também traz se já existir, acho melhor vc me ligar amanhã.

**Comment by jadossantos** [comment]
Ok.
