### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - RAP031 - Grupo

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#166]
Monica,

Para cadastrar um novo <b>Grupo</b> em uma determinada <b>Categoria</b> a única regra é ter um nome diferente dos já cadastrados? 

Anteriormente no <b>SICEL_CDU_003_Manter Grupo</b> também era validado a existência de pelo menos um quesito associado. Isso não será mais validado?

**Comment by monicaleite** [comment]
Joel,

Em conversa com o Elder sugeriu-se manter as informações em memória e realizar o cadastro somente quando o roteiro fosse salvo, assim o sistema iria identificar os quesitos adicionados ao grupo na tela de roteiro.

**Comment by jadossantos** [comment]
A documentação foi alterada para contemplar tal regra.
