### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - PT 8 - Peso

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#167]
O que é o combo <b>PESO</b> e de onde esses valores são carregado?

**Comment by monicaleite** [comment]
Joel, 

Ele será exibido apenas para o quesito do tipo de resposta igual a "Escolha" e será conforme informado no caso de uso Manter Tipo de resposta.
Melhorei a RAP030
• A opção “Peso” no item “Quesito” estará habilitado somente para a CGE e será exibido somente para o tipo de resposta igual a “Escolha” e virá conforme informado no caso de uso Manter Tipo de Resposta.

**Comment by jadossantos** [comment]
Ok.

**Comment by jadossantos** [comment]
Mônica,

Qual valor será cadastro no <b>PESO</b> caso o usuário seja diferente de <b>CGE</b>?

**Comment by monicaleite** [comment]
A opção de mudar o peso no Manter Roteiro é apenas para CGE, lá no Manter Tipo de Resposta vai ser cadastrado pelos atores definidos pelo caso de uso.

**Comment by monicaleite** [comment]
Joel,

Conversei com o Elder e ficou definido que será uma combo de seleção com valor fixo de 1 a 5 em que somente será exibido para a CGE para informar valor.

**Comment by jadossantos** [comment]
ok.

**Comment by jadossantos** [comment]
Monica,

Os valores de 1 a 5 não estão na RAP ou tela. Poderia verificar?

E qual é o significado desses valores? O Leandro me questionou isso.

**Comment by monicaleite** [comment]
Joel, 

Está na descrição da tela, esses valores são pontuações que podem ser atribuídos ao quesito, para um calculo que será feito pela CGE, o qual não é contemplado pelo sistema no momento.

**Comment by jadossantos** [comment]
ok, mas a informação só aparece na PT4 e faltou na PT8.
