### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Fluxo FA 11

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#168]
Quando o usuário excluir um registro que possua filhos a exclusão será realizada em cascata?

A exclusão poderá ser desfeita? Ela será em memória ou direta no banco de dados?

**Comment by monicaleite** [comment]
Joel,

Referenciei a RAP65 também no fluxo de exclusão.
• Excluir: esta opção será exibida apenas para os itens na estrutura que possuírem informações cadastradas (categoria, grupo e quesito), quando não possuir nenhuma informação a opção de excluir não deverá ser exibida.

o   Ao excluir uma categoria, o sistema deverá excluir a categoria e os grupos e os quesitos que pertencem a ele;
 Caso seja cadastro de categoria com quesito, então o sistema deverá excluir a categoria e os quesitos que pertencem a ela.
o   Ao excluir um grupo, o sistema deverá excluir o grupo e os quesitos que pertencem a ele;
o   Ao excluir um quesito, o sistema deverá realizar a exclusão somente desse registro.

**Comment by jadossantos** [comment]
Ok, mas faltou responder o 2º questionamento.

**Comment by monicaleite** [comment]
Os vínculos são excluídos apenas do roteiro, não será feito exclusão de nenhum cadastro base no roteiro.

**Comment by jadossantos** [comment]
ok.
