### ISSUE TITLE
CDU_001_Manter_Tipo_Resposta - SM1 - Fluxo de exceção para tipo de resposta horário  

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#169]
Mônica, 

Não deveria existir um fluxo de exceção para os campos "<b>De</b>" e "<b>Até</b>" já que os campos passam a ser obrigatórios caso o tipo de resposta seja seja  horário?  Seria uma situação similar  ao FE6.

**Comment by monicaleite** [comment]
Joel,

Foi incluído o FE9 no caso de uso.

FE 9.   O valor do campo “DE” não pode ser menor do que o valor do campo “Até”
Nos passos, FA1.4 e FA2.4 , caso o sistema identifique  que o campo horário informado no campo “De” foi preenchido com um valor menor do que o valor do campo “Até”, o sistema deve executar os seguintes passos:a verifica que não o tipo de resposta está sendo utilizada;
FE 9.1      O Sistema apresenta a mensagem [MSG032];
FE 9.2      O ator atesta a mensagem;
FE 9.3      O Fluxo é encerrado.

**Comment by rsantanam** [comment]
Ok.
