### ISSUE TITLE
CDU_001_Manter_Tipo_Resposta - SM1 -  Ordenação por clique 

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#170]
Mônica, 

Na SM1 diz que a grid de escolhas deverá permitir a ordenação, conforme trecho abaixo: 
<i>"Permitir reordenar os itens do tipo escolha pelo clique e arrasto do mouse." </i> 
Como será essa ordenação por clique?

**Comment by monicaleite** [comment]
O comportamento será igual ao do roteiro, onde vc seleciona um registro e arrasta para a posição que deseja.

**Comment by rsantanam** [comment]
Ok.
