### ISSUE TITLE
CDU_001_Manter_Tipo_Resposta - SM1 -  Grid de escolhas

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#171]
Mônica, 

Na SM1 diz que a grid de escolhas deverá permitir a ordenação. Não seria necessário adicionar uma coluna com o <b>Número da escolha</b> ?

![image](https://cloud.githubusercontent.com/assets/6524452/7572225/f62ad60a-f7f2-11e4-924e-deed7f80f519.png)

**Comment by monicaleite** [comment]
Não foi solicitado a coluna Rogério, e essa ordenação vai ser como no roteiro ele seleciona a linha e arrasta para a posição que deseja, nesse caso ele fará o controle pelas as colunas e informações que existem já.

**Comment by rsantanam** [comment]
Ok Mônica.
