### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Label

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#175]
Verificar qual título permanecerá.

![1](https://cloud.githubusercontent.com/assets/6584772/7658822/d0be611a-fb13-11e4-8de8-e0059f84ede4.png)

**Comment by monicaleite** [comment]
O documento foi corrigido.

**Comment by jmatil** [comment]
Correção confirmada

![1](https://cloud.githubusercontent.com/assets/6584772/7680937/d643cfd2-fd41-11e4-89b0-f1bb02c44a34.png)
