### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - ALINHAMENTO

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#176]
Há possibilidade de alinhamento destes itens destacados na tela do sistema?

![1](https://cloud.githubusercontent.com/assets/6584772/7659067/c1b83db0-fb15-11e4-840b-3602e252210c.png)

**Comment by jadossantos** [comment]
Não, pois é o padrão do sistema.

**Comment by jmatil** [comment]
Compreendido
