### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - PADRONIZAÇÃO

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#177]
Verificar a possibilidade de padronização das fonte utilizadas conforme o restante dos títulos que envolvem esta funcionalidade, pois o início de cada palavra está destacado com caixa alta. Somente a página inicial está conforme imagem anexa.
Obs: A documentação exige caixa alta para cada início de palavra.

![1](https://cloud.githubusercontent.com/assets/6584772/7659217/cdf3bf7c-fb16-11e4-8667-6f23e7c1bfa4.png)

**Comment by jadossantos** [comment]
Alterado.

**Comment by jmatil** [comment]
Alteração confirmada

![1](https://cloud.githubusercontent.com/assets/6584772/7680829/dc48cd2a-fd40-11e4-9e80-a84bcc3c94a5.png)
