### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Campo Opção

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#178]
Prezados,
No campo "Opção" o texto no navegador FireFox apresenta quebrando a palavra conforme tela em anexo. 

![1](https://cloud.githubusercontent.com/assets/9218077/7659198/a5b4fef4-fb16-11e4-8342-679f815848b3.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
