### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Quantidade de CARACTERES

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#179]
Verificar a quantidade de caracteres permitidos para o campo destacado na imagem, pois foi utilizado 386 caracteres e acionado a opção salvar. O sistema geral a página anexa abaixo:

INSERÇÃO
![2](https://cloud.githubusercontent.com/assets/6584772/7659375/dc57ff8c-fb17-11e4-8bca-77570beecc7e.png)

RESULTADO
![1](https://cloud.githubusercontent.com/assets/6584772/7659384/ea25d24c-fb17-11e4-885a-ae7e90cb497b.png)

**Comment by jadossantos** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada

![1](https://cloud.githubusercontent.com/assets/6584772/7680902/82dc1c0a-fd41-11e4-9d5a-bf593047ef31.png)
