### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Quantidade de CARACTERES II

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#180]
Foi disponibilizado uma quantidade de caracteres superior a permitida pelo sistema. O sistema não permitiu a realização do cadastro, não emitiu mensagem e não saiu da situação evidênciada na imagem;

![1](https://cloud.githubusercontent.com/assets/6584772/7659587/6daf77ac-fb19-11e4-880d-f496d1a91e95.png)

**Comment by jadossantos** [comment]
Problema de limitação do banco de dados. Alteramos a coluna de <b>varchar2</b> para <b>clob</b>.

**Comment by jmatil** [comment]
Correção confirmada.

![1](https://cloud.githubusercontent.com/assets/6584772/7681044/b1f1bf76-fd42-11e4-9138-155348da7f10.png)
