### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Filtro de Pesquisa_Campo Ano

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#181]
O campo "ANO" está permitindo caracteres especiais e palavras conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7659575/4fe3f162-fb19-11e4-9599-1828ac14db3e.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7659598/8156acda-fb19-11e4-9255-5576c16bac84.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
