### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Navegar para a página

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#182]
No campo apresenta a situação  ["Navegar para a página"] está permitindo caracteres que não seja númericos. 

![1](https://cloud.githubusercontent.com/assets/9218077/7660036/1ca3d200-fb1d-11e4-819f-88e8b16c4820.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
