### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - SALVAR

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#183]
A ação abaixo ocorreu ao acionar o botão "SALVAR". Obs: ação esporádica

![1](https://cloud.githubusercontent.com/assets/6584772/7660044/30855762-fb1d-11e4-8b88-c97c2f14e025.png)

**Comment by jadossantos** [comment]
Problema na <b>UK_TIPO_PROCEDIMENTO_01</b> (banco de dados), pois estava faltando as colunas referente a exclusão lógica.

**Comment by jmatil** [comment]
Retestes foram feito e foi verificado até o momento que o erro não está ocorrendo
