### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Navegar para a página - Dúvida

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#184]
É apresentada na aplicação ["Navegar para a página"] porém na documentação CDU_008 na PT1 . esta sendo apresentado somente como ["Página"]. Segue o que esta na documentação ou o que esta sendo apresentada na aplicação?

![1](https://cloud.githubusercontent.com/assets/9218077/7660220/5c6a273a-fb1e-11e4-839c-e5cc66bc301c.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7660223/60b94cf8-fb1e-11e4-9193-7202bb4c1eff.png)

**Comment by monicaleite** [comment]
Kleiber, 

O sistema deve ser capaz de pesquisar página, não tem problema a alteração do texto não, se esse for o único problema encontrado.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado Mônica.
