### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Pesquisar Página

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#185]
A situação abaixo foi simulada acionado a opção para realização da pesquisa de uma página sem que o ator informe parâmetros no campo. A ação e a mensagem emitida pelo sistema não estão descritos na documentação de regras.

![1](https://cloud.githubusercontent.com/assets/6584772/7681413/7e56812a-fd46-11e4-8856-bba7baad7c5d.png)

**Comment by monicaleite** [comment]
Aguardando posicionamento da equipe de teste quanto ao impacto na documentação, pois não existe essa mensagem na documentação.

**Comment by jmatil** [comment]
A ação foi retirada.
