### ISSUE TITLE
SICEL_CDU_006_Manter_Tipo_de_Procedimento - Editar Tipo de Procedimento

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#186]
Favor avaliar a situação simulada abaixo:
1 ) Foi criado um tipo de procedimento com o nome 'x';
2 ) Foi elaborado um roteiro (Menu -  Elaborar Roteiro), cujo o tipo de procedimento 'x' foi vinculado;
3 ) Foi acessado o Menu: Cadastro / Tipo de Procedimento e doi alterado o nome 'x' para 'Z'.
4 ) Ao avaliar novamente o "Roteiro Elaborado" e que estava vinculado ao roteiro 'x' as informações antigas ainda permaneciam. Ação simulada ao detalhar o "Roteiro Elaborado".

Pergunta: Há necessidade de alguma exceção indicando o vínculo com algum roteiro mesmo sendo somente uma alteração de um item que não esteja no estado de execução?

**Comment by jadossantos** [comment]
Fizemos a correção, porém o versionamento ainda não foi implementado.

**Comment by jmatil** [comment]
correção confirmada
