### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Nome das colunas

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#187]
Prezados,

Conforme tela em anexo , esta sendo apresentada na coluna ["Aberto em"] e na coluna ["Ação"] sendo que na documentação CDU_007 é documentada ["Aberto"] e ["Ações"]

![1](https://cloud.githubusercontent.com/assets/9218077/7686633/9073e9f2-fd6d-11e4-9077-38607c3ac91c.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7686635/94a9ff16-fd6d-11e4-9b4a-2552b2ff69de.png)

**Comment by jadossantos** [comment]
Favor observar a <b>RAP022</b> e a label ação foi mantida para manter um padrão com os demais CDUs..

**Comment by kleiberfaria** [comment]
Item verificado !
4.22    RAP022 – Listagem de procedimentos cadastrados
Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Procedimento

As colunas “Ano”, “Tipo”, “Edição”, “Aberto em”, “Finalizado em”, “Unidade Eleitoral Titular”, ”Total de Unidades executoras”, “Qtd de Procedimentos Finalizados pelas Unidade” e “Percentual de unidades %” devem possibilitar a ordenação do usuário por ordem crescente e decrescente quando numérico e ordem alfabética de a → z e a ← z. 

Por default a listagem como um todo deverá vir ordenada pelo ano mais atual.
