### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Exclusão

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#188]
Prezados,
Ao realizar uma exclusão, a aplicação apresenta a tela de erro conforme apresentado em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7687478/f28b31b2-fd73-11e4-8878-b4abc364f2ce.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7687447/caf2b21a-fd73-11e4-80bc-242307c8b115.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
