### ISSUE TITLE
SICEL_CDU_009_Manter Modelo de Documentos - Quantidade de caracteres

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#189]
Ambos os campos estão com suporte de 300 caracteres.

![1](https://cloud.githubusercontent.com/assets/6584772/7704484/0b5d9332-fe15-11e4-8647-961e81a9b4bb.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
