### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Tamanho Mínimo e Máximo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#19]
Prezados
Foi verificado a não exigência na documentação de que no campo "Tamanho Mínimo" fosse exigido um valor inferior ao campo "Tamanho Máximo", isso se confirma?
Segue imagem da ação realizada.

![tminimotmaximo](https://cloud.githubusercontent.com/assets/6584772/3673073/8a87b6fe-1268-11e4-9a39-836e835e2cd6.PNG)

**Comment by jadossantos** [comment]
Monica atualizou a documentacao com o FA 6 e fizemos a implementacao da sugestao.

**Comment by monicaleite** [comment]
A documentação atualizada já está disponível no git.

**Comment by jmatil** [comment]
Foi verificado a atualização no sistema e a disponibilização da documentação atualizada no GIT
