### ISSUE TITLE
SICEL_CDU_009_Manter Modelo de Documentos - Hints

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#190]
Verificar a inclusão dos itens destacados na imagem e exigidos na documentação.

![1](https://cloud.githubusercontent.com/assets/6584772/7732600/76b7a3a8-feff-11e4-90af-3d6ade84ddb3.png)

**Comment by jadossantos** [comment]
Resolvido. 
Favor limpar o cache.

**Comment by jmatil** [comment]
Confirmado a correção

![1](https://cloud.githubusercontent.com/assets/6584772/7747543/cfa92f8a-ff91-11e4-9f94-124fddfd6021.png)
