### ISSUE TITLE
SICEL_CDU_009_Manter Modelo de Documentos - ÍCONE ATIVADO / DESATIVADO

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#191]
Por que esta lupa aparece desativada?

![1](https://cloud.githubusercontent.com/assets/6584772/7749749/1c0851d0-ffa6-11e4-9347-8d8a21565779.png)

**Comment by jadossantos** [comment]
O ícone passou a ficar ativo em todas as situações e a mensagem de validação de página não digitada foi removida.

**Comment by jmatil** [comment]
Confirmada a atualização
