### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Elaboração do Roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#192]
Verificar a ação do sistema ao acionar o botão "Salvar". Segue imagem do comportamento do sistema

![1](https://cloud.githubusercontent.com/assets/6584772/7758222/75615546-ffde-11e4-9d7a-ff2399e18a5d.png)

Acionamento do botão "SALVAR"

![2](https://cloud.githubusercontent.com/assets/6584772/7758254/b2fd7c9a-ffde-11e4-8413-e0e43bd7958d.png)

OBS.: Impacto no CDU 006 (Fluxo de exceção 4)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Confirmado a correção
