### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Campo tamanho máximo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#193]
Verificar a aceitação de caracteres alfanuméricos para o campo destacado na imagem

![1](https://cloud.githubusercontent.com/assets/6584772/7760598/755da6b6-fff3-11e4-9456-b31194214044.png)

**Comment by rsantanam** [comment]
Resolvido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
