### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Alteração das informações

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#194]
O sistema está emitindo a mensagem de alteração realizada com sucesso, mas os dados alterados só estão sendo possíveis de serem visualizados após atualizarmos a página ou entrarmos em outro menu.

**Comment by rsantanam** [comment]
Resolvido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
