### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Editar Tipo de Resposta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#195]
Verificar a seguinte situação:
1) Foi escolhido um tipo de resposta da qual havia vínculo com outro cadastro no sistema;
2) Foi acionado a opção para edição.
3) Trocado a classe TEXTO para ESCOLHA.
4) Informado os dados necessários e acionado a opção SALVAR.
"O sistema emitiu a mensagem abaixo"

ITEM EDITADO.
![1](https://cloud.githubusercontent.com/assets/6584772/7777872/e6c3c7aa-009c-11e5-9ae7-dd2ac7973bcf.png)

RESPOSTA DO SISTEMA
![2](https://cloud.githubusercontent.com/assets/6584772/7777875/ef9ad77e-009c-11e5-96e3-fc3ec5fea2cf.png)

**Comment by rsantanam** [comment]
Jaílson,

Poderia detalhar melhor o problema não consigo simular nem local nem em desenvolvimento ?

**Comment by jmatil** [comment]
O tipo de resposta marcada na figura acima está vinculada a algum outro registro. O que não permite a exclusão, pois está vinculada. (Ação correta). Mas ao editar este tipo de resposta trocando a classe "Texto" pela classe "Escolha" deste mesmo registro e acionando a opção "SALVAR". O sistema emite esse erro anexado na imagem.

**Comment by rsantanam** [comment]
Poderia tentar repetir a ação?

**Comment by rsantanam** [comment]
Não foi possível simular o defeito.

**Comment by jmatil** [comment]
Foi verificado que a ação não persiste
