### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Imprimir Rascunho

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#196]
Prezados,

Ao realizar o FA_5 Imprimir Rascunho e acionando o a opção [RASCUNHO] a aplicação é direcionada para a tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/7777890/27a45a64-009d-11e5-94c3-fdaad937e905.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7777894/30a21692-009d-11e5-8d90-1905b82320ed.png)

**Comment by rsantanam** [comment]
Resolvido, favor verificar.

**Comment by kleiberfaria** [comment]
Item verificado !
