### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Quantidade de Escolhas Cadastradas

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#197]
Foi adicionado uma quantidade de 300 escolhas para o tipo de resposta e o sistema disponibilizou a tela com o comportamento abaixo:

![1](https://cloud.githubusercontent.com/assets/6584772/7778546/f670a032-00a2-11e5-845c-752d927553d2.png)

![2](https://cloud.githubusercontent.com/assets/6584772/7778552/fc4b1fb4-00a2-11e5-961f-6f485e558d9d.png)

**Comment by rsantanam** [comment]
Foi adicionado 300 itens para o tipo de resposta escolha ou algum campo em específico?

**Comment by jmatil** [comment]
Segue exemplo
![1](https://cloud.githubusercontent.com/assets/6584772/7779868/d274cf9e-00ae-11e5-842a-f79daef536fc.png)

**Comment by jmatil** [comment]
Com 200 registros
![1](https://cloud.githubusercontent.com/assets/6584772/7780092/241e66e6-00b1-11e5-8713-4f4aa3c16e38.png)

**Comment by jadossantos** [comment]
Aguardando a resposta do email "[TSE - SICEL] Issue 197 do github".

**Comment by jadossantos** [comment]
Segundo a  resposta do email acima o problema não voltou a acontecer.

**Comment by jmatil** [comment]
Confirmado
