### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Incluir um Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#198]
Prezados,
Ao incluir [ Incluir Tipo de Procedimento ] a aplicação exibe a tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7780513/8060e6fe-00b6-11e5-9d08-a665cb48c2e4.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7780520/928e52c6-00b6-11e5-87be-454cd6ce5654.png)

**Comment by jadossantos** [comment]
Não consegui simular o problema. Pelo log registrado na issue é bem provável que se trate de um erro de conexão fechada.

**Comment by kleiberfaria** [comment]
Estarei fechando essa isssue. Realizei o novo teste na pagina  [ Incluir Tipo de Procedimento ] e não ocorreu o problema relatado.
