### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Imprimir Procedimento 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#199]
Prezados,
Conforme [RN045], o FA7_Imprimir Procedimento não está sendo ativado o campo [PROCEDIMENTO] 

![2](https://cloud.githubusercontent.com/assets/9218077/7798393/accfd3ec-02cf-11e5-86be-da37d50d3ad4.png)

![1](https://cloud.githubusercontent.com/assets/9218077/7798314/cf96d30e-02ce-11e5-9ebd-9ecb573328a8.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
