### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Verificação de Duplicidade 

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#2]
Não ficou claro se na verificação de duplicidade Unidades diferentes podem cadastrar Tipos de Resposta com mesma Classe e Código. Por enquanto a implementação segue usando este conceito, isto está correto ?
![p1](https://cloud.githubusercontent.com/assets/7429018/3512744/a885b744-06bc-11e4-9402-05754b8bdcf0.png)

**Comment by monicaleite** [comment]
O sistema deve validar a duplicidade para código e classe. Quando o usuário selecionar no campo classe a opção "Escolha" o sistema também deverá validar a duplicidade dos campos "Texto" e "Valor", pois esse campos somente aparecem quando selecionado a opção "Escolha".

**Comment by jadossantos** [comment]
Mônica,
Ficamos com dúvida se diferentes Unidades poderão cadastrar <b>Tipos de Respostas</b> com mesma composição de Código e Classe. Por exemplo:
A unidade <b>TSE</b> tem o <b>Tipo de Resposta</b> com Código <b>123</b> e Classe <b>Data</b> e em um determinado momento a unidade <b>TRE-BA</b> tentará cadastrar o <b>Tipo de Resposta</b> com Código <b>123</b> e Classe <b>Data</b>.
A unidade TRE-BA irá conseguir? 
Caso a resposta for <b>afirmativa</b> essa regra não está clara na documentação, mas implementamos desta maneira.
Caso a resposta for <b>negativa</b> qual mensagem será apresentada?
Nos dois casos teremos que atualizar a documentação.

**Comment by monicaleite** [comment]
O entendimento está correto, confirmado com o líder de projeto do TSE Elder. Os documentos já foram atualizados no git.
