### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] RAP001 – Resultado para a Consulta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#20]
Prezados
Foi realizado o cadastro de três itens na sequência 1, 2 e 3 e conforme o que está descrito na regra de apresentação 001 o sistema deverá apresentar após realização da pesquisa uma lista ordenada do registro mais recente para o mais antigo, ou seja, 3, 2 e 1. Esta ação está corretamente interpretada mim? Pois a única forma de realizar esta ordenação seria acionando o título da tabela que permite alterar essa ordem. Seguem imagens para as devidas comparações: 

![resultado1](https://cloud.githubusercontent.com/assets/6584772/3706705/2134553e-142c-11e4-8767-4cbcc66f40a9.png)

![resultado2](https://cloud.githubusercontent.com/assets/6584772/3706724/4918e84e-142c-11e4-9337-af896a844844.PNG)

**Comment by jadossantos** [comment]
Monica,

Essa regra esta correta? Caso afirmativo a ordenação seria feita pela sequence do registro.

**Comment by monicaleite** [comment]
O registro inicialmente tem a ordenação conforme a regra RAP001 do mais recente para o mais antigo e caso o usuário deseje pode reordenar.

**Comment by jadossantos** [comment]
Monica,

A coluna que identifica a ordem de cadastro não é exibida na grid. Isso não deixaria o usuário confuso?

**Comment by monicaleite** [comment]
Foi solicitação do usuário, pois no momento em que for montado o roteiro ele pode querer reordenar, porém no momento do cadastro é interessante visualizar o que ele incluiu por último.

**Comment by jadossantos** [comment]
Jailson,

A ordenação será decrescente pela sequence e esse campo não é exibido na tela.

**Comment by jmatil** [comment]
Foi retestado verificado a implementação da ordenação.
