### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - FE3 Nenhum Registro Encontrado

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#200]
Conforme telas em anexo, a aplicação não apresenta a MSG 002 para o FE3 Nenhum Registro Encontrado.

![2](https://cloud.githubusercontent.com/assets/9218077/7800976/deff4d7e-02f3-11e5-93af-b3f8cabe93e4.png)

![1](https://cloud.githubusercontent.com/assets/9218077/7800978/e376a71c-02f3-11e5-94ed-0bdc8842848b.png)

**Comment by jadossantos** [comment]
A <b>RAP049 – Opção “Executar” na listagem</b>
<i>Quando para a unidade eleitoral logada não existir nenhuma procedimento atribuído, o sistema deverá exibir a frase: “Nenhum procedimento atribuído para a unidade eleitoral logada” e a opção executar deverá ser desabilitada.</i>

**Comment by kleiberfaria** [comment]
Joel e quanto a mensagam para o fluxo FE3? Não estou conseguindo simular. Mensagem essa é apresentada somente para esse fluxo

![1](https://cloud.githubusercontent.com/assets/9218077/7801238/e7e7ff4a-02f7-11e5-9b79-4909474df214.png)

**Comment by jadossantos** [comment]
Mônica,

Qual comportamento deve acontecer?

**Comment by monicaleite** [comment]
Pessoal, 

São 2 coisas diferentes, uma coisa é não existir procedimentos, aí aparece essa mensagem, outra é existir procedimento e ele informar um filtro que não tem em nenhum procedimento, então aí executa o FE3.

**Comment by kleiberfaria** [comment]
Preciso que a aplicação apresente a MSG002 - [ FE3. Nenhum registro encontrado ] 

![1](https://cloud.githubusercontent.com/assets/9218077/7801536/89df82ce-02fc-11e5-9dee-d4aca18eeb39.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
