### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Campo Obrigatório

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#201]
Favor verificar se o campo "Descrição" é de preenchimento obrigatório. Há incompatibilidade entres as informações da documentação.

**Comment by monicaleite** [comment]
Os 2 campos são obrigatórios, vou corrigir o item na descrição dos campos.

**Comment by jmatil** [comment]
Favor verificar a obrigatoriedade de preenchimento destes campos conforme solicitado na documentação, pois ao acionar a opção "Elaborar" sem preencher os campos, o sistema direciona o ator a outra tela sem que estes itens sejam validados.

![1](https://cloud.githubusercontent.com/assets/6584772/7801584/9cad7ebe-02fd-11e5-81ed-e7afc631f92c.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
