### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - FA8 Reabrir Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#202]
Conforme tela em anexo, a funcionalidade [Reabrir Procedimento] não esta reabrindo o procedimento conforme [RAP054]

![1](https://cloud.githubusercontent.com/assets/9218077/7802507/71e901a2-030d-11e5-83f8-f9ec23894dc2.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Joel,
Acabei de fazer o teste e ainda não foi possivel a funcionalidade está "Ativa"

![1](https://cloud.githubusercontent.com/assets/9218077/7803016/0e54a002-031b-11e5-9626-5e00bc0f9c3e.png)

**Comment by kleiberfaria** [comment]
Item verificado !
