### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Registro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#203]
O sistema não está validando a duplicidade de cadastro ao acionar o botão "Elaborar"

![1](https://cloud.githubusercontent.com/assets/6584772/7803373/1565b990-0324-11e5-93c0-0c9a4b300083.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
