### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Mensagem de Exclusão

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#204]
O sistema não está emitindo a mensagem de exclusão MSG007 - Exclusão realizada com sucesso!

![1](https://cloud.githubusercontent.com/assets/6584772/7803482/4b2257ac-0327-11e5-824e-8fb4f5429011.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
