### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Botão

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#205]
Há necessidade de inclusão deste botão na aplicação ou ele só aparecerá caso seja utilizado outro perfil?
Obs.: A mesma ação ocorre para inclusão de quesitos ou categoria

![1](https://cloud.githubusercontent.com/assets/6584772/7810902/7df4c2dc-037c-11e5-90b4-a72bea84dee8.png)

**Comment by monicaleite** [comment]
Jailson,

Esse botão só irá aparecer quando você fora realizar uma inclusão e informar um registro que já existe então não aparecerá o botão salvar, conforme RAP030.

**Comment by jmatil** [comment]
Compreendido.
