### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Alterar Roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#207]
Verificar a ação do sistema, pois só foi alterado o campo descrição de um roteiro que já está com a estrutura completa e foi emitido a mensagem destacada na imagem.

![1](https://cloud.githubusercontent.com/assets/6584772/7812969/2fed7d3e-038d-11e5-97a8-317b374ab1dc.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
