### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Roteiro Elaborado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#208]
Um roteiro que foi elaborado não está sendo apresentado para a realização de cópia da estrutura

![2](https://cloud.githubusercontent.com/assets/6584772/7813796/441f5dca-0394-11e5-8e19-b5352d65ad1b.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
