### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - FA_5 Seleção de executores

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#209]
Prezados,

Ao Realizar o fluxo favor verificar o comportamento da tela conforme imagem em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7818693/938f715a-03b3-11e5-84d1-2330b098bf86.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
