### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Peso - Classe Escolha

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#21]
Prezados
Na tabela de Interface do fluxo de eventos descreve que o campo peso máximo deverá aceitar somente valores inferior a 11, mas não há especificação na regra de negócio que indique esta ação, fluxo de exceção que destaque este item e nem mensagem relacionada. Este comportamento deverá ser aceito? Seguem imagens para as devidas comparações: 

![doc](https://cloud.githubusercontent.com/assets/6584772/3706948/ef6ea0d8-142e-11e4-8121-b297715c1b5a.PNG)

![peso](https://cloud.githubusercontent.com/assets/6584772/3706960/0ecde876-142f-11e4-9f6a-a8e1f74ea37f.PNG)

![msgs](https://cloud.githubusercontent.com/assets/6584772/3706961/179a5c28-142f-11e4-99f5-6e2f596966ec.PNG)

**Comment by monicaleite** [comment]
Vou retirar essa definição.

**Comment by jadossantos** [comment]
Monica,

Então o peso não terá mas um valor máximo?

**Comment by monicaleite** [comment]
Não. Não existe uma validação nem regra que apoie isso, foi retirado.

**Comment by jadossantos** [comment]
Na verdade o tamanho máximo será 99 já que o tamanho do campo é igual a 2. Ok?

**Comment by monicaleite** [comment]
certo.

**Comment by jadossantos** [comment]
Com essa mudança teremos que mudar também o Modelo Físico. Teremos que submeter novamente a SEAD/SEBD?

**Comment by jadossantos** [comment]
Implementação feita.

**Comment by jmatil** [comment]
Foi verificado a atualização da documentação e a implementação no sistema.
