### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Incluir um Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#211]
Prezados,

Conforme tela em anexo, os procedimentos cadastrados pela a equipe de teste estão sendo excluidos pela própia aplicação. Isso pode gerar um grande impacto na execução de scripts de teste pois ao mesmo tempo que se realiza a inclusão também se faz a exclusão pelo o script. 

![1](https://cloud.githubusercontent.com/assets/9218077/7819060/c082c886-03b5-11e5-995e-0370f59f9b85.png)

**Comment by jadossantos** [comment]
O procedimento é finalizado porque a data limite é menor do que a atual.

**Comment by kleiberfaria** [comment]
Verificado conforme informação por dessa issue e também por telefone.
