### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Editar Resposta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#212]
Verificar o comportamento do sistema, pois foi selecionado um tipo de resposta com a classe "Texto" e foi trocado para a classe "Escolha". Os campos foram preenchidos e acionado a opção "Salvar". O sistema emitiu a codificação relatada na imagem:

![1](https://cloud.githubusercontent.com/assets/6584772/7826628/471bdd6e-03f3-11e5-9c01-c0706355dce7.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
