### ISSUE TITLE
SICEL_CDU_008_Manter Procedimento - Excluir Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#213]
Prezados,

Conforme tela em anexo, ao realizar uma exclusão de um procedimento a aplicação evidenciou o erro.

![1](https://cloud.githubusercontent.com/assets/9218077/7827258/954dd9bc-03fb-11e5-886e-ac2b8f63ee3d.png)

**Comment by jadossantos** [comment]
Não consegui reproduzir o erro.

**Comment by kleiberfaria** [comment]
Como a aplicação hoje pela manhã e agora realizei mais um teste e consegui a exclusão do procedimento, estarei fechando essa issue.
