### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Inserir cópia de Categoria a um roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#214]
Na tentativa de salvar todas as categorias disponíveis nos cadastros à um roteiro, o sistema se comportou conforme imagem abaixo:

![1](https://cloud.githubusercontent.com/assets/6584772/7866060/48c7a3cc-0543-11e5-9ce9-119f9fc94c53.png)

**Comment by jadossantos** [comment]
O fluxo de exceção não existe no CDU e usamos a mesma mensagem MSG003 para tratar o problema.

**Comment by jmatil** [comment]
Correção confirmada
