### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Exclusão do Roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#215]
Verificar a ação do sistema ao tentar excluir um Roteiro cadastrado. Segue imagem:

![2](https://cloud.githubusercontent.com/assets/6584772/7881871/12d782e6-05de-11e5-9cab-6af97e5aec26.png)

**Comment by jadossantos** [comment]
O problema no ambiente de homologação foi por causa das triggers.
