### ISSUE TITLE
CDU_SICEL_006_Manter Tipo Procedimento - Exclusão

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#216]
Comportamento do sistema na exclusão de um tipo de procedimento cadastrado com ou sem vínculo:

![2](https://cloud.githubusercontent.com/assets/6584772/7881914/8e9609a2-05de-11e5-9492-3ec23a06ce1a.png)

**Comment by jadossantos** [comment]
O problema no ambiente de homologação foi por causa das triggers.
