### ISSUE TITLE
CDU_SICEL_006_Manter Tipo Procedimento - Alteração

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#217]
O sistema não está permitindo a alteração de um registro cadastrado e sem vínculo. Segue imagem:

![2](https://cloud.githubusercontent.com/assets/6584772/7881932/dc2c0a40-05de-11e5-9761-224f24f1dabf.png)

**Comment by jadossantos** [comment]
O problema no ambiente de homologação foi por causa das triggers.
