### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Grid de consulta - Nome dos grupos

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#218]
Monica,

```
Conforme defino por lync/telefone o campo "Nome dos grupos" deverá exibir o nome do primeiro grupo da lista vinculada a categoria, correto?
```

**Comment by monicaleite** [comment]
Rogério,

Isso como uma categoria pode ter vários grupos, exibir todos na grid ficaria muito poluído e não foi definido pelo gestor outra forma, então adotaremos a exibição apenas do primeiro grupo e caso o usuário deseje mais informações ele terá que fazer o detalhamento  ou entrar na edição para visualizar todos.

**Comment by rsantanam** [comment]
Ok.
