### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Inclusão do grupo

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#219]
Monica,

Na inclusão do grupo através do campo adicionar "(+)" , deverá carregar o primeiro grupo da lista, já que poderão existir vários, correto?

**Comment by monicaleite** [comment]
Ao acionar a opção "(+)"  o sistema deverá carregar outro campo "grupo" e "quesito" em branco e no início para o usuário preencher, porém na listagem ele será incluso no final dos demais grupos da categoria em questão.

**Comment by rsantanam** [comment]
Ok.
