### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Editar Escolha

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#22]
Prezados 
Ao executar o fluxo "FA6. Editar Escolha" foi percebido que a alteração não é realizada somente ao acionar a opção "Salvar" e sim ao acionar a opção "Adicionar" e depois a opção "Salvar".
![editar1](https://cloud.githubusercontent.com/assets/6584772/3707342/eac35222-1433-11e4-9767-7d077e3f25b9.PNG)

![editar2](https://cloud.githubusercontent.com/assets/6584772/3707358/09f14d66-1434-11e4-8809-65734e125091.PNG)

**Comment by monicaleite** [comment]
Para ficar conforme o desenvolvido, irei acrescentar no passo FA6.3 que o ator aciona a opção adicionar e posteriormente salvar.

**Comment by marasb** [comment]
Mônica, a alteração também deverá ser feita no fluxo Incluir Escolha.

**Comment by monicaleite** [comment]
Feito. O git está atualizado.

**Comment by marasb** [comment]
A alteração foi realizada. Defeito corrigido.
