### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Titulo da grid de consulta

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#220]
Monica,

O titulo da grid de consulta esta com "Grupos cadastrados" não deveria ser "Categorias cadastradas" , já que o fluxo básico item 1 diz que será uma lista de categorias ?

**Comment by monicaleite** [comment]
Isso Rogério, coloca como categorias cadastradas, quando eu for no TSE, irei realizar essa correção, pois não estou conseguindo acessar remotamente. Vou deixar essa issue comigo para lembrar de realizar a correção.

**Comment by monicaleite** [comment]
O nome da grid foi alterado, conforme informado acima.

**Comment by rsantanam** [comment]
Ok.
