### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Tela de Inclusão

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#221]
Monica,

Os campos Categoria, Grupo e Quesito só poderão carregar informações ou será inserido dados novos?

No detalhamento dos campos diz que as informações possíveis serão as já cadastradas no sistema:
![image](https://cloud.githubusercontent.com/assets/6524452/8417055/5a141d12-1e80-11e5-9f10-5dd505a1ad71.png)

Então nessa tela iremos fazer o vínculo entre Categoria / Grupo / Quesito ?

**Comment by monicaleite** [comment]
Os campos poderão trazer um registro que já existe e também servirá para cadastro de novas informações, logo ele poderá carregar um dados já existente ou cadastrar um novo, lembrando da duplicidades. Essa forma ja feita no roteiro.

**Comment by rsantanam** [comment]
Quando for feito uma inclusão de um quesito, será necessário definir um tipo de resposta padrão já que a informação obrigatória para o quesito e a funcionalidade não possui campo para definição.
O tipo resposta é cadastrado por funcionalidade, nesse caso como proceder?

**Comment by monicaleite** [comment]
No caso do quesito não será feito inclusão, pois o caso de uso é para cadastro da categoria e grupo o quesito é só recuperado, pois ele é cadastrado no caso de uso Manter Quesito.

**Comment by rsantanam** [comment]
A documentação não deixa claro esse comportamento. Talvez seja necessário evidenciar esse comportamento afim de gerar dúvidas na hora dos testes.

**Comment by monicaleite** [comment]
Ok, Rogério...quando for ao TSE, irei verificar uma regra de apresentação para esse campo, informando que ele é apenas recuperado do Manter Quesitos. Vou deixar o git comigo que é para não esquecer de atualizar a documentação.

**Comment by monicaleite** [comment]
Rogério,

Eu alterei o nome do fluxo do FA10 e alterei o nome incluir para vincular, demonstrando assim que no caso do quesito é apenas recuperação da informação para vínculo.
Na PT2 melhorei a descrição e no domínio já informava que seria recuperado.

**Comment by rsantanam** [comment]
Ok, obrigado.
