### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - FE 5 Estrutura inválida

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#222]
Mônica,

Acredito que a mensagem MSG022 lançada no fluxo de exceção FE5 esteja errada:
   <b>MSG022</b>:   <i>Estrutura do roteiro inválida. Você tentou uma associação inválida entre [X e Y].</i>

Poderia verificar?

**Comment by monicaleite** [comment]
Rogério,

Vou criara a mensagem: Estrutura inválida. Você tentou uma associação inválida entre [X e Y]. Amanhã corrijo a documentação.

**Comment by monicaleite** [comment]
Rogério,

Alterada a msg22 do FE5 para msg21.

**Comment by rsantanam** [comment]
Mônica,

Acho que a MSG021 ainda continuará inadequada:
<i>"MSG021  : Estrutura do roteiro incompleta. É necessário obedecer à hierarquia de Categoria, Grupo e Quesito. Não podendo haver grupo sem quesito ou categoria sem grupo."<i/>

O ideal seria a mensagem que havia sugerido inicialmente: <i><b> "Estrutura inválida. Você tentou uma associação inválida entre [X e Y]."<b/><i/>

**Comment by monicaleite** [comment]
Rogério, 

Irei para o TSE na parte da tarde e farei a correção, pode considerar a mensagem que você criou, irei colocar a mesma na documentação.

**Comment by rsantanam** [comment]
Ok, obrigado.

**Comment by monicaleite** [comment]
O caso de uso foi corrigido, incluída a MSG035

**Comment by rsantanam** [comment]
Ok, a MSG022 foi alterada e passamos a utilizá-la assim como a funcionalidade de Roteiro.
