### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Inclusão Categoria/Grupo/Quesito

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#223]
Mônica,

Os campos permitiram autocomplete, de modo que ao ser encontrado uma Categoria/Grupo/Quesito cadastrado na base o mesmo deverá ser carregado. Quando for alterado alguma informação referente ao item carregado deverei tratar como a inclusão?

**Comment by monicaleite** [comment]
Rogério,

Está correto o entendimento, quando no campo ele começar a digitar o sistema deverá procurar na base de dados se existe algum registro conforme está sendo digitado, caso encontre ele exibe para o usuário selecionar, se não encontrar ele pega a informação digitada e realiza o cadastro como um registro novo.

**Comment by rsantanam** [comment]
Supondo que esteja digitando uma categoria, encontro com o autocomplete e seleciono esta. O sistema deverá carregar as informações. Se faço uma alteração no nome do grupo por exemplo e clico em salvar como o sistema deve se comportar?
O sistema irá fazer uma alteração na categoria  ou  irá tentar incluir essa categoria?

**Comment by monicaleite** [comment]
Rogério preciso verificar o caso de uso, tem como vc encaminhar para meu e-mail, por favor. Se poder esperar para amanhã eu verifico no TSE, se não me encaminha o documento para eu analisar aqui por favor.

**Comment by monicaleite** [comment]
Rogério,

Quando o usuário acessar uma estrutura através da listagem na opção editar, toda alteração que ele fizer será de edição.
Quando o usuário estiver fazendo inclusão "Incluir Categoria/Grupo" e recuperar um registro que existe e ele realizar uma alteração desse registro na tela de inclusão, essa ação será considerada como inclusão de um novo registro.

**Comment by rsantanam** [comment]
Ok.
