### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Filtro de pesquisa - Campo Unidade Eleitoral

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#224]
Olá Monica,

No caso de uso SICEL_CDU_004_Manter Quesito do TSE, existe um campo 'Unidade Eleitoral' nos filtros de pesquisa na lista de atributos da tela PT1, que não aparece no protótipo da tela e nem é citado no histórico de revisão do documento. Esse campo deverá ser implementado? Caso sim é necessário descrever as características do campo(obrigatoriedade, tamanho e etc).

**Comment by monicaleite** [comment]
Em anexo o documento que está no repositório.

Rogério,

A informação está descrita no caso de uso no histórico e também na tabela, qual versão é essa que vc está verificando?

O sistema guarda qual unidade está logada e desse login ele obterá quem cadastrou o registro, ta explicado na descrição do campo e tem a RN 5 na frente que fala sobre isso...não sei se entendi corretamente o que você perguntou.

[SICEL_CDU_004_Manter Quesito .docx](https://github.com/islssa/SICEL/files/479/SICEL_CDU_004_Manter.Quesito.docx)

**Comment by rsantanam** [comment]
Olá Mônica,

Abri a dúvida, pois no histórico diz  "Inclusão da informação “Unidade Eleitoral”, “Categoria” e “Grupo” na listagem da tela de consulta do quesito.". Porém na lista de atributos aparecem para filtro de pesquisa e não aparecem para quesitos cadastrados. 

Então, em Filtro de pesquisa, existirá o campo “Unidade Eleitoral”? Sendo ele fixo, carregado do usuário? Assim a pesquisa retornará somente Quesitos cadastrados para a “Unidade Eleitoral” do usuário. É isso?

Uma segunda questão. Na grid de resultado da pesquisa, deverão existir as colunas “Unidade Eleitoral”, “Categoria” e “Grupo” como mostrado na imagem do protótipo?

**Comment by monicaleite** [comment]
Rogério,

Rogério ele vai exibir de todas as unidades eleitorais ou de acordo com o filtro informado, falta acrescentar no protótipo o campo "Unidade Eleitoral", irei ajustar futuramente. Ele vai seguir a questão da hierarquia da RN05 e RN7 se não me engano, no caso a CGE poderá vê de todos então o filtro habilitará para ela visualizar dos que estão abaixo assim para os demais...
Será exibido apenas no resultado, as seguintes colunas: Unidade Eleitoral, Nome, Nota, Categoria, Grupo e data de criação. Irei atualizar o documento descrevendo os campos conforme está no protótipo.
Se precisar me liga no 3018-3026

**Comment by rsantanam** [comment]
Mônica,

Então o campo "Unidade Eleitoral" só será exibido na grid de resultado, ok?

**Comment by monicaleite** [comment]
ok, Rogério!
