### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Inclusão  - Categoria já existente

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#226]
Mônica,

Supondo que durante a inclusão já tenha informado categoria, grupo e quesito. Então na categoria em que já havia preenchido, resolvo utilizar o autocomplete e carregar uma categoria previamente cadastrada que já possui grupo e quesito, as informações que haviam anteriormente serão perdidas. Esse entendimento esta correto?

**Comment by monicaleite** [comment]
Sim, serão perdidas se ele carregar em uma estrutura que já estava pronta.

**Comment by rsantanam** [comment]
Ok.
