### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Mensagem 011

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#227]
O sistema não emitiu e permitiu a exclusão de um Quesito vinculado à um procedimento em execução:

![a](https://cloud.githubusercontent.com/assets/6584772/8650839/d63f9d50-294b-11e5-9f6a-2d823cc3745f.png)

![b](https://cloud.githubusercontent.com/assets/6584772/8651171/b63dc7dc-294d-11e5-8c64-4814a277432f.png)

![c](https://cloud.githubusercontent.com/assets/6584772/8651173/ba704f00-294d-11e5-87f6-d0565b419509.png)

![d](https://cloud.githubusercontent.com/assets/6584772/8651175/c26a0016-294d-11e5-9b20-1ff96ee9ad72.png)

![e](https://cloud.githubusercontent.com/assets/6584772/8651181/c6e37db6-294d-11e5-81a4-31b326994e6f.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
No momento o sistema não está excluindo nenhum item

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Infelizmente a impossibilidade de exclusão permanece. ( O sistema não está executando a exclusão de um quesito simples sem vínculo)

**Comment by rsantanam** [comment]
Jaílson,

Poderia verificar novamente, por favor.

**Comment by jmatil** [comment]
Correção confirmada
