### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Edição de um Quesito vinculado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#228]
Ao editar um QUESITO vinculado a um PROCEDIMENTO em EXECUÇÃO, o sistema emitiu o comportamento conforme destacado na imagem anexa e não emitiu a mensagem solicitada na documentação do CDU [MSG012]

![4](https://cloud.githubusercontent.com/assets/6584772/8698254/b8a9ea24-2ad2-11e5-9174-ebe31ee3f593.png)

**Comment by rsantanam** [comment]
Resolvido, poderia verificar?

**Comment by jmatil** [comment]
Situação permanece.
Salve o link da imagem (alterar) em um local da máquina e troque a extensão [png] por [wmv] para ver a filmagem anexa

![alterar](https://cloud.githubusercontent.com/assets/6584772/8799518/ffc17e4c-2f80-11e5-998e-27f3c08aeb99.png)

**Comment by rsantanam** [comment]
Jáilson, 
Poderia verificar a situação novamente?

**Comment by jmatil** [comment]
Favor verificar a situação, pois ainda permanece

**Comment by rsantanam** [comment]
Jaílson,

Poderia verificar o item, novamente?

**Comment by jmatil** [comment]
Se alterarmos o campo "nota" e acionar a opção "Salvar" o sistema comporta-se normalmente. Apresenta os dois registros para o Quesito, mas se eu alterar o NOME do QUESITO e acionar a opção SALVAR o sistema emite a mensagem, mas não apresenta os dois arquivos. Somente atualizarmos a página.

**Comment by rsantanam** [comment]
Jaílson, 
Testa novamente, por favor.

**Comment by monicaleite** [comment]
Retirado dos casos de uso conforme repassado pelo Cleber, não será possível essa verificação.
As mensagens MSG011 e MSG012 não serão mais utilizadas devido a forma como foi realizada o versionamento dos registros, que serão cópia quando já entrarem em execução, não cabendo assim as mensagens criadas anteriormente.

**Comment by jmatil** [comment]
Mensagem não será emitida devido ao versionamento dos registros
