### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Citação

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#229]
O caso de uso cita uma Regra de Apresentação [RAP61], mas o mesmo caso de uso não é citado na REGRA DE APRESENTAÇÃO.

![4](https://cloud.githubusercontent.com/assets/6584772/8698609/f8749cc8-2ad5-11e5-9fb5-896a6e67d5de.png)

**Comment by monicaleite** [comment]
Segunda-feira na parte da manhã irei no TSE e realizarei os ajustes. Favor verificar o máximo de questões de documentação para que eu possa ajustar tudo na segunda.

**Comment by monicaleite** [comment]
A inclusão da referencia foi realizada.

**Comment by jmatil** [comment]
Inclusão confirmada
