### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Retorno à página anterior

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#23]
Prezados
Foi simulado a alteração de um cadastro do qual foi inserido um valor no campo mínimo superior ao campo máximo. O sistema emitiu a mensagem corretamente, mas ao cancelar a operação acionando o botão "Voltar" a mensagem permaneceu conforme imagem abaixo. A mesma ação ocorre para outras execuções realizadas no ato do cadastramento ou alteração de algum cadastro.
Pergunta: Há necessidade de limpeza desta(s) mensagem(ns) ao acionar a opção de retorno (Voltar) à página anterior ou não?

![voltar](https://cloud.githubusercontent.com/assets/6584772/3720203/d39e724c-1650-11e4-8714-efc2274c9efd.png)

**Comment by monicaleite** [comment]
Não sei como está sendo o comportamento nos demais sistemas do TSE, mas ao meu ver não deverá retornar com a mensagem de erro.

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Foi verificado que a ação foi alterada após acessar a opção "Voltar"
