### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Comportamento da Ordenação

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#230]
Verificar a necessidade de Ordenação conforme requisitado pela documentação, pois no momento a ordenação só está sendo realizada através da coluna DATA DE CRIAÇÃO e não através do clicar e arrastar.

![4](https://cloud.githubusercontent.com/assets/6584772/8698777/26444044-2ad7-11e5-8485-4fa205609934.png)

**Comment by rsantanam** [comment]
Jaílson, 
O sistema não executa essa ação para grid de resultado.

Mônica,
Acredito que essa RN não seja aplicável a situação mencionada por Jaílson. Poderia verificar?

**Comment by monicaleite** [comment]
Esse comportamento é para ser aplicado, pq o componente não está permitindo??

**Comment by rsantanam** [comment]
Na grid de resultado?

**Comment by monicaleite** [comment]
Sim, nos primeiros casos de uso ele fazia a ordenação pelas "setas", nesse já seria usado o recuro que existe no roteiro, que permite ele ordenar o resultado apenas arrastando.

**Comment by monicaleite** [comment]
Jailson,

Poderia verificar na documentação se essa ordenação deve ser persistida no sistema e influenciar em outra funcionalidade? Estou com a documentação desatualizada aqui e como vc está olhando esse caso de uso, verificar por favor se existe mais alguma regra que fale sobre a ordenação.

**Comment by rsantanam** [comment]
Jaílson,

Adicionei a possibilidade de arrastar as colunas na grid de resultado. Acredito que satisfaça o requisito.

**Comment by jmatil** [comment]
Ação confirmada
