### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Visualização do Cadastro/Edição

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#231]
Ao alterar um quesito e acionar a opção "Salvar", o sistema emite a mensagem de  "Sucesso", mas o item não consta na tela o item como alterado, pois o sistema retorna à tela de pesquisa e o item não é apresentado. A ação só poderá ser visualizada caso ator acesse outro menu e refaça a pesquisa novamente do "Quesito".
Obs: A mesma ação está ocorrendo ao incluir um novo Quesito. "Impossibilidade de visualização" do item cadastrado, mas a mensagem de "SUCESSO" é emitida.

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
