### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Duplicação do Registro após alteração

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#232]
Ao editar um QUESITO que foi vinculado a uma Categoria e Grupo, o sistema está duplicando o resultado conforme imagem anexa.

ITEM CADASTRADO COM VÍNCULO À UMA CATEGORIA & GRUPO:
![4](https://cloud.githubusercontent.com/assets/6584772/8699683/a3166bb4-2add-11e5-9dcf-8f497b68bc09.png)

CONFIRMAÇÃO DA AÇÃO, MAS RESULTADO SÓ É APRESENTADO APÓS ACESSAR OUTRA FUNCIONALIDADE:
![41](https://cloud.githubusercontent.com/assets/6584772/8699703/de186c12-2add-11e5-9bcd-825771c07cd4.png)

APRESENTAÇÃO DO RESULTADO APÓS ACESSO À OUTRA FUNCIONALIDADE: (Resultado Duplicado)
![42](https://cloud.githubusercontent.com/assets/6584772/8699719/f7b35f10-2add-11e5-81b9-8bb9c1439bc1.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Ao alterar a nota (2x) de um quesito com vínculo, o sistema emite a mensagem abaixo:
![q](https://cloud.githubusercontent.com/assets/6584772/8800072/f21dcd18-2f85-11e5-83b3-505df0e34742.png)

**Comment by rsantanam** [comment]
Jailson,

Acredito que esta situação da alteração do quesito já esteja resolvida. Não consegui simulá-la, poderia verificar?

**Comment by jmatil** [comment]
Ação confirmada
