### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Realização da Pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#233]
O sistema não está apresentando resultados para a pesquisa que utilizam como parâmetros as CATEGORIAS cadastradas sem GRUPO

CATEGORIA CADASTRADA
![4](https://cloud.githubusercontent.com/assets/6584772/8700728/fcea981c-2ae3-11e5-9ac3-49455d93e338.png)

PESQUISA
![41](https://cloud.githubusercontent.com/assets/6584772/8700755/1fd804ea-2ae4-11e5-81ad-31900367964f.png)

**Comment by jmatil** [comment]
Está trazendo resultados diversos para alguns parâmetros.

![4](https://cloud.githubusercontent.com/assets/6584772/8732209/5fa33312-2bd2-11e5-9d44-ec3c65a6e519.png)

![41](https://cloud.githubusercontent.com/assets/6584772/8732256/b378e8e2-2bd2-11e5-9349-ea7537efa98d.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
