### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Exclusão de um Roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#234]
Verificar o comportamento do sistema após tentativa de exclusão de um ROTEIRO

![6](https://cloud.githubusercontent.com/assets/6584772/8704332/b2e1f34a-2af8-11e5-9812-6c1cdb6202d7.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
