### ISSUE TITLE
SICEL_CDU_006_Manter Tipo de Procedimento - Citação no parágrafo da Regra

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#235]
Verificar as citações destacadas no parágrafo e na tabela. Para este caso de uso, ele não é citado no parágrafo, mas é citado na tabela. Verificar se todos citados no parágrafos deverão estar na tabela.
![6](https://cloud.githubusercontent.com/assets/6584772/8722456/4815f32e-2b9b-11e5-835d-29e96a51140e.png)

**Comment by monicaleite** [comment]
Na segunda feira irei realizar a correção da documentação, isso não será impedimento para finalização e validação dos itens que precisam ser verificados no reteste, ok!

**Comment by monicaleite** [comment]
Alterei o nome do caso de uso Manter Categoria para Manter Categoria/Grupo, corrigindo assim a documentação.

**Comment by jmatil** [comment]
Alteração confirmada
