### ISSUE TITLE
CDU_SICEL_006_Manter Tipo Procedimento - Atualização do Sumário

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#236]
Verificar a possibilidade de atualização do Sumário da documentação. 
Ob.: Funcionalidade [FE4] não citada no SUMÁRIO

![6](https://cloud.githubusercontent.com/assets/6584772/8722577/6af9f7c2-2b9c-11e5-85a7-34f0b4c4125d.png)

**Comment by monicaleite** [comment]
Na segunda feira irei realizar a correção da documentação, isso não será impedimento para finalização e validação dos itens que precisam ser verificados no reteste, ok!

**Comment by monicaleite** [comment]
O sumário foi atualizado.

**Comment by jmatil** [comment]
Atualização confirmada
