### ISSUE TITLE
CDU_SICEL_006_Manter Tipo Procedimento - RN038

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#237]
O sistema realmente não permite a edição de um TIPO DE PROCEDIMENTO caso esteja vinculado a um ROTEIRO em execução, mas quando a mensagem pergunta: "CONFIRMAR EDIÇÃO?" e disponibiliza a opção "SIM", deixa subentendido a possibilidade de edição desse registro vinculado. Deveremos deixar essa mensagem mesmo?
Obs.: Verificar se haverá necessidade de inclusão de um fluxo de exceção para esta ação.
![6](https://cloud.githubusercontent.com/assets/6584772/8723198/29467d7c-2ba2-11e5-99d7-c9be3528186d.png)

**Comment by monicaleite** [comment]
A alteração ocorre, porém não ocorrerão nos procedimentos com esses status...essa é a regra para todos os registros eles podem ser editados ou excluídos porem nos procedimentos que estão com status finalizado ou em execução não será alterado, logo não tem fluxo de exceção, pq a ação será executada, mas não refletida nos casos mencionados acima!!

**Comment by jmatil** [comment]
Rogério
Favor verificar a situação acima, pois o sistema não está alterando um registro na situação "INSTAURADO" com o mesmo TIPO DE PROCEDIMENTO já em EXECUÇÃO.

> > > SOLICITAÇÃO DE ALTERAÇÃO DE UM TIPO DE PROCEDIMENTO - Ação confirmada sem a opção de RECUSA<<<
> > > ![6](https://cloud.githubusercontent.com/assets/6584772/8731976/0cd4f888-2bd1-11e5-8ca1-3c58bf016112.png)
> > > 
> > > ITEM COM A SITUAÇÃO "INSTAURADO", MAS NÃO MODIFICADO <<<
> > > ![61](https://cloud.githubusercontent.com/assets/6584772/8732030/4b7fadda-2bd1-11e5-8897-34abf69e85b4.png)

**Comment by rsantanam** [comment]
Cleber,

Poderia verificar esse problema?

**Comment by Cleberfri** [comment]
Mônica, como o tipo procedimento pertence a procedimento e não altera o entendimento das respostas dos quesitos, vai ser necessário versionar essa tabela também?

**Comment by monicaleite** [comment]
Cleber,
Bom dia.

Não entendi! O Jailson está falando de editar um registro que pertence a um procedimento apenas instaurado, nesse caso ele deve ser alterado.

**Comment by Cleberfri** [comment]
Resolvido, peço que teste novamente

**Comment by jmatil** [comment]
Correção Confirmada
