### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - FE3_MSG028

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#238]
Prezados,

Ao realizar o fluxo FA1. Incluir Procedimento e no na aba [Roteiro] conforme imagem acionar o botão [Inserir] a aplicação não deveria exibir a mensagem FE3. Roteiro não inserido [MSG028] ?

![1](https://cloud.githubusercontent.com/assets/9218077/8723652/a9e087f4-2ba5-11e5-8581-16ac7c13b195.png)

**Comment by rsantanam** [comment]
Kleiber,
Acredito que esse fluxo de exceção deva ser chamado no momento em que salva o procedimento, porém não vejo como poderia simular esse fluxo uma vez que só consegue avançar para a aba seguinte caso inclua um roteiro na grid.

**Comment by kleiberfaria** [comment]
Item verificado !
