### ISSUE TITLE
CDU_SICEL_006_Manter Tipo Procedimento - Roteiro Vinculado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#239]
Ao criar um Tipo de Procedimento com um ROTEIRO vinculado no campo específico conforme imagem, o sistema deverá amarrar essa informação no momento em que for criado um PROCEDIMENTO ou caso o usuário escolha outro ROTEIRO este deverá somar a aquele já vinculado?

![6](https://cloud.githubusercontent.com/assets/6584772/8730809/a36cfdde-2bc9-11e5-9955-e6065f21abdc.png)

![61](https://cloud.githubusercontent.com/assets/6584772/8730811/a7d18732-2bc9-11e5-9de2-6146d9458682.png)

**Comment by monicaleite** [comment]
Jailson,
Não entendi o questionamento, essa tela faz a associação do tipo a um roteiro.

**Comment by jmatil** [comment]
Isso. A primeira tela faz a associação ao um ROTEIRO
Na criação de um procedimento, esse ROTEIRO associado deverá vir vinculado automaticamente na hora em que for criado um PROCEDIMENTO ou se caso eu escolha outro ROTEIRO (na tela de procedimento), aquele em que eu vinculei na hora do cadastramento do TIPO DE PROCEDIMENTO deverá somar na hora que for realizada a execução?

**Comment by monicaleite** [comment]
Não entendi! Tem como me ligar? 3218-3026, tentei ligar aí chamou e ninguém atendeu.

**Comment by jmatil** [comment]
Conforme conversado a ação do sistema foi compreendida
