### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Caracteres Inválidos e Aceitos

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#24]
Prezados
1) Ao inserir um dos seguintes caracteres (,.!@#$%¨&*()) nos campos tamanho máximo ou mínimo e acionar a opção "Salvar", o sistema emitiu uma mensagem da qual não foi encontrada relatos na documentação de regra de negócio. 
2) Após execução da ação o sistema impediu o acesso de retorno à página anterior, ou seja, a opção "Voltar" ficou travada. 
OBS: O mesmo comportamento ocorreu para o campo "Peso" ao seleciona a classe "Escolha".

![caracterinvalido](https://cloud.githubusercontent.com/assets/6584772/3720225/18cdaf36-1651-11e4-91a9-4593c41aa110.png)

**Comment by jadossantos** [comment]
O problema era na validação do javascript.

**Comment by jmatil** [comment]
Verificado a correção do item citado.
