### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Alteração

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#241]
Foi acionado a opção de alteração de um QUESITO cadastrado e associado a uma Categoria/Grupo. Foi incluso informações no campo NOTA e acionado a opção SALVAR. O sistema emitir a mensagem abaixo:

![4](https://cloud.githubusercontent.com/assets/6584772/8751859/58abb5a2-2c86-11e5-9b0f-f61084ba5136.png)

![41](https://cloud.githubusercontent.com/assets/6584772/8751862/60cb3c12-2c86-11e5-8efc-c6ed74dad70b.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
