### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Questionário

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#242]
Prezados,

Ao realizar um "NOVO" Procedimento e [Executar] o mesmo, o questionário já esta vindo preenchido conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/8754302/eda32cb4-2c98-11e5-9de9-19b8e6bc274b.png)

**Comment by kleiberfaria** [comment]
Item verificado !

**Comment by kleiberfaria** [comment]
Favor verificar Rogério. Realizamos o teste nessa hora e esta ocorrendo novamente o erro na aplicação.

**Comment by rsantanam** [comment]
Kleiber,

Poderia verificar a situação novamente?

**Comment by kleiberfaria** [comment]
Estarei avaliando devido ao novo cenário de inclusão do roteiro manualmente.

**Comment by kleiberfaria** [comment]
Item verificado !
