### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Excluir Tipo de Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#243]
Prezados,

Ao realizar uma exclusão de um [Tipo de Procedimento], sem algum vínculo o sistema não esta permitindo realizar a exclusão. 

![2](https://cloud.githubusercontent.com/assets/9218077/8780900/6e53753a-2ee2-11e5-898d-f104a9205783.png)

**Comment by rsantanam** [comment]
Resolvido. Problema estava sendo ocasionado por uma trigger no banco.

**Comment by kleiberfaria** [comment]
Depois que limpou a base preciso realizar o cadastro de um novo procedimento para realizar o teste. Estarei validando assim que eu realizar o procedimento
