### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Listar Procedimento "Data"

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#245]
Prezados,
Conforme telas em anexo, o sistema esta apresentado ao Listar Procedimento a data invertida.

![2](https://cloud.githubusercontent.com/assets/9218077/8781371/f279c90c-2ee4-11e5-8e7b-2bbfb51e1f35.png)

![1](https://cloud.githubusercontent.com/assets/9218077/8781374/f751b714-2ee4-11e5-8ca0-769dfb898b6a.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
