### ISSUE TITLE
SICEL_CDU_005_Manter_Roteiro - Exclusão de Roteiro

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#246]
Mônica,

O fluxo de exclusão do roteiro (FA 3) não esta tratando a situação do registro vinculado a um Procedimento com situação <b>instaurado</b>. Hoje é possível excluí-lo.

Poderia verificar?

**Comment by monicaleite** [comment]
Rogério,

Caso o roteiro pertença a um procedimento onde ele é o único roteiro que o compõe, então não poderá, pois ficará sem roteiro o procedimento e ele é obrigatário na criação do procedimento. Diante disso será necessário criar no Manter Roteiro um fluxo de exceção em que verificará se o roteiro em questão está vinculado a um procedimento e se ele é único nesse procedimento, caso positivo o sistema não permitirá a exclusão e emitirá uma mensagem informando quais procedimentos esse roteiro único pertence e que ele precisa alterar o roteiro no procedimento para realizar a exclusão. Você pode implementar essa definição que eu irei atualizar a documentação.

Vou deixar a issue comigo, para que eu me lembre de alterar a documentação, quando for ao TSE.

Obrigada.

**Comment by monicaleite** [comment]
Inclusão do fluxo de exceção FE12 para tratar a questão da exclusão de um roteiro “único” que pertence a um procedimento instaurado no fluxo alternativo FA4 passo4.
Inclusão da RN052 no fluxo alternativo FA4 passo4.

**Comment by rsantanam** [comment]
Implementado.

Jaílson, poderia verificar?

**Comment by jmatil** [comment]
Verificado a implementação. O Título do Fluxo será este mesmo?
![5](https://cloud.githubusercontent.com/assets/6584772/8913148/a539eb66-346d-11e5-835e-28ebb3706bea.png)

Caso ator tente executar o procedimento sem este roteiro que estava vinculado, a aplicação emitirá esta mensagem: "No records found."

![51](https://cloud.githubusercontent.com/assets/6584772/8913331/d5078f28-346e-11e5-82aa-67b4577c27c7.png)

**Comment by monicaleite** [comment]
Não Jailson, Irei corrigir a documentação, lembrando que a mensagem deve está correta, pois ela que será exibida no sistema. Quando retornar no TSE, farei essa correção. O correto é O roteiro pertence a um procedimento Instaurado.

**Comment by monicaleite** [comment]
Jailson,

Alterei para FE 12. O Roteiro é único em um procedimento instaurado, favor verificar.

**Comment by jmatil** [comment]
Atualização confirmada
