### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Lista de Escolhas Cadastradas

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#248]
Foi constatado que a listagem de Escolhas não consta no registro do Tipo de Resposta. Há possibilidade de essa ação ocorrer? Pois há um procedimento em execução que consta esta listagem.

RELATÓRIO EM EXECUÇÃO
![relatorio](https://cloud.githubusercontent.com/assets/6584772/8825007/be478098-3051-11e5-94b7-e6e6f39e5964.png)

TIPO DE RESPOSTA SEM A LISTAGEM DE ESCOLHAS
![resposta escolha](https://cloud.githubusercontent.com/assets/6584772/8825017/d42c9286-3051-11e5-839b-ce0c845404d3.png)

**Comment by rsantanam** [comment]
Jaílson, não consegui simular, provavelmente foi corrigido indiretamente.

**Comment by jmatil** [comment]
confirmado
