### ISSUE TITLE
SICEL_CDU_000_Manter Categoria - Incluir Categoria

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#249]
Prezados,

Ao realizar de uma categoria a aplicação não esta permitindo a inclusão. Lembrando que é um pré-requisito para criar um Roteiro.

![1](https://cloud.githubusercontent.com/assets/9218077/8826637/5896d03e-305e-11e5-978a-2aa857fafe79.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
