### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Versão do sistema

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#25]
A versão da aplicação está sendo apresentado no meio da tela, sendo que o correto é ficar no rodapé da aplicação.

![erro_verso](https://cloud.githubusercontent.com/assets/6304414/3735034/a75d2a8c-171f-11e4-992d-4f50ba18cbef.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
