### ISSUE TITLE
SICEL_CDU_010_Manter Documento de Procedimento - Citação na REGRA

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#250]
Fazer a citação do caso de uso na regra 042

![10](https://cloud.githubusercontent.com/assets/6584772/8834849/3552286a-308d-11e5-9cd7-7dc0b577dbe3.png)

**Comment by monicaleite** [comment]
Assim que eu for no TSE, irei atualizar a documentação.

**Comment by monicaleite** [comment]
regra de negócio atualizada.

**Comment by jmatil** [comment]
Atualização confirmada
