### ISSUE TITLE
SICEL_CDU_010_Manter Documento de Procedimento - Editar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#251]
Ao acionar o botão de edição conforme tela em anexo em um procedimento em [EXECUÇÃO], de acordo com a RN38 esta apresentando a aba [DOCUMENTOS] e [RELATÓRIO] 

![3](https://cloud.githubusercontent.com/assets/9218077/8835239/93c64f96-308f-11e5-89d1-99dbd759ead3.JPG)

![1](https://cloud.githubusercontent.com/assets/9218077/8835245/99dc7022-308f-11e5-99c3-255585b02549.png)

**Comment by rsantanam** [comment]
Kleiber,

A RN048 complementa a RN38. Os campos são apresentados bloqueados para edição, é permitido somente visualizar as informações.

**Comment by kleiberfaria** [comment]
Item verificado !
