### ISSUE TITLE
SICEL_CDU_010_Manter Documento de Procedimento - Inserção de documentos

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#252]
Ao inserir documentos em um procedimento cadastrado o sistema aumenta a quantidade de unidade eleitoral para o mesmo procedimento conforme imagem anexa

DOCUMENTOS QUE FORAM INSERIDOS
![10](https://cloud.githubusercontent.com/assets/6584772/8850654/22800c46-3120-11e5-8ec6-2f6c3d5970e6.png)

UNIDADES ELEITORAIS QUE FORAM AUMENTADAS CONFORME INSERÇÃO DAS DOCUMENTAÇÕES.
![101](https://cloud.githubusercontent.com/assets/6584772/8850687/755f6e2a-3120-11e5-8d00-fa5a5c029754.png)

**Comment by rsantanam** [comment]
Jaílson,

Poderia verificar se o comportamento foi corrigido?

**Comment by jmatil** [comment]
Correção confirmada
