### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Excluir um Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#253]
Ao realizar uma exclusão de um procedimento cadastrado a sistema esta exibindo a mensagem conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/8851911/91b59f1a-3128-11e5-86eb-42ede34a5ccf.png)

**Comment by rsantanam** [comment]
Kleiber,

Poderia informar mais detalhes do erro? Tentei simular e não consegui, poderia verificar?

**Comment by kleiberfaria** [comment]
Rogério,
Tenta realizar a exclusão do primeiro procedimento conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/8874334/406c1a6c-31e6-11e5-9351-b937e8b186d0.png)

**Comment by rsantanam** [comment]
Kleiber,

Favor verificar se o comportamento ainda persiste.

**Comment by kleiberfaria** [comment]
Item verificado !
