### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Classe Texto

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#254]
Para um tipo de resposta com a classe TEXTO, o sistema deverá apresentar algum campo na hora da execução do procedimento? Qual a ligação desse campo TAMANHO MÁXIMO com a execução do procedimento. Segue imagem da resposta criada com a CLASSE TEXTO e sendo associada à um procedimento em EXECUÇÃO. Somente aparece o nome do QUESITO que foi associado à esse tipo de resposta. Essa ação está correta?

![1](https://cloud.githubusercontent.com/assets/6584772/8852331/f3bfffaa-312a-11e5-8cfd-f6c631b3893b.png)

**Comment by rsantanam** [comment]
Jaílson,

Foi corrigido o comportamento, poderia verificar?

**Comment by jmatil** [comment]
Correção confirmada
