### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Questionario não é visualizado

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#255]
Ao [Executar um procedimento] e ao realizar o preenchimento do questionário, o sistema esta exibindo a mensagem conforme tela em anexo. 

![1](https://cloud.githubusercontent.com/assets/9218077/8853111/9295031a-312f-11e5-8860-cdbf8317a1a5.png)

**Comment by rsantanam** [comment]
Kleiber, 

Poderia passar mais detalhes de como gerou o erro, tentei simular colocando um procedimento em execução e não reproduzi o erro. Poderia verificar?

**Comment by kleiberfaria** [comment]
Apenas criei o procedimento coloquei em status [Em Execução] e realizei o questionário porem ele não fica visivel.

**Comment by rsantanam** [comment]
Kleiber,

Não consegui simular o problema, porém devido as demais correções é possível que tenha sido corrigido indiretamente ou mesmo seja causado por dados cadastrados incorretamente por erro na aplicação.

**Comment by kleiberfaria** [comment]
Criei um procedimento para o status em EXECUÇÃO e o erro não foi evidenciado para um "novo" procedimento.
