### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro RN028

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#256]
O sistema não está contemplando a visualização dos cadastros conforme citado na regra
![5](https://cloud.githubusercontent.com/assets/6584772/8856639/6cb5fbf0-3142-11e5-8d69-513aa73a2f32.png)

**Comment by rsantanam** [comment]
Jaílson,

A RN32 completa o entendimento da RN28.
A issue foi resolvida, poderia verificar?

**Comment by jmatil** [comment]
Correção confirmada
