### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Arquivo PDF

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#258]
Os roteiros deste caso de uso que são requisitados para gerar o PDF estão apresentando estes caracteres destacados na imagem.

![5](https://cloud.githubusercontent.com/assets/6584772/8860548/fb310970-315a-11e5-85f0-8cd43b2671c2.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
