### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Visualização dos ROTEIROS

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#259]
Ao visualizar um roteiro com o perfil ZONA ELEITORAL e acionar a opção VOLTAR, o sistema está ocultando os registros cadastrados. Eles retornam a ser visualizados após acessarmos outras funcionalidades.

REGISTROS CADASTRADOS NO PERFIL ZONA
![a](https://cloud.githubusercontent.com/assets/6584772/8874510/05c0eee0-31e8-11e5-9c9d-bf3d92d3f720.png)

REGISTRO VISUALIZADO
![b](https://cloud.githubusercontent.com/assets/6584772/8874517/16aa1c72-31e8-11e5-816a-50f08ddb154a.png)

AO ACIONADO A OPÇÃO VOLTAR O SISTEMA NÃO APRESENTA OS REGISTROS CADASTRADOS
![c](https://cloud.githubusercontent.com/assets/6584772/8874527/2f98c29c-31e8-11e5-8e91-be94d1e27e7f.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
