### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Tamanho da coluna descrição.

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#26]
Foi inserido um registro com a quantidade máxima de caracteres no campo descrição.
Ao realizar a consulta desse registro foi observado que o sistema não está inserido quebra de linha na coluna descrição, ou seja, o sistema está deixando o texto todo na mesma linha, sem quebrar linha e sem limitar o tamanho da coluna.

![erro2_tamanho da coluna descrio](https://cloud.githubusercontent.com/assets/6304414/3735166/1fa60756-1721-11e4-9145-f30906922d52.png)

**Comment by jadossantos** [comment]
O css foi ajustado.

**Comment by marasb** [comment]
Defeito corrigido.
