### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Botão SIM

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#261]
Verificar os caracteres disponibilizados juntamente com o botão "SIM"

![5](https://cloud.githubusercontent.com/assets/6584772/8875513/1b473e60-31f0-11e5-84f6-1c942e35a7bd.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Correção confirmada
