### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Seleção de executores

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#262]
Rogério,
Ao editar um [Procedimento Cadastrado] >> na Aba [Relatório] incluímos Unidades Eleitorais na aba [Unidade Eleitoral] e o sistema esta com grande lentidão por conta da carga gerada de Unidades Eleitorais.
![2](https://cloud.githubusercontent.com/assets/9218077/8876161/491378be-31f4-11e5-92ed-b9fb24218c70.png)

![1](https://cloud.githubusercontent.com/assets/9218077/8876059/a8c6c690-31f3-11e5-863f-1ca796b072e0.png)

**Comment by rsantanam** [comment]
Kleiber, acredito que a issue deveria ser classificada como melhoria. Finalizando a correção dos erros poderíamos encontrar uma forma para melhorar o desempenho das consultas mais lentas.

**Comment by kleiberfaria** [comment]
Rogério,
Estarei então fechando essa issue para posteriormente como informado verificar a melhoria quanto ao desempenho verificado pelo o teste explorado.
