### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Alterar prazo para todas as unidades 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#263]
Ao acionar o campo [Novo prazo para todas as unidades], e incluir uma nova [*Data limite] o sistema fica processando a informação não executando a opção [Salvar] conforme tela em anexo. 

![1](https://cloud.githubusercontent.com/assets/9218077/8940649/656753c8-3541-11e5-98d0-048f07be3336.png)

**Comment by Cleberfri** [comment]
O erro ocorre quando é inserido uma nova unidade no procedimento e antes de salvar é acionado o botão de alterar prazo limite. Como os registros novos estão em memoria ele da um erro e não finaliza a operação.

Queria saber se é possivel realizar a inibição do botão alterar data para todos unidade ao ser inserido uma nova unidade e abilitar somente quando eu salvar o procedimento?

**Comment by monicaleite** [comment]
Cleber, 

Não fui eu quem especificou esse caso de uso, mas essas informações foram definidas ha muito tempo e não temos contato com o Gestor (greve) no momento para saber se isso pode ser alterado, logo peço que fique da forma foi descrito no caso de uso.

**Comment by Cleberfri** [comment]
Resolvido e as alterações só serão persitidas no banco após o usuário salvar o procedimento completo conforme está no caso de uso. Peço que seja testado novamente.

**Comment by kleiberfaria** [comment]
Item verificado! Correção realizada.
