### ISSUE TITLE
SICEL_CDU_009_Manter Modelo de Documentos - Mensagem de exceção

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#264]
O sistema não está emitindo a mensagem de exceção ao acionar a opção de alteração de um registro, excluir a documentação e acionar a opção "SALVAR".

![x](https://cloud.githubusercontent.com/assets/6584772/8940971/47423794-3543-11e5-9146-4accb0829901.png)

**Comment by Cleberfri** [comment]
Resolvido, peço que teste novamente

**Comment by jmatil** [comment]
Correção confirmada
