### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Documentos para [Unidade Eleitoral] não visível 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#265]
Prezados,

Ao realizar a inclusão de um documento para [Unidade Eleitoral] só esta sendo visível esse documento somente em uma [Unidade Eleitoral] e não nas demais conforme tela em anexo.

![2](https://cloud.githubusercontent.com/assets/9218077/8960452/623fc20c-35e6-11e5-8560-4a6de2835915.png)

![3](https://cloud.githubusercontent.com/assets/9218077/8960454/67a78d4c-35e6-11e5-8610-57944622b5d5.png)

**Comment by Cleberfri** [comment]
Resolvido, peço para que teste novamente

**Comment by kleiberfaria** [comment]
Item verificado !
