### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Inclusão - Sem preenchimento

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#266]
Mônica,

Como o sistema deve se comportar caso não seja preenchido nenhum campo durante a inclusão ? Não identifiquei um fluxo, poderia ajudar?

**Comment by monicaleite** [comment]
se ele tentar salvar sem preencher nenhum campo, entra a exceção para campo obrigatório.

**Comment by rsantanam** [comment]
Ok.
