### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Excluir um Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#267]
Ao realizar a exclusão do procedimento a aplicação exibe a tela de erro conforme imagem em anexo:
Primeiramente foi realizada a exclusão do [Roteiro] em seguida realizei a exclusão de um [Procedimento]

![exclusao de um procedimento cleber](https://cloud.githubusercontent.com/assets/9218077/9016155/1a13f082-37a5-11e5-8114-2c126c15a42d.png)

**Comment by Cleberfri** [comment]
Verificado, peço que teste novamente.

**Comment by kleiberfaria** [comment]
Item verificado !
