### ISSUE TITLE
SICEL_CDU_002_Manter_Categoria_Grupo - Inclusão do grupo - autocomplete

### ISSUE THREAD

**Issue by rsantanam** [islssa/SICEL#268]
Monica,

Me surgiu uma dúvida sobre a vinculação do grupo na Categoria/Grupo durante a reutilização a informação pelo autocomplete. O grupo não existe sozinho ele deve ter obrigatoriamente uma categoria associada de forma que posso ter a seguinte situação (observe a associação do Grupo 1):
![image](https://cloud.githubusercontent.com/assets/6524452/9097530/8a143dd0-3b9a-11e5-9c67-9d48c9c61e6f.png)

Perceba que temos dois grupos com mesmo nome associados a categorias diferentes.
Ao tentar reutilizar as informações de grupo cadastradas nos deparamos com a seguinte situação:
![image](https://cloud.githubusercontent.com/assets/6524452/9097580/cb5fdc90-3b9a-11e5-83cf-92c9cd2ef030.png)

Dois grupos distintos já que cada um esta associado a categorias diferentes, porém com nomes iguais.

Poderia ajudar com o problema?

**Comment by rsantanam** [comment]
Mônica,

Fiz uma alteração para visualizar uma diferenciação entre grupos de mesmo nome como segue as imagens.
1 - Na tela de consulta temos para "Grupo 1" categorias distintas:
![image](https://cloud.githubusercontent.com/assets/6524452/9144466/7b930c2a-3d23-11e5-89fa-f67470ea443b.png)

2 - Ao utilizar o autocomplete de grupo:
![image](https://cloud.githubusercontent.com/assets/6524452/9144476/98cb8196-3d23-11e5-92aa-0ff822d9ca8a.png)

3 - Ao selecionar o comportamento segue ao que já existe na documentação:
![image](https://cloud.githubusercontent.com/assets/6524452/9144490/ba9068aa-3d23-11e5-845c-38f4a312cd79.png)

Essa alteração esta disponível, por favor avalie, acredito que resolve o problema de diferenciação do grupo.

**Comment by monicaleite** [comment]
Acredito que isso resolve Rogério.
