### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Execução

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#269]
Ao realizar o preenchimento do questionário para tornar o procedimento em "Execução" o mesmo ainda continua em no status "Instaurado" 

![1](https://cloud.githubusercontent.com/assets/9218077/9112116/0c83b074-3c23-11e5-9738-7b307dad9a20.png)

**Comment by rsantanam** [comment]
Resolvido. Poderia verificar?

**Comment by kleiberfaria** [comment]
Item verificado !
