### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - RN005 e RN007

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#27]
Como faremos para validar as regras RN005 (Perfil X Funcionalidade) e RN007 (Visualização das informações cadastradas), pois para testar essas regras precisamos de autenticação dos usuários pelo ODIN?
Essas regras serão implementadas depois, quando existir a integração com o ODIN?

**Comment by monicaleite** [comment]
É necessário a integração com o ODIN, somente com a implementação da integração será possível a validação.

**Comment by jadossantos** [comment]
Essa integração será realizada em outra iteração.

**Comment by marasb** [comment]
Conforme  orientado, essas regras não serão validadas agora, pois ainda não existe a integração com o ODIN.
