### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Apresentação de Registro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#270]
Verificar o comportamento do sistema ao utilizar a opção de autocomplete no campo ROTEIRO, pois o sistema está puxando registros de roteiros duplicados.
Passos: 
1. Acionar a opção para copiar uma CATEGORIA;
2. Digitar no campo ROTEIRO para a realização do autocomplete;
3. Verificar que apenas o "Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais" está sendo duplicado.

![5](https://cloud.githubusercontent.com/assets/6584772/9137463/21496360-3cf4-11e5-94ab-40631fe72499.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correçao confirmada
