### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Cadastro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#271]
O sistema está aceitando registros duplicados. Verificar, pois aparentemente está impactando no CDU005.
![2](https://cloud.githubusercontent.com/assets/6584772/9171784/c25c265a-3f44-11e5-9a43-c1948793e0d2.png)

Tentativa de realizar a alteração de um destes itens duplicados:
![21](https://cloud.githubusercontent.com/assets/6584772/9171895/bf463478-3f45-11e5-8552-a81dce768516.png)

**Comment by rsantanam** [comment]
Jaílson, poderia verificar novamente?

**Comment by jmatil** [comment]
correção confirmada
