### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Exclusão de um Grupo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#272]
O sistema está emitindo a mensagem de sucesso para a ação de exclusão, mas não exclui o GRUPO. Ação impacta no CDU 5.

![2](https://cloud.githubusercontent.com/assets/6584772/9172226/8012ec26-3f48-11e5-87c6-4b4cd2c11908.png)

**Comment by rsantanam** [comment]
Jailson, poderia verificar novamente?

**Comment by jmatil** [comment]
Correção confirmada
