### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Categoria não encontrada

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#273]
O sistema está indicando (na funcionalidade MANTER ROTEIRO) que a categoria já está cadastrada no sistema, mas ao verificar na funcionalidade Categoria/Grupo não foi possível encontrar essa mesma categoria cadastrada.

![categoria1](https://cloud.githubusercontent.com/assets/6584772/9205508/06bed71c-4039-11e5-84d9-56c4e0c8be53.png)

![categoria2](https://cloud.githubusercontent.com/assets/6584772/9205515/0cc3baa6-4039-11e5-8ba4-67493b27d4c2.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
