### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Referência

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#278]
Verificar a referência destacada na PT2. Incluir Categoria/Grupo para a ação de exclusão
![23](https://cloud.githubusercontent.com/assets/6584772/9231719/0f49be70-4100-11e5-875c-499cd6bc5cc4.png)

**Comment by monicaleite** [comment]
A documentação deve ser corrigida.

**Comment by monicaleite** [comment]
Corrigido.

**Comment by jmatil** [comment]
Confirmado a atualização da Documentação
