### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - hints incorretos da escolha

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#28]
Os hints dos botões para excluir e editar escolha estão incorreto, pois estão sendo apresentados Excluir Tipo de Resposta e Editar Tipo de Resposta.
Favor corrigir para Excluir Escolha e Editar Escolha.

![erro4_erro nos hints](https://cloud.githubusercontent.com/assets/6304414/3749784/670c464a-17ef-11e4-8cda-5aaafee21277.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by marasb** [comment]
Defeito corrigido.
