### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Inclusão

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#280]
O sistema está emitindo a obrigatoriedade de inclusão do QUESITO ou direcionando o ator a tela de sistema do ODIN ao simular os seguintes passos:
1º acionar a opção para inclusão de uma nova Categoria/Grupo
2º digitar no campo CATEGORIA um nome qualquer não existente nos registros
3º informar no campo GRUPO um nome de um registro existente para aproveitamento da estrutura
4º com a estrutura informada, acionar a opção para inclusão de um novo QUESITO
5º acionar a opção para excluir os QUESITOS que foram reaproveitados do GRUPO que foi informado mantendo somente o novo QUESITO que foi digitado
6º acionar a opção para SALVAR.

![odin](https://cloud.githubusercontent.com/assets/6584772/9234239/10850a16-410e-11e5-8a0f-703fe4f0f08e.png)

![sicel](https://cloud.githubusercontent.com/assets/6584772/9234252/244a740a-410e-11e5-8033-222a1926597a.png)

![quesito](https://cloud.githubusercontent.com/assets/6584772/9234287/48266c8a-410e-11e5-8fc2-e3326e3446dd.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
correção confirmada
