### ISSUE TITLE
SICEL_CDU_002_Manter Categoria/grupo - Inclusão Categoria/Grupo

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#285]
Ao realizar uma inclusão da [categoria/grupo] e realizar os seguintes passos:
1. Preenchimento do campo: [Categoria]
2. Preenchimento do campo: [Grupo]
3. Preenchimento do autocomplete campo: [Quesito]
Os campo [Categoria] e [Grupo] fica em branco não permitindo SALVAR e quando a aplicação permite o preenchimento vai para a tela que esta em anexo nesse GIT

![1](https://cloud.githubusercontent.com/assets/9218077/9251974/5a2e438c-41ac-11e5-9594-845abcefaed2.png)

![2](https://cloud.githubusercontent.com/assets/9218077/9251979/5f83a4f8-41ac-11e5-839b-885da7f18b09.png)

**Comment by rsantanam** [comment]
Kleiber,

Tentei simular o erro e não consegui, tem algum detalhe que realizou como por exemplo, adicionou e removeu uma estrutura ?

**Comment by kleiberfaria** [comment]
Rogério,
Apenas digitei um texto nos campos e eles apagam não permitindo seu SALVAR.

**Comment by rsantanam** [comment]
Digitou apenas no campo quesito?

**Comment by rsantanam** [comment]
O quesito permite apenas o reuso dos já cadastrados, diferente de grupo e categoria que permitem a inclusão.

**Comment by kleiberfaria** [comment]
Segunda tela do log Rogerio,
![1](https://cloud.githubusercontent.com/assets/9218077/9252882/25c96874-41b1-11e5-9b69-b3c720132ff4.png)

**Comment by rsantanam** [comment]
Kleiber,

Poderia verificar?

**Comment by kleiberfaria** [comment]
Rogério,
O erro ainda persiste.

**Comment by rsantanam** [comment]
Resolvido. Poderia testar novamente ?

**Comment by kleiberfaria** [comment]
Rogério,
Pelo o script de teste o problema ainda persiste.

**Comment by rsantanam** [comment]
Informa os passos detalhadamente que o script executa, todos os detalhes são importantes, como o identificado por Jaílson ontem.

**Comment by kleiberfaria** [comment]
Rogério,
Encaminhei por email o video com a execução do script de teste para essa funcionalidade exibindo o erro.

**Comment by kleiberfaria** [comment]
Evidenciado nessa data 20/08/2015
![1](https://cloud.githubusercontent.com/assets/9218077/9385707/4bd28f28-472e-11e5-85ea-b926aa701bff.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado Joel. Realizado o teste. Funcionalidade ok !
