### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Quantidade de Caracteres

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#286]
Se utilizar-mos mais de 100 caracteres para os campos CATEGORIA ou GRUPO e acionar a opção SALVAR, o sistema direciona o usuário à tela de sistemas do ODIN

![qtd](https://cloud.githubusercontent.com/assets/6584772/9252048/cd72dab0-41ac-11e5-8a9a-e8f402e90c6f.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Precisamos de atualização na documentação para limitar ou não a quantidade de caracteres para estes itens. Ou deverá ficar com quantidade ilimitada?

**Comment by monicaleite** [comment]
na documentação não está definido o tamanho?

**Comment by jmatil** [comment]
Infelizmente não encontramos
![qtdcaracteres](https://cloud.githubusercontent.com/assets/6584772/9274528/ff55e87c-426c-11e5-9a08-91c1494840c0.PNG)

**Comment by monicaleite** [comment]
vamos deixar então livre, na versão anterior pegando no show log do tortoise tem tamanho definido?

**Comment by rsantanam** [comment]
Monica,

Não podemos deixar com tamanho livre, porque iria ocasionar uma violação de banco ao persistir as informações. Expliquei a Jaílson que como não esta definido o tamanho seguiremos o que já havia sido definido na funcionalidade de Categoria:
Categoria: tamanho máximo 100
Grupo: tamanho máximo 100
Quesito: tamanho máximo 300

**Comment by jmatil** [comment]
Verificando algumas documentações antigas encontrei valores de 100 caracteres para os campos: CATEGORIA e GRUPO
![categoria](https://cloud.githubusercontent.com/assets/6584772/9304388/12e09b00-44be-11e5-810e-6b3183f3a80f.PNG)

![grupo](https://cloud.githubusercontent.com/assets/6584772/9304391/17c22404-44be-11e5-9e07-fcecf0b9ab64.png)

**Comment by monicaleite** [comment]
Alterado para 100.

**Comment by jmatil** [comment]
Confirmado a atualização da Documentação
