### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Quesito com quantidade máxima de caracteres

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#287]
Verificar como fica a formatação da página caso utilize um QUESITO cadastrado com a quantidade máxima de caracteres permitido.
![quesitoqtd](https://cloud.githubusercontent.com/assets/6584772/9252294/000fd4fe-41ae-11e5-8ccd-2aecb2129a1c.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Confirmado
