### ISSUE TITLE
SICEL_CDU_002_Manter Categoria/grupo - Detalhar Categoria

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#288]
Ao clicar em um categoria para o detalhamento, a aplicação vai para o ODIN

![1](https://cloud.githubusercontent.com/assets/9218077/9257928/ff630852-41ce-11e5-8bca-3f011ae2738d.png)

![2](https://cloud.githubusercontent.com/assets/9218077/9257955/1ff21e0a-41cf-11e5-9528-012b582ae835.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
