### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Referências

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#289]
As regras são chamadas na documentação do caso de uso [ 002 ], mas na documentação de regra de negócio o caso de uso não está sendo referenciado nos parágrafos
[RAP057], [RAP001], [RAP015], [RAP036], [RAP001] , [RN025], [RN024], [RAP015],[RN022], [RN014]

**Comment by monicaleite** [comment]
O documento será atualizado.

**Comment by monicaleite** [comment]
Realizada a referencia.

**Comment by jmatil** [comment]
Confirmado a atualização da Documentação
