### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Inserir um registro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#290]
Ao executar o script de teste para cadastramento de um tipo de resposta com os dados:
- Código: 001
- Classe: Texto
- Tamanho Máximo: 10
- Descrição: Descrição Classe - Texto
  Obtivemos o seguinte resultado:
  ![tiporesposta](https://cloud.githubusercontent.com/assets/6584772/9278565/0506129a-4288-11e5-844a-55cf18213b4a.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
