### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Quesito duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#291]
Ao clicar e arrastar um QUESITO sobre uma CATEGORIA o sistema duplicou a informação do QUESITO na tela.

![2](https://cloud.githubusercontent.com/assets/6584772/9279699/8ee7a8e6-428f-11e5-8aff-a94e3860e8c4.png)

![21](https://cloud.githubusercontent.com/assets/6584772/9279702/93c34834-428f-11e5-9e51-b1a970ae9e64.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
