### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Estrutura

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#292]
O sistema está perdendo a estrutura caso adicionarmos uma nova categoria a uma categoria sem grupo ou quesito.

![2](https://cloud.githubusercontent.com/assets/6584772/9280841/801f9d16-4297-11e5-9cc4-883bbd2b6e89.png)

![21](https://cloud.githubusercontent.com/assets/6584772/9280846/84a52a54-4297-11e5-8d61-c60e37333f80.png)

![22](https://cloud.githubusercontent.com/assets/6584772/9280848/88d4afd2-4297-11e5-8208-7281bdcda61a.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
