### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Questionario MSG No records found.

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#293]
Ao executar um procedimento o questionário aparece como respondido porem com a msg
[No records found]. O procedimento utilizado foi o criado de nome:
Sicel Sicel II

![1](https://cloud.githubusercontent.com/assets/9218077/9312280/2a2809d6-44f2-11e5-8248-a633929ef2d7.png)

**Comment by rsantanam** [comment]
Kleiber, o procedimento sicel sicel II esta cadastrado no sistema?

**Comment by kleiberfaria** [comment]
Foi realiza sim com o procedimento Sicel Sicel II, porem agora estou realizando com o procedimento [Correição Ordinária]

![1](https://cloud.githubusercontent.com/assets/9218077/9340892/f491ed0a-45c8-11e5-8809-65d456ef09b7.png)

**Comment by rsantanam** [comment]
Kleiber, 

Verifica novamente o item por favor?

**Comment by kleiberfaria** [comment]
Rogério,
Ainda ocorre. Verifiquei que o erro ocorre somente com o roteiro [Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais]

![1](https://cloud.githubusercontent.com/assets/9218077/9392494/7f95d9e4-4753-11e5-84b2-30de4a7f22c0.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
