### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Salvar Questinario FE1. Nenhuma Resposta Informada

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#294]
Ao Salvar um questionário não preenchido para realizar o  [FE1. Nenhuma Resposta Informada], o sistema exibe a mensagem correta porem com a formatação conforme imagem em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/9312503/5f0ec2e2-44f3-11e5-9148-ff191ae8ed41.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
