### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Inclusão de um Grupo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#295]
Na tentativa de realizar a inclusão de um Grupo através da funcionalidade MANTER ROTEIRO, o sistema não emite a mensagem de confirmação. A tela fica no modo loop. Mas ao acessar a funcionalidade CATEGORIA/GRUPO o item aparece cadastrado no sistema.

![grupo](https://cloud.githubusercontent.com/assets/6584772/9312593/f1a0e5b8-44f3-11e5-8794-53f631263c7a.png)

![grupo ii](https://cloud.githubusercontent.com/assets/6584772/9312631/3284101e-44f4-11e5-8a6d-85607057a6fd.png)

**Comment by rsantanam** [comment]
Jaílson,

Verifique novamente não consigo simular a situação.

**Comment by jmatil** [comment]
Foi constatado que esse bug não está mais ocorrendo. Não foi identificado o motivo que levou a esta ação relatada, mas fecharemos a issue. Em caso de retorno do bug iremos reabrir a issue.

**Comment by jmatil** [comment]
Rogério
A ação de inclusão do Grupo e a não apresentação da mensagem de sucesso após acionar o botão salvar retornou. Poderia verificar?

![51](https://cloud.githubusercontent.com/assets/6584772/9357048/1034b21c-465b-11e5-9a2a-2b64a71c3d36.png)

**Comment by rsantanam** [comment]
Jailson, normalmente isso acontece por algum problema de conexão que pode ser causado por n fatores. Tentei simular e não consegui. Verfique e caso volte a ocorrer devolva a issue.

**Comment by jmatil** [comment]
Compreendido. Ação não ocorreu para inclusão do Grupo
