### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Excluir Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#296]
Ao realizar a exclusão de um procedimento, o sistema exibe a mensagem de erro conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/9312663/8735c54e-44f4-11e5-9c99-7f835f8b7aab.png)

**Comment by rsantanam** [comment]
Kleiber, cadastrei alguns procedimentos e removi normalmente, tem mais algum passo que fez e não sinalizou na issue?

![image](https://cloud.githubusercontent.com/assets/6524452/9314749/46983aaa-4501-11e5-9290-c3996de8326e.png)

**Comment by kleiberfaria** [comment]
O erro não ocorreu mais com os testes realizados nessa hora. Não simulado na tentativa.
