### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Exclusão de um registro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#297]
Ao acionar a opção para realização da exclusão de uma Categoria/Grupo o sistema emite a mensagem de solicitação de confirmação. Ao acionar a opção "Sim" o sistema emite a mensagem "Já existe a informação Categoria cadastrada no sistema!". Para visualizar que o item foi excluido é necessário atualizar a página ou acessar outra funcionalidade.
![2](https://cloud.githubusercontent.com/assets/6584772/9312726/f9cf8f68-44f4-11e5-83d2-13f0fa532612.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Favor rever a situação, pois a ação persiste.

**Comment by jmatil** [comment]
Correção confirmada
