### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Salvar Questinario

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#298]
Ao criar um procedimento e executar sem preencher o dados do questionario e salvar o sistema exibe a mensagem [msg026]

![1](https://cloud.githubusercontent.com/assets/9218077/9331010/37cf5dae-4593-11e5-809d-2ff7d6b97553.png)

![1](https://cloud.githubusercontent.com/assets/9218077/9330124/815863cc-458d-11e5-8799-7fff8c55b565.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
