### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Execução de um procedimento com roteiro associado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#299]
Ao executar um procedimento, o sistema faz com que o roteiro vinculado a este procedimento executado perca a estrutura da categoria/grupo que estava associada e permaneça apenas Quesitos que não têm associações com categorias ou grupos.

![5](https://cloud.githubusercontent.com/assets/6584772/9339461/9d28f7a0-45c0-11e5-923d-d22424932b71.png)

**Comment by rsantanam** [comment]
Jaílson,

Verifica novamente, por favor.

**Comment by jmatil** [comment]
A ação permanece

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
