### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Validação da Inclusão de Escolha

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#3]
Com relação à validação da obrigatoriedade dos campos Texto e Peso, imaginamos que seria interessante [Adicionar] a escolha na lista e depois validar se a lista possui uma ou mais escolhas. 

[Definição das Regras]
![p2](https://cloud.githubusercontent.com/assets/7429018/3512828/662644e4-06bd-11e4-9393-d87ea3569067.png)

[Mensagens de Validação]
![p3](https://cloud.githubusercontent.com/assets/7429018/3512839/709876fe-06bd-11e4-90b8-3035e27c2919.png)

Este comportamento pode funcionar da maneira sugerida ? Lembrando ainda que para adicionar uma Escolha esta deve obrigatoriamente ter preenchidos os campos Texto e Peso.

**Comment by monicaleite** [comment]
Quando selecionado em classe a opção escolha os itens peso e texto são obrigatórios. Em relação a validação, vc diz, que a tela inicial já virá com o valor escolha no campo classe?! Não entendi.

**Comment by monicaleite** [comment]
Em conversa com o líder de projetos Elder, todas as sugestões foram aceitas. o documento já foi atualizado no git.
