### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Texto da FE7 não está claro

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#30]
O texto do primeiro parágrafo da FE7 não está claro, conforme abaixo:

"...Nos passos, FA5.4 e FA6.4 , caso o sistema identifique  que o campo “Peso” com valor inválido, o sistema deve executar os seguintes passos:a verifica que não o tipo de resposta está sendo utilizada (FAVOR MELHORAR O TEXTO DESSE PARÁGRAFO)
FE 7.1      O Sistema apresenta a mensagem [MSG016];" (MSG016 - Para inserir um valor negativo é necessário informar – ( sinal menos) com o número."

![erro_texto precisa ser revisado - fe7](https://cloud.githubusercontent.com/assets/6304414/4109073/8478ab8c-31e0-11e4-974e-ce7f39c9e703.png)

**Comment by marasb** [comment]
Mônica,
O joel já me explicou que essa regra será validada caso seja informado apenas o valor " - (menos)" no campo Peso.
Mas acredito que o texto do primeiro parágrafo poderia ser mais claro.

**Comment by monicaleite** [comment]
Mara,

Acredito que ocorreu um problema ao realizar o merge, pega a documentação no correcao_iteracao1, lá está correto. Assim que corrigirmos aqui eu te aviso.

**Comment by marasb** [comment]
Na documentação correção_iteracao1 não existe o defeito.
