### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Confimação de Exclusão

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#300]
Ao confirmar a exclusão de um grupo o sistema está direcionando o ator à tela de sistemas do ODIN.

![2](https://cloud.githubusercontent.com/assets/6584772/9357140/9fec697c-465b-11e5-8e89-4079f152a150.png)

**Comment by rsantanam** [comment]
Jaílson, esta excluindo uma estrutura de categoria grupo ou excluindo a categoria grupo na grid de pesquisa?

**Comment by jmatil** [comment]
Atualmente esta ação não está ocorrendo, caso volte a acontecer iremos reabrir a issue com mais detalhamento.
