### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Editar Procedimento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#301]
Ao editar um procedimento com status [Instaurados] e acessar as abas [Unidade Eleitoral] ou [Relatório] o sistema apresenta a tela de erro conforme as imagens em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/9390930/98d532d2-474a-11e5-8f42-7d4170b0e99a.png)
![2](https://cloud.githubusercontent.com/assets/9218077/9390934/9effc136-474a-11e5-901d-d82c80a507ea.png)
![3](https://cloud.githubusercontent.com/assets/9218077/9390940/a446e19c-474a-11e5-9f09-402e89601438.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
