### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Arquivos em PDF

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#302]
Verificar a quantidade de PROCEDIMENTOS apresentadas no detalhamento do ROTEIRO, com a quantidade apresentada no arquivo gerado em PDF.

![5-pdf](https://cloud.githubusercontent.com/assets/6584772/9440989/bfaa3c7a-4a49-11e5-8d52-4e6cedf04bab.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
