### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Alteração da classe Horário

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#303]
Na tentativa de realizar a alteração da classe escolha para qualquer outra classe disponível na funcionidade o sistema está emitindo a mensagem abaixo:

CAMPO A SER ALTERADO
![1](https://cloud.githubusercontent.com/assets/6584772/9474367/98cff8c2-4b36-11e5-8a7b-5b7e61a96868.png)

RESULTADO
![12](https://cloud.githubusercontent.com/assets/6584772/9474386/bb1f1f7a-4b36-11e5-9b35-6e6ce09fb02d.png)

**Comment by jmatil** [comment]
Verificar, pois a ação ainda permanece

![perfil](https://cloud.githubusercontent.com/assets/6584772/9504224/c84ac5d8-4c11-11e5-9055-69319df68323.png)

**Comment by rsantanam** [comment]
Jaílson, testa novamente por favor.

**Comment by jmatil** [comment]
Infelizmente a ação ainda permanece.
Passos:
1 - Criar um tipo de resposta com a classe "HORÁRIO";
2 - Salvar este registro:
3 - Acionar a opção para alteração somente do tipo de classe, e se for necessário, preencher os campos que se disponibilização para preenchimento obrigatório;
4 - Acionar a opção para Salvar o REGISTRO.

![1](https://cloud.githubusercontent.com/assets/6584772/9519505/9dfbd81a-4c95-11e5-946c-d85fd3a9eab0.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Foi testado a alteração da classe horário para as outras existentes, e o problema agora somente ficou registrado ao trocarmos a classe HORÁRIO para a classe ESCOLHA.

![1](https://cloud.githubusercontent.com/assets/6584772/9526182/244cd676-4cbe-11e5-9d33-72a579417504.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
