### ISSUE TITLE
SICEL_CDU_002_Manter Categoria/grupo - Incluir/Categoria Grupo 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#304]
Realizando a inclusão de uma Categoria/Grupo e preencher os campos para a inclusão e [SALVAR] o sistema é direcionado para a tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/9496327/3c46bd24-4be6-11e5-86e7-25e211099f3f.png)

![2](https://cloud.githubusercontent.com/assets/9218077/9496335/40222ca8-4be6-11e5-9a00-793e653adf4e.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado !

**Comment by kleiberfaria** [comment]
Ao alterar o quesito que já esta salvo, o sistema vai para a tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/9504074/d39ec188-4c10-11e5-8fc5-131facb6c847.png)

**Comment by kleiberfaria** [comment]
issues reaberta. Favor verificar.

**Comment by rsantanam** [comment]
Essa tela não faz alteração no quesito, tentou fazer uma outra associação com outro quesito?

**Comment by kleiberfaria** [comment]
Rogério, eu só mudo o nome DO QUESITO.

**Comment by rsantanam** [comment]
REsolvido.

**Comment by kleiberfaria** [comment]
Item verificado !
