### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Perfil

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#305]
Verificar as ações disponíveis no tipo de resposta para o perfil Zona Eleitoral. O sistema está permitindo a alteração e Exclusão de um registro cadastrado por outro perfil.

![perfil](https://cloud.githubusercontent.com/assets/6584772/9504097/ec708354-4c10-11e5-89d9-5919950b9e5c.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
