### ISSUE TITLE
SICEL_CDU_011_Relatório de Procedimento - Relatórios Disponíveis para o Procedimento/ CONSOLIDADO 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#306]
Na aba Relatório, ao selecionar [GERAR RELATÓRIO] o sistema é direcionado para a tela do odin.

![1](https://cloud.githubusercontent.com/assets/9218077/9504162/71bf2380-4c11-11e5-824d-9435460deae4.png)

![2](https://cloud.githubusercontent.com/assets/9218077/9504165/764a83a4-4c11-11e5-854a-c9c17bba5bc1.png)

**Comment by rsantanam** [comment]
Kleiber, poderia realizar todo o cadastro para tentar simular o erro? Não consegui reproduzir, porém verifiquei que no ambiente de integração esse registro gerou o erro informado, mas se possível realiza o cadastro pela aplicação utilizando tipo resposta, quesitos, categorias e etc cadastrados pela aplicação por favor.

**Comment by kleiberfaria** [comment]
Rogério,

Realizei o teste criando tipo resposta, quesitos, categorias.... Em suma tudo do zero. Ao simular o erro de fato não ocorre criando tudo do zero, porem foi identificado que o erro corre somente com o roteiro [Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais]

**Comment by rsantanam** [comment]
Esse roteiro é inserido por carga, possa ser que esteja com algum problema nos insert, por isso pedi que fizesse do zero. O roteiro que criou foi igual ao "Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais" ?

**Comment by kleiberfaria** [comment]
Sim Rogério foi com a mesma estrutura do [Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais]

**Comment by rsantanam** [comment]
Nesse caso acho que seria melhor remover essa carga, infelizmente não vou ter tempo para corrigir esses scripts devido ao grande número de demandas nos projetos.

**Comment by kleiberfaria** [comment]
Rogério,
Nesse [Roteiro - Misto - Liberado - Relatório Mensal de Atividades - Visível para outros Tribunais] ele tem esse quesito conforme imagem e ao Executar um procedimento que tenha o roteiro mencionado e responder o questionário o erro ocorre. Quanto remover, o problema é que os scripts de teste aponta exatamente esse roteiro. 

![1](https://cloud.githubusercontent.com/assets/9218077/9526227/6302d280-4cbe-11e5-9c32-bf2ee20dd37a.png)

**Comment by rsantanam** [comment]
Kleiber, se o problema não ocorre no cadastro manual o problema esta no script. O que sugere?

A minha posição seria limpar a base e não gerar a carga inicial, de modo que os cadastros fossem realizados pela aplicação.

**Comment by kleiberfaria** [comment]
Rogerio,
Agora não sei na altura da entrega da aplicação se seria viável esse cadastro pela aplicação.

**Comment by rsantanam** [comment]
Kleiber, altereri para não simulado pois não ocorre na utilização do cadastro pela aplicação.

**Comment by kleiberfaria** [comment]
Verifiquei a alteração, porem o erro ainda persiste mas agora clicando apenas na aba [RELATÓRIO]

![1](https://cloud.githubusercontent.com/assets/9218077/9664751/463d0a9c-5242-11e5-95eb-f91234bd64fb.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Joel,
Fiz o seguinte teste:
1. Exclusão do [TIPO DE PROCEDIMENTO]
2. Responder o Questionário.
3. Aba [RELATORIO] > Gerar Relatório Consolidado

![1](https://cloud.githubusercontent.com/assets/9218077/10483740/4fe4726c-7257-11e5-849b-5ff4ea91b9dd.png)

![3](https://cloud.githubusercontent.com/assets/9218077/10483751/5c22e3a6-7257-11e5-940a-b98ea2ea1f05.png)

![2](https://cloud.githubusercontent.com/assets/9218077/10483754/6199e41a-7257-11e5-8f43-4129763271e6.png)

**Comment by jadossantos** [comment]
O jenkins está com problema e o build não aconteceu. Estou verificando.

**Comment by kleiberfaria** [comment]
Joel, assim que a build ocorrer estarei realizando o teste. Obrigado !

**Comment by jadossantos** [comment]
Favor, verificar.

**Comment by kleiberfaria** [comment]
Item verificado Joel !
