### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Impressão de relatório não exigido/ TECLA ENTER

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#308]
Conforme imagem em anexo, ao colocar o curso em um campo de preenchimento e acionar o tecla enter, o sistema abre a caixa de impressão de relatório.

![1](https://cloud.githubusercontent.com/assets/9218077/9528510/2abca862-4ccb-11e5-8f70-d9af0ab7684c.png)

RESULTADO:
![1](https://cloud.githubusercontent.com/assets/9218077/9528747/a188b638-4ccc-11e5-820b-347f125ef3f9.png)

**Comment by rsantanam** [comment]
Kleiber não existe documento que trate sobre operações utilizando o teclado como atalho nas funcionalidades do TSE. Esse tratamento poderia ser realizado em um momento futuro e ser tratada como melhoria.

**Comment by kleiberfaria** [comment]
Mas sobre esse relatório que é gerado e as informações que são apresentadas nelas?

**Comment by rsantanam** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Rogério ainda persiste conforme tela em anexo.
![1](https://cloud.githubusercontent.com/assets/9218077/9551157/c72715d8-4d85-11e5-8a48-6bfe7f2b5162.png)

**Comment by rsantanam** [comment]
Ok, testa novamente.

**Comment by kleiberfaria** [comment]
Item verificado !
