### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Estrutura do Roteiro com o perfil Zona

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#309]
O sistema não está mantendo a estrutura do ROTEIRO para o perfil ZONA
Criar um ROTEIRO seguindo os seguintes passos:
1) acionando os procedimentos para inclusão do roteiro e direcionando até a página de montagem das estruturas;
2) acionando a opção para adicionar uma categoria (+);
3) digitar o nome e a descrição de uma categoria não existente na base de dados (para não execução do autocomplete);
4) Salvar esta categoria;
5) acionar a opção para adicionar um quesito (+);
6) adicionar mais de um quesito ao registro;
7) clicar e arrastar os quesitos para montagem correta da estrutura (Categoria/Quesito)
8) acionar a opção SALVAR
9) Acionar a aba ZONA para detalhamento do ROTEIRO cadastrado.
10) comparar a estrutura montada.

ESTRUTURA MONTADA
![estrutura confirmada](https://cloud.githubusercontent.com/assets/6584772/9528950/f0efe06a-4ccd-11e5-9171-4cd35233d3be.png)

VISUALIZAÇÃO DA ESTRUTURA MONTADA
![estrutura visualizada ii](https://cloud.githubusercontent.com/assets/6584772/9528960/ffb03e1a-4ccd-11e5-9ece-7dc2cf5c43cc.png)

VISUALIZAÇÃO DA ESTRUTURA MONTADA
![estrutura visualizada](https://cloud.githubusercontent.com/assets/6584772/9528970/09a207e6-4cce-11e5-852b-c1f40d4660b0.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Resultado ao tentar montar a mesma estrutura citada acima:
Uma categoria com 2 quesitos:
![corr](https://cloud.githubusercontent.com/assets/6584772/9577525/f37f107a-4fb7-11e5-987e-bbba46ae772d.png)

**Comment by rsantanam** [comment]
Resolvido, verifica por favor.

**Comment by jmatil** [comment]
Correção confirmada
