### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Verificar texto do RAP013

### ISSUE THREAD

**Issue by marasb** [islssa/SICEL#31]
O caso de uso "Manter Tipo de Resposta" está chamando a regra RAP013.
Solicito que seja verificado o texto abaixo, pois está muito confuso:
"RAP013 – Informações a serem exibidas no campo “Categoria”Valores positivos e negativos
Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter QuesitoTipo de Resposta
O sistema deverá exibir nopermitir para o campo “categoria” todas as categorias cadastradas no casoem questão a inclusão de uso Manter Categorianúmeros positivos e negativos. Para os campos negativos o sistema irá considerar o sinal – (menos) juntamente com número para que seja válido."

O título também está inconsistente, pois está referenciando o campo "Categoria".

Não existe o campo  "categoria" no caso de uso "Manter Tipo de Resposta".

![erro rap013](https://cloud.githubusercontent.com/assets/6304414/4109259/c544bcda-31e2-11e4-9699-bf50f0e964a7.png)

**Comment by monicaleite** [comment]
Mara, 

Acredito que ocorreu um problema ao realizar o merge, pega a documentação no correcao_iteracao1, lá está correto. Assim que corrigirmos aqui eu te aviso.

**Comment by marasb** [comment]
Na documentação correção_iteracao1 não existe o defeito.
