### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Classe Horário

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#310]
Foi preenchido os campos para a classe horário sem a utilização da máscara (:) e acionado a opção SALVAR. Segue mensagem

![horario](https://cloud.githubusercontent.com/assets/6584772/9584394/4d9f5284-4fe7-11e5-911d-de80cd23a689.png)

**Comment by rsantanam** [comment]
Jaílson, iremos bloquear o campo para digitação forçando a seleção através do componente.

**Comment by jmatil** [comment]
Confirmado a implementação da ação.
