### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Exclusão de um roteiro vinculado a um procedimento em execução

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#311]
Verificar a mensagem após a exclusão de um roteiro vinculado a um procedimento em execução
![hibernate](https://cloud.githubusercontent.com/assets/6584772/9584872/06c8a3ee-4fea-11e5-8cde-4301ee3a8d9c.png)

**Comment by rsantanam** [comment]
Resolvido, testa novamente.

**Comment by jmatil** [comment]
Favor avaliar, pois a situação permanece mesmo cadastrando informações não vinculadas a dados antigos.

![r5](https://cloud.githubusercontent.com/assets/6584772/9665588/b3282a88-5247-11e5-9f79-5723446cf941.png)

**Comment by rsantanam** [comment]
resolvido

**Comment by jmatil** [comment]
Ação permanece

**Comment by jadossantos** [comment]
Resolvido.
Obs.: Precisei remover a trigger <b>ADMSICEL.TG_ROCA_BU_VALIDAR_EDICAO</b>

**Comment by jmatil** [comment]
Correção Confirmada
