### ISSUE TITLE
SICEL_CDU_002_Manter Categoria/grupo - Contagem dos Registros

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#312]
Favor comparar a contagem dos registros conforme arquivos em pdf. A ação foi simulada utilizando o perfil CRE/DF

![contagens](https://cloud.githubusercontent.com/assets/6584772/9612996/29a84ec0-50bf-11e5-8038-1888171eb729.png)

**Comment by rsantanam** [comment]
Resolvido, testa por favor.

**Comment by jmatil** [comment]
Favor avaliar a situação atual

![rr](https://cloud.githubusercontent.com/assets/6584772/9664748/4454078a-5242-11e5-9bc5-8baea5514c4a.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Ação permanece

**Comment by jadossantos** [comment]
Jailson, 
O valor <b>58</b> do último exemplo vem da coluna <b>NR_CATEGORIA</b> da tabela <b>CATEGORIA</b> do banco de dados. 
Esse valor é gerado automaticamente pela aplicação.
Anteriormente, o campo era a posição da ordenação dos registros na tela de pesquisa.

Alterei para exibir <b>sempre</b> o valor <b>1</b>.

**Comment by jmatil** [comment]
Confirmado essa adaptação, mas a numeração que segue na ordem crescente deverá está explíta no arquivo PDF conforme as outras funcionalidades do sistema?
MANTER CATEGORIA/GRUPO
![issue312](https://cloud.githubusercontent.com/assets/6584772/10219868/00093324-6819-11e5-8a3e-f7094671072e.png)

Exemplo - MANTER ROTEIRO
![roteiro](https://cloud.githubusercontent.com/assets/6584772/10219844/d3ee2f38-6818-11e5-95ac-73ac3f61a3ad.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificar se a versão que foi resolvida está disponibilizada para confirmação do reteste, pois atualmente a ação do sistema persiste.
![issue312](https://cloud.githubusercontent.com/assets/6584772/10245509/7697742c-68de-11e5-939a-a1fd9dd984b6.png)

**Comment by jadossantos** [comment]
Aumentei o tamanho do campo. Favor avaliar.

**Comment by jmatil** [comment]
Correção confirmada

![correcao](https://cloud.githubusercontent.com/assets/6584772/10278628/1871ecca-6b35-11e5-87dc-3a0c1cfd804a.PNG)
