### ISSUE TITLE
SICEL_CDU_007_Manter Procedimentos - Aba Finalizados

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#313]
Mônica,
Conforme imagem em anexo, a aba finalizados não esta apresentando os procedimentos finalizados. Tem alguma RAP ou RN que descreve sobre essa aba [Finalizados]? 

![1](https://cloud.githubusercontent.com/assets/9218077/9614346/b3a3eab4-50c7-11e5-96fe-01020540b821.png)

**Comment by monicaleite** [comment]
Na verdade a dúvida é em relação ao Manter Procedimento ou Executar? Porque a aba é do Manter Procedimento correto?
É necessário fazer a leitura do caso de  uso para identificar, pois como falei foi o Enzo que fez, não sei de cabeça, teria que lê o caso de uso para verificar, mas acredito que sim, de forma quando o procedimento estiver finalizado no executar deverá ser exibido na aba "Finalizado" do procedimento.

**Comment by kleiberfaria** [comment]
Sim Mônica executar e apresentar nos procedimentos finalizados. Vou direcionar para o Rogério. Obrigado !

**Comment by monicaleite** [comment]
Kleiber,

A aba "Finalizados" que você está falando é do Manter Procedimento, correto?

**Comment by kleiberfaria** [comment]
Sim exatamente.

**Comment by rsantanam** [comment]
Resolvido, testa por favor.

**Comment by kleiberfaria** [comment]
Realizado o teste, porem ainda não esta sendo exibido os finalizados.

![1](https://cloud.githubusercontent.com/assets/9218077/9664513/c5f06ec0-5240-11e5-8c3a-d770aedb62f4.png)

**Comment by rsantanam** [comment]
Kleiber, não utilize os registros antigos, pois se houve um erro na vinculação pode comprometer a integridade dos dados, deve cadastrar registros novos para tentar simular o problema.

**Comment by kleiberfaria** [comment]
Com registro novo

![1](https://cloud.githubusercontent.com/assets/9218077/9665404/75320b6e-5246-11e5-83a9-6d4383d24e31.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by kleiberfaria** [comment]
Item verificado !
