### ISSUE TITLE
SICEL_CDU_002_Manter Categoria/grupo - Visualização do Quesito que estava vinculado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#314]
O sistema está direcionando o ator a janela de sistemas do Odin ao simular a seguinte situação:
1) Criar um QUESITO e associar uma CATEGORIA/GRUPO existente (Mesmo sendo do próprio perfil);
2) Excluir esto QUESITO recém criado;
3) Acionar o menu da CATEGORIA/GRUPO;
4) Acionar o Link da CATEGORIA/GRUPO que estava associada ao QUESITO recém excluído.

Cadastro do Quesito com Categoria/Grupo associados
![q1](https://cloud.githubusercontent.com/assets/6584772/9633957/b9fddd68-5165-11e5-8223-3bab42288671.png)

Apresentação do Registro Cadastrado
![q2](https://cloud.githubusercontent.com/assets/6584772/9633971/cdd5d7fa-5165-11e5-815e-bd1921dc2d4e.png)

Acesso a funcionalidade CATEGORIA/GRUPO para visualização do registro
![q3](https://cloud.githubusercontent.com/assets/6584772/9633979/da36a13c-5165-11e5-8574-22dbe869cea5.png)

Tela do ODIN
![resultado](https://cloud.githubusercontent.com/assets/6584772/9634000/f47c76ac-5165-11e5-8cb6-e6ff57d0fbd0.png)

**Comment by rsantanam** [comment]
Monica, 

O quesito foi vinculado a uma Categoria/Grupo e depois através da funcionalidade de Manter Quesito o quesito em questão foi removido.

Como o sistema deve se comportar nessa situação?

**Comment by monicaleite** [comment]
Não falamos que teria uma exceção para manter ao menos um dentro da categoria ou grupo antes de excluir, agora não lembro se eu coloquei o fluxo no caso de uso.

**Comment by rsantanam** [comment]
Monica isso acontece se estivermos na funcionalidade de Categoria/Grupo mas a questão é a exclusão por parte da funcionalidade Manter Quesito. Tentei encontrar alguma regra que trata-se dessa situação e talvez não tivesse sido implementada mas também não encontrei.

**Comment by monicaleite** [comment]
Rogério, 

No caso o quesito em questão não está sendo usado em um procedimento né! Porque aí seria versionado.
Se não tem nenhuma regra que trate da questão, veja qual é a solução mais fácil e rápida e caso precise ajustar o caso de uso me avise. O ideal é não remover ele do vinculo lá do categoria/grupo, a remoção deverá ser feita somente no quesito não refletindo nos vínculos e deixando de ser exibido para vínculos futuros.

**Comment by rsantanam** [comment]
Mônica, o correto seria que existisse uma validação onde seria verificado se o quesito esta vinculado a alguma estrutura criada pelo Categoria/Grupo ou pelo Elaborar Roteiro, porém isso terá impacto para implementar e também documentar. O sistema cria diversos vínculos entre quesitos, categoria, grupos, roteiros, procedimentos, versionamentos e etc. Uma alteração como essa terá impacto em todas as demais funcionalidades.

**Comment by monicaleite** [comment]
Rogério,

No caso ele removendo do manter quesito, o sistema não irá excluí dos demais locais onde está sendo usado, apenas no quesito e não seria exibido para cadastro futuro.

**Comment by rsantanam** [comment]
Exatamente, para isso teremos que verificar o impacto nas demais funcionalidades.

**Comment by monicaleite** [comment]
Rogério, 

Como não está tratando isso no caso de uso, veja qual a melhor opção e entregamos, foi homologado sem prevê isso.

**Comment by rsantanam** [comment]
Ok, então manteremos como a aplicação esta definida, sendo que existe a possibilidade da aplicação gerar um erro como encontrado por Jaílson.

**Comment by monicaleite** [comment]
Jailson,

Devido a falta de informação na documentação e tempo para implementar uma solução, será entregue conforme foi desenvolvido.

**Comment by jmatil** [comment]
Compreendido. Conforme relato a issue será.
