### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Aba Unidade Eleitoral

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#315]
Na aba Unidade Eleitoral, ao clicar na unidade cadastrada para a exibição do detalhamento da unidade, é direcionada para uma página de erro.
Passos: 
1. Menu > Procedimento 
2. Editar Procedimento
3. Aba> Unidade Eleitoral
4. Detalhar Unidade Eleitoral

![1](https://cloud.githubusercontent.com/assets/9218077/9636903/51315a3a-5174-11e5-8679-a553d243f090.png)

![2](https://cloud.githubusercontent.com/assets/9218077/9636909/58495872-5174-11e5-90ea-0941f7a00700.png)

**Comment by rsantanam** [comment]
Kleiber,

Os dois registros que estão na lista com esse problema deverá ser removido visto que não é possível o cadastro de procedimentos sem o "tipo do procedimento" que é obrigatório e que esta causando o erro. Quando puder limpo a base novamente.

**Comment by kleiberfaria** [comment]
Foi realizado o teste com um novo procedimento depois que a base foi limpa na sexta 04/09/2015 e o erro ainda persiste.
![1](https://cloud.githubusercontent.com/assets/9218077/9736029/42311336-5615-11e5-88cc-81dd59fbb49e.png)

**Comment by jadossantos** [comment]
Kleiber,

Rodei a aplicação em minha máquina e com o banco de dados do TSE, e não consegui simular o problema. 
Esse erro ainda persiste? Caso afirmativo poderia fornecer mais informações?

**Comment by kleiberfaria** [comment]
Sim Joel, persiste. O que ocorre é que quando é criado um *Tipo de Procedimento e você vincula ao um *Novo Procedimento e exclui o *Tipo de Procedimento vinculado, seguindo os passos:
1.Criar um *Tipo Procedimento
2. Vincular esse *Tipo Procedimento ao um *Novo Procedimento
3. Excluir esse *Tipo Procedimento criado
4. Aba *Instaurados > Editar o Procedimento > Aba *Unidade Eleitoral
5. Clica no link *Detalhar Unidade Eleitoral 

É quando o erro ocorre.
![exclusao](https://cloud.githubusercontent.com/assets/9218077/10194845/4196df84-6761-11e5-860f-82f7258b8719.png)

![exclusao2](https://cloud.githubusercontent.com/assets/9218077/10194852/4873fd32-6761-11e5-9637-cb1f354b67ee.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Joel,
Realizei o teste. Conforme tela em anexo, o erro ainda ocorre. Realizei o devido print de tela para ver se o log pode te auxiliar.

![bug 315](https://cloud.githubusercontent.com/assets/9218077/10368668/d181817a-6dac-11e5-825f-e0f64dfbb5b4.png)

**Comment by jadossantos** [comment]
Resolvido.
Aguardando a solução do build no jenkins.

**Comment by kleiberfaria** [comment]
Item verificado !
