### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Simulação de Campo Obrigatório após Edição

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#316]
A situação abaixo foi simulada após:
1º) Acionar a opção para edição de um Roteiro cadastrado;
2º) Limpar os dois campos (TIPO & DESCRIÇÃO)
3º) Acionar a opção SALVAR

![r1](https://cloud.githubusercontent.com/assets/6584772/9638075/d3bdc942-517a-11e5-9dd5-ceed6ed31434.png)

**Comment by rsantanam** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificar se a correção está disponível para realização do reteste, pois a ação permanece.
![r1](https://cloud.githubusercontent.com/assets/6584772/9642035/55a14640-5190-11e5-93db-50703492bf43.png)

**Comment by rsantanam** [comment]
Jaílson, testa novamente por algum problema a versão não foi publicada.

**Comment by jmatil** [comment]
Correção confirmada
