### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Edição de um roteiro vinculado a um procedimento em execução

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#317]
Verificar o comportamento do sistema ao editar um ROTEIRO vinculado a um PROCEDIMENTO em execução.
Obs: O registro criado não teve vinculo à registros antigos. Foram cadastrados dados novos.

![r5](https://cloud.githubusercontent.com/assets/6584772/9665480/0ec2bea4-5247-11e5-8d69-a84ce6af8846.png)

![r51](https://cloud.githubusercontent.com/assets/6584772/9665487/13651592-5247-11e5-95fd-2432fe9991f2.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Poderia verificar a ação que antes era realizada, pois a mensagem de confirmação havia sido retirada conforme destacada na documentação. Ou seja, esta mensagem de confirmação não estava sendo mais utilizada neste caso de uso.

![msg012](https://cloud.githubusercontent.com/assets/6584772/10144100/13f2ad6c-65f2-11e5-9589-c7aaf142a517.PNG)

**Comment by jadossantos** [comment]
Monica, 
Identifiquei 2 pontos na tela de edição de um <b>Roteiro</b> que apresentam a mensagem <B>MSG012</b>, porém o <b>CDU</b> que está disponível na <b>branch master</b> apresenta a mensagem.
É para remover a mensagem ou não?

**Comment by monicaleite** [comment]
Joel, 

Segundo uma conversa que houve entre Rogério e Cleber na época foi solicitado que essa mensagem deveria ser removida do caso de uso, se ainda existe no CDU, eu irei remover depois da documentação. Pode remover!

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
