### ISSUE TITLE
SICEL_001_Manter Tipo de Resposta - Estrutura da Classe Tipo Escolha

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#318]
Foram cadastrados novos registros como: Cadastro do Tipo de Resposta, Quesito, Categoria/Grupo, Roteiro, Tipo de Procedimento, Procedimento e Execução deste PROCEDIMENTO criado, porém foi constatado que após a execução deste procedimento, o TIPO DE RESPOSTA - ESCOLHA perdeu a estrutura que é considerada item obrigatório para realização do cadastro.
![tr](https://cloud.githubusercontent.com/assets/6584772/9666115/97c45f20-524a-11e5-96a8-a72606172ec5.png)

**Comment by rsantanam** [comment]
Resolvido

**Comment by jmatil** [comment]
Confirmado
