### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - encontrado alguns erros na escrita

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#32]
Ao ler o documento acima, percebi algumas palavras colocadas de modo indevido nas frases. Segue abaixo os problemas e respectivas sugestões.

Problema: 
    FA 3.4. O sistema excluí a categoria e exibe mensagem de sucesso; [MSG007] 
Sugestão:
    retirar o acento de "excluí"

Problema:
    FA 5.1. O ator aciona seleciona a opção de gerar PDF do detalhamento;
Sugestão:
    adicionar uma barra ('/') entre as palavras "aciona" e "seleciona", ou retirar uma delas.

Problema:
    a descrição do botão "Gerar PDF" do item FA 5. está da escrita seguinte forma: "Permite gerar o um detalhamento no formato PDF."
Sugestão:
    retirar a letra "o" entre "gerar" e "um"

**Comment by monicaleite** [comment]
Victor, 

Todas as sugestões foram aceitas, o documento foi atualizado no git.

Obrigada.

**Comment by vogoncalves** [comment]
Conferido, disponha!
