### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Mensagem de Preenchimento

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#320]
O sistema está emitindo a mensagem de preenchimento obrigatório para um item que já está preenchido. Seguir os passos conforme imagens anexas:
1) 
![cat 1](https://cloud.githubusercontent.com/assets/6584772/10288047/f2420368-6b6c-11e5-89be-0920b46ccf88.png)
2)
![cat 2](https://cloud.githubusercontent.com/assets/6584772/10288053/f9ec3714-6b6c-11e5-8c6b-7e5ec26f9aac.png)
3) 
![cat 3](https://cloud.githubusercontent.com/assets/6584772/10288059/008ecf5a-6b6d-11e5-93e6-f4ff2df748e0.png)
4)
![cat 4](https://cloud.githubusercontent.com/assets/6584772/10288063/070708ca-6b6d-11e5-9559-60c3b8756217.png)
5)
![cat 5](https://cloud.githubusercontent.com/assets/6584772/10288067/0d0ea6ba-6b6d-11e5-93e6-62fdc526cd39.png)

**Comment by jadossantos** [comment]
Jailson, 
Essa mensagem é porque um grupo deve ter pelo menos um quesito e no exemplo acima não tem.

**Comment by jmatil** [comment]
A imagem "3" apresenta a situação onde foi acionado a opção para inclusão de um "Quesito", mas parece que se encontra no mesmo nível do Grupo ("não sei se irá ajudar"). Nesta situação, ao acionarmos a opção para inclusão de um QUESITO, a aplicação está gerando um campo de cadastramento de "GRUPO". Este campo gerado até preenchemos com informações (autocomplete) dos quesitos existentes no sistema. Poderia avaliar novamente?

![quesito](https://cloud.githubusercontent.com/assets/6584772/10336131/f4bc04d4-6ccc-11e5-943d-6c919c6f76b3.png)

**Comment by jadossantos** [comment]
Jailson,
O ícone do "+" irá adicionar uma nova linha do mesmo tipo e no mesmo nível que a linha atual se estiver.

Obs.: Você pode arrastar e soltar o quesito em cima do grupo, para que o quesito volte a ser 1.2.1 no caso acima.

**Comment by jmatil** [comment]
Compreendido
