### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Menu "Executar Procedimento"

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#321]
Ao acessar o menu [EXECUTAR PROCEDIMENTO], e realizar diversos acessos simultâneos nesse menu, o sistema exibe a mensagem "Nenhum procedimento atribuído para a unidade eleitoral "
porem a mensagem permanece se em seguida acessar o menu [PROCEDIMENTO] conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/10289516/11e0b8f6-6b75-11e5-8c1e-4f35ca008bf8.png)

![1](https://cloud.githubusercontent.com/assets/9218077/10289573/6b1c7b08-6b75-11e5-8904-edd4561c5f5a.png)

**Comment by jadossantos** [comment]
Isso é um erro. 
Irei alterar o status e verificar depois.

**Comment by kleiberfaria** [comment]
Obrigado Joel !

**Comment by jadossantos** [comment]
Resolvido

**Comment by kleiberfaria** [comment]
Joel, seria possível você limpar a base para que eu possa realizar o teste para esse Git? Não pode ter nenhum [Procedimento Cadastrado]

**Comment by jadossantos** [comment]
Kleiber, mude o tribunal. Por exemplo, TRE-BA.

**Comment by kleiberfaria** [comment]
Item verificado !
