### ISSUE TITLE
SICEL_CDU_002_Manter Categoria_Grupo - Autocomplete

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#322]
O sistema está autocompletando os campos com registros inexistentes na aplicação (itens que já foram excluidos).

![categoria](https://cloud.githubusercontent.com/assets/6584772/10309481/3652c244-6c13-11e5-94b1-a09f301a3943.png)

![grupo 2](https://cloud.githubusercontent.com/assets/6584772/10309484/3b76db48-6c13-11e5-86ad-85204d3707d7.png)

**Comment by jadossantos** [comment]
Jailson, como você simulou esse problema?

Obs.: Todas as <b>categorias</b>, <b>grupos</b> e <b>quesitos</b> são carregados previamente na tela de cadastro, para otimizar o processamento do autocomplete. Caso seja excluído algum registro neste momento a "lista" pré-carregada não será atualizada.

**Comment by jmatil** [comment]
Simulei novamente a ação e foi constatado que estes registros que estão aparecendo pertenciam a procedimentos que havia sido criados e executados.

**Comment by jadossantos** [comment]
Jailson, 
Fiz a carga na base de dados. 
Respondi e fechei um procedimento. 
Removi a categoria e o problema não aconteceu. 
Removi o grupo e o problema também não aconteceu. 

Poderia verificar novamente?
