### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Alteração da ordem dos itens cadastrados

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#324]
Na tentativa de ALTERAR a forma como os quesitos foram posicionados no ROTEIRO  e acionar a opção "Salvar", o sistema emite a mensagem de sucesso, mas não grava o posicionamento do qual foi posto os itens alterados.

Registro do qual foram alterados o posicionamento dos QUESITOS
![a](https://cloud.githubusercontent.com/assets/6584772/10400642/4883f13e-6e90-11e5-95b3-5a5b096ac20b.png)

Visualização do REGISTRO recém alterado
![b](https://cloud.githubusercontent.com/assets/6584772/10400709/ad73ee64-6e90-11e5-91c8-cbc792c35fd7.png)

**Comment by jadossantos** [comment]
Resolvido. 
Lembrando que a numeração seguirá a ordem (Categoria_Quesito, Grupo, e Grupo_quesito).

**Comment by jmatil** [comment]
Poderia verificar novamente, pois aparentemente a correção que foi feita não está disponivel para realização do reteste. Ação permanece

**Comment by jadossantos** [comment]
O jenkins está com problema e o build não aconteceu. Estou verificando.

**Comment by jmatil** [comment]
Aguardo a solução deste problema para confirmar a correção da issue

**Comment by jmatil** [comment]
Correção confirmada
