### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Incluir Roteiro sem o Grupo | Erro 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#325]
Ao incluir um "ROTEIRO" com uma Categoria/Grupo sem o "GRUPO" o sistema apresenta erro.
Passos:
1. Categoria/grupo: Incluir Categoria/Grupo sem o Grupo > Salva
2. Menu: Elaborar > Incluir Roteiro > Elaborar
![1](https://cloud.githubusercontent.com/assets/9218077/10465340/ce06e582-71c4-11e5-8bbd-d1f0ec52ee4f.png)
![2](https://cloud.githubusercontent.com/assets/9218077/10465450/59c910cc-71c5-11e5-8af3-e7175e0e7714.png)
![3](https://cloud.githubusercontent.com/assets/9218077/10465366/e6f80daa-71c4-11e5-8895-372cd50c07cb.png)

**Comment by jadossantos** [comment]
Resolvido.
Aguardando a solução do build no jenkins.

**Comment by kleiberfaria** [comment]
Joel, 
Realizei o teste e o erro de log conforme evidenciado nesse Git, não ocorre mais. Porem, como foi criado uma [Categoria] e [Quesito] sem o grupo, o sistema não esta apresentado a contagem do quesito conforme Git aberto de número #330

![4](https://cloud.githubusercontent.com/assets/9218077/10700037/e3208950-7999-11e5-90d0-fa69832ad380.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by kleiberfaria** [comment]
Item verificado!
