### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Campo horário

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#326]
Verificar a solicitação da regra para o campo horário.
1) Cadastrar um tipo de resposta com classe horário;
2) Vinculá-la ao Quesito.
3) Realizar o restante dos procedimentos para realização da execução
4) Verificar que o campo aceita caracteres alfanuméricos com 200 caracteres.

![horario](https://cloud.githubusercontent.com/assets/6584772/10522613/722f173c-734c-11e5-9dfa-bb31edc67918.png)

**Comment by jadossantos** [comment]
Resolvido. Adicionei um componente do primefaces.

**Comment by jmatil** [comment]
Confirmado a implementação do componente
