### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Execução do Componente Implementado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#327]
Ao selecionar um dos itens disponibilizados pelo componente o sistema está emitindo a mensagem destacada abaixo:
Obs.: Este item é relacionado a classe Horário - Tipo de Resposta

![a](https://cloud.githubusercontent.com/assets/6584772/10633842/4ef3a92a-77cc-11e5-96e6-40d698991739.png)

![b](https://cloud.githubusercontent.com/assets/6584772/10633846/53e995c0-77cc-11e5-8760-40454a3e272a.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
