### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Exclusão de Roteiro vinculado a um e único PROCEDIMENTO

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#328]
Verificar situação ocorrente após acionar a opção para exclusão de um roteiro vinculado a um e único PROCEDIMENTO.
![a](https://cloud.githubusercontent.com/assets/6584772/10634167/9d5a2b78-77ce-11e5-9fb8-4b4bb33facde.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Correção confirmada
