### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - Execução do Componente Implementado - HORAS

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#329]
Este componente implementado que detalha horas e minutos parece estar faltando os ultimos itens: 56, 57, 58, 59. Isso é comum para este item?
![componente](https://cloud.githubusercontent.com/assets/6584772/10674155/55c53450-78d8-11e5-8d4d-15b84e5683d7.PNG)

**Comment by jadossantos** [comment]
Resolvido. O componente por padrão exibia até 55 minutos.

**Comment by jmatil** [comment]
Confirmado
