### ISSUE TITLE
SICEL_RMG - Regras com referências incomplestas

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#33]
Na parte: "Nome do(s) caso(s) de uso que utiliza(m) essa regra:", as regras descritas abaixo não estão referenciando todos os CDU que realmente as utilizam.

Problema 01:
Em RAP004, RAP005, está informando que estas, estão sendo utilizadas apenas pelo Manter Tipo de Resposta, mas os CDUs Manter Categoria, Manter Grupo e Manter Quesito também fazem referência a essas regras.

Sugestão:
## Colocar: "Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Tipo de Resposta, Manter Categoria, Manter Grupo e Manter Quesito."

Problema 02:
Em RAP003, está informando que este, está sendo utilizado apenas pelo Manter Tipo de Resposta, mas os CDUs Manter Categoria e Manter Grupo também fazem referência a essa regra.

Sugestão:
## Colocar: "Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Tipo de Resposta, Manter Categoria e Manter Grupo."

Problema 03:
Em RN004, está informando que este, está sendo utilizado apenas pelo Manter Tipo de Resposta, mas os CDUs Manter Categoria, Manter Grupo e Manter Quesito também fazem referência a essas regras.

Sugestão:
## Colocar: "Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Tipo de Resposta, Manter Categoria, Manter Grupo e Manter Quesito."

Problema 04:
Em RN002, está informando que este, está sendo utilizado apenas pelo Manter Tipo de Resposta, mas os CDUs Manter Categoria, Manter Grupo e Manter Quesito também fazem referência a essas regras.

Sugestão:
## Colocar: "Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Tipo de Resposta, Manter Categoria, Manter Grupo e Manter Quesito."

Problema 05:
Em RN001, está informando que este, está sendo utilizado apenas pelo Manter Tipo de Resposta, mas os CDUs Manter Categoria, Manter Grupo e Manter Quesito também fazem referência a essas regras.

Sugestão:
Colocar: "Nome do(s) caso(s) de uso que utiliza(m) essa regra: Manter Tipo de Resposta, Manter Categoria, Manter Grupo e Manter Quesito."

**Comment by monicaleite** [comment]
Victor,

Todas as sugestões foram aceitas, o documento foi atualizado no git.

Obrigada.

**Comment by vogoncalves** [comment]
Conferido.
