### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - Detalhamento do Roteiro

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#330]
Ao alterar o conteúdo de um roteiro, acrescentando um Quesito no registro, o sistema não está computando esse Quesito quando é solicitado o detalhamento.

![roteiro](https://cloud.githubusercontent.com/assets/6584772/10698976/67f609f0-7992-11e5-9dcc-5fca43776d06.png)

**Comment by jadossantos** [comment]
Resolvido. Não estava contando os quesitos vinculados diretamente a categoria.

**Comment by jmatil** [comment]
Correção confirmada
