### ISSUE TITLE
SICEL_CDU_002_Manter Quesito - Inconsistência entre imagem e descrição do campo nome

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#34]
Em PT 2.    Incluir Quesito (imagem protótipo de inserir), o campo "Nome*:" está com asterisco, porém na descrição desse campo diz que ele é não obrigatório. Segue abaixo imagem exibindo o problema.

![sicel_cdu_002_manter quesito - inconsistencia entre imagem e descricao do campo nome](https://cloud.githubusercontent.com/assets/8506935/4171030/43e60bc6-3539-11e4-812f-3cbcca2b2ac1.PNG)

**Comment by monicaleite** [comment]
Victor,

O campo realmente é obrigatório, já corrigi a documentação e atualizei o git.

**Comment by vogoncalves** [comment]
Conferido.
