### ISSUE TITLE
sicel_homolog.tse.jus.br - Dúvida com o funcionamento de "Adicionar um quesito"

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#35]
em http://sicel_homolog.tse.jus.br/ 
Roteiros > Elaborar (escolha na listagem a opção “Correição Ordinária 2009   Corregedoria Geral Eleitoral    BR  23/07/2009  Sim” )

Ao tentar adicionar um quesito, um componente é exibido mostrando a mensagem de que não existe quesito e que é para cadastrar um novo. Este realmente é o comportamento esperado? Caso contrário, como deveria ser?

Segue imagem de referência em anexo.

![adicionar quesito sem informacoes](https://cloud.githubusercontent.com/assets/8506935/4288778/c3928da4-3dae-11e4-8dc1-6fecfae9c67f.PNG)

**Comment by raphaelgalvao** [comment]
Monica,

Precisamos simular um caso onde os campos associados ao cadastro de um quesito aparecam, nao conseguimos encontrar nenhum registro para tentar realziar essa operação, em todos os casos aparece essa mensagem acima.

**Comment by monicaleite** [comment]
Esse mensagem deve ter ocorrido, pois você adicionou todos os quesitos que existiam para aquele grupo em questão, para incluir mais quesitos você terá que ir no grupo e vincular mais quesitos para eles possam ser exibidos no grupo em questão no momento de elaborar o roteiro.
Pode ter ocorrido também por possuir um grupo que não possui nenhum quesito cadastrado para ele, nesse caso também terá que cadastrar quesitos para o grupo em questão. 
Mas esse é comportamento do sistema atual. 
De acordo com os casos de uso da iteração 2 já especificados isso só poderá ocorrer no sistema  para categoria, pois não é obrigado cadastrar o grupo com a categoria no mesmo momento. 
No momento do cadastro do grupo é obrigatório informar ao menos um quesito para ele, logo no roteiro nunca terá um grupo sem nenhum quesito.
Foi criado um roteiro para vocês utilizarem para teste nome "Teste - SICEL - TSE", nesse tem como incluir quesitos.

**Comment by vogoncalves** [comment]
Obrigado Monica, dúvida esclarecida.
