### ISSUE TITLE
sicel_homolog.tse.jus.br - Dúvidas com atributo tipo classe na aba quesito

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#36]
em http://sicel_homolog.tse.jus.br/ 
Roteiros > Elaborar (escolha na listagem a opção “Correição Ordinária 2009 Corregedoria Geral Eleitoral BR 23/07/2009 Sim” )

Em quesitos é apresentado uma informação (fixa) informando o tipo da classe, se é "Obs", "Número" ou "Escolha". O que representa essa informação e como ela será atrelada aos quesitos? Quesito terá um atributo "Classe" como TipoResposta ou será o mesmo do tipoResposta?

Segue imagem de referência em anexo.
![duvida campos quesito](https://cloud.githubusercontent.com/assets/8506935/4289188/a8e5aae2-3db1-11e4-94b1-d28b26e56475.PNG)

**Comment by raphaelgalvao** [comment]
Só conseguimos identificar esses tipos mecionados no print. Possa ser que existam mais, e quais outras informações estao associados a isso? E de onde virá essas informações?

Por exemplo:
ESCOLHA: Nao conforme / Exige Aperfeicoamento / Nao se aplica / Conforme
OBS
NUMERO

**Comment by monicaleite** [comment]
Essas informações virão do Manter Tipo de Resposta.

**Comment by vogoncalves** [comment]
Obrigado Monica, dúvida esclarecida.
