### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Em Detalhar é apresentado "Editar"

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#37]
Em PT 4. Detalhar Quesito, o título está como "Editar Quesito", quando deveria estar "Detalhar Quesito". Ver imagem em anexo.
![detalhar erro](https://cloud.githubusercontent.com/assets/8506935/4465815/c1d889c4-48de-11e4-94c7-0d03dfe08638.PNG)

**Comment by monicaleite** [comment]
Corrigido. O git está atualizado.

**Comment by vogoncalves** [comment]
Verificado.
