### ISSUE TITLE
Manter Quesito e Manter Tipo Resposta - Comportamentos diferentes no detalhar

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#38]
Nos casos de uso "SICEL_CDU_001_Manter Tipo de Resposta" e "SICEL_CDU_004_Manter Quesito" o comportamento para visualizar os detalhes de uma informação acontece de forma diferente. No primeiro é por um ícone de uma lupa e no outro é clicando no nome. Esse comportamento é realmente para ser distinto entre as páginas? Aconselhamos manter um padrão de usabilidade para o sistema, optando por apenas uma das opções.

![mtr](https://cloud.githubusercontent.com/assets/8506935/4491724/3caf9e5a-4a3b-11e4-9465-991ac3036b6a.PNG)
![quesito](https://cloud.githubusercontent.com/assets/8506935/4491731/45917bec-4a3b-11e4-8643-7e379b84366e.PNG)

**Comment by monicaleite** [comment]
Victor,

Provavelmente o tipo de resposta será alterado para ficar conforme o Manter Quesito, o cliente está ciente da diferença e mesmo assim solicitou que o detalhamento seja com o link no dados da listagem, os demais casos de uso que possuem listagem estão adotando o mesmo comportamento de link.

**Comment by vogoncalves** [comment]
Ok, será mantido então os dois padrões nessas telas.
