### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Dúvida na apresentação dos campos Grupo e Categoria no detalhar

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#39]
No PT 4. Detalhar quesito, os campos "Categoria" e "Grupo" são somente leitura. Mas um quesito pode fazer parte de mais de um grupo e categoria. Neste caso, como ficaria a visualização desses campos já que eles podem ser vários?

![detalhar 1](https://cloud.githubusercontent.com/assets/8506935/4496790/422bba84-4a69-11e4-93f0-743ecc5e4f85.PNG)

**Comment by monicaleite** [comment]
Victor, 

Realmente ficou uma falhar no requisito, falei com o Gerente do Projeto, que disse que no editar e no detalhar vcs podem exibir qualquer categoria e grupo. Será aberta uma SM posteriormente para definição de como ficará essa situação no sistema. Para entrega façam conforme conversamos por telefone.

Obrigada.

**Comment by vogoncalves** [comment]
Ok Monica, 

então conforme foi acordado por telefone, caso um Quesito possua mais de uma Categoria e/ou Grupo, preencher o(s) campo(s) com qualquer valor dentre as existentes.
