### ISSUE TITLE
CDU_SICEL_001_Manter Tipo de Resposta - Remoção das Escolhas

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#4]
Ao editar um Tipo de Resposta que possui a classe Escolha e após a edição esta classe foi alterada para qualquer outra, as escolhas (texto e peso) previamente incluídas podem ser removidas ? Atualmente este comportamento foi adotado na implementação.

**Comment by monicaleite** [comment]
Sim, depois de incluídas podem ser removidas.
