### ISSUE TITLE
SICEL_RMG - Validação de nomes deverá ser case sensitive?

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#40]
No item 2.1 RN001 – Informação Duplicada o Manter Quesito informa que deverá ser validado apenas pelo Nome, mas a validação será case sensitive, ou não? Por exemplo, devo considerar igual ou diferente os nomes: "Exemplo1" e "exemplo1"?

**Comment by monicaleite** [comment]
Deverá ocorrer a  validação será case sensitive.

**Comment by vogoncalves** [comment]
Ok, será diferenciado maiúsculos de minúsculos.
