### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Deverá permir a inclusao de Quesitos no mesmo grupo?

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#41]
Na RN015 diz que: "O sistema deverá verificar se o quesito a ser incluído já existe em grupo da mesma categoria, existindo ele deve seguir o passo em que solicita a confirmação do ator para inclusão. Caso não tenha o sistema vai direto para o passo em que realiza a inclusão e emite a mensagem de sucesso."

Já na RN016 diz: "Um quesito pode pertencer a mais um grupo e categoria.
A duplicidade do quesito será verificada somente quando o usuário tentar incluir o mesmo nome de quesito para o mesmo grupo."

Considerando os fatos, a inserção de quesitos com o mesmo nome pertencentes ao mesmo grupo deverá ser permitida? Caso verdadeiro, o banco de dados terá que ser mudado, pois hoje isso não é permitido. Caso positivo, como será o comportamento da tela? Haverá a real necessidade de uma confirmação do usuário, sendo que o sistema não permite?

**Comment by monicaleite** [comment]
Vitor,

O usuário pode incluir um quesito para um grupo diferente mas que pertence a mesma categoria, o que ele não poderá é incluir no mesmo grupo, ou seja em um outro grupo da mesma categoria ele pode incluir.

Vou tentar melhorar a RN15 para deixar mais claro isso.

**Comment by vogoncalves** [comment]
Alteração confirmada.

Obrigado Monica!
