### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Registro Duplicado

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#42]
Quais campos serão avaliados para considerar um registro duplicado? o nome e a descrição da categoria ou apenas o nome da categoria ? Até o momento é realizada uma verificação somente sobre o campo nome da categoria.

**Comment by monicaleite** [comment]
Será pelo nome da categoria somente.

**Comment by nandoalmeida** [comment]
Ok, issue será fechada.
