### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Ordenar por Data de criação ou ordem numérica?

### ISSUE THREAD

**Issue by vogoncalves** [islssa/SICEL#43]
O item FB2 contém referência para o [RAP003], o qual informa: "O sistema deverá ordenar por data de criação e, caso o usuário deseje, poderá realizar sua própria ordenação das informações cadastradas.". 
O primeiro empecilho é que, no banco, a tabela GRUPO não possui a coluna DT_CRIACAO. Segundo, na listagem de grupo também não existe uma coluna de data de criação, tornando um pouco sem sentido ordenar por algo que o usuário nem pode visualizar. Terceiro, caso seja alterado a ordem de um item manualmente, a ordenação por data terá que ser descartada.

Sugestão: ordenar apenas pela numeração do item da lista, remover assim a referência [RAP003] do item FB2 e explicitar no documento a ordenação apenas pela numeração.

**Comment by monicaleite** [comment]
Victor,

Devido a questão de log na inclusão o sistema deve guardar quem fez, quando etc.. a listagem inicial quando o usuário entrar será baseado nesse data, a data mais recente e permite também que o usuário faça a reordenação conforme o exemplo em protótipo.

Caso tenha dúvida me ligue.

**Comment by monicaleite** [comment]
A RAP003 será retirada do documento.

**Comment by vogoncalves** [comment]
Ok Monica! Aguardando retirada da RAP003 para fechamento desta issue.

**Comment by monicaleite** [comment]
Já foi retirada.

**Comment by vogoncalves** [comment]
Item retirado. Esta issue deve ser fechada.
