### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Não exclusão da categoria

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#44]
Ao excluir uma categoria, conforme FA 3 "Excluir Categoria" o sistema não permite a exclusão no campo "Operações" conforme imagem em anexo. 
![sicel_cdu_002_manter categoria - nao exclusao da categoria](https://cloud.githubusercontent.com/assets/6584772/4630028/18783100-53aa-11e4-8ce1-7cda07a8114f.jpg)

**Comment by nandoalmeida** [comment]
Esse comportamento estava realmente incorreto e já foi resolvido, no entanto outro problema, desta vez na trigger disparada, não está permitindo a exclusão lógica de um registro de Categoria. Já estamos trabalhando na reformulação da trigger/método.

**Comment by nandoalmeida** [comment]
Pendências com triggers já resolvidas, issue resolvida.

**Comment by kleiberfaria** [comment]
Item verificado e conferido.

**Comment by kleiberfaria** [comment]
Concluido.
