### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Label (Opcional)

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#45]
Prezados
Favor verifica a label descrita na documentação conforme imagem abaixo (falta a opção opcional):

![label](https://cloud.githubusercontent.com/assets/6584772/4632611/4553a302-53bf-11e4-99c1-ceefd7ab287c.png)

**Comment by nandoalmeida** [comment]
Jailson, segundo o comentário realizado por Mônica na issue #49 

<b><i>"O protótipo é apenas para exemplo e orientação, a documentação já informa que é obrigatório e por padrão colocar o \* nos campos conforme feito para os demais."</i></b>

Imagino que a palavra <b>opcional</b> não deva ser de fato impressa na tela, tal como ocorre em outras telas onde os campos não são obrigatórios.

**Comment by jmatil** [comment]
Ação confirmada. A palavra "Opcional" não deverá ser impressa na tela

**Comment by jmatil** [comment]
Prezados
Em conversa com a Mônica foi acordado que esta label ("Opcional") deverá realmente ser implementada.

**Comment by monicaleite** [comment]
A palavra opcional é sim para ser exibida. Em relação a ser exemplo e orientação está correto, mas na leitura e descrição dos campos na tabela o nome é colocado da forma que deve ser exibido, do contrário teria descrito no detalhamento apenas as palavras sem o (opcional).

**Comment by nandoalmeida** [comment]
Ok, corrigido favor verificar.

**Comment by jmatil** [comment]
Confirmado a correção

![issue](https://cloud.githubusercontent.com/assets/6584772/4750914/4b2c8b9c-5a98-11e4-9c3a-7465a7871fcb.png)
