### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Ordenação

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#46]
Prezados
Favor verificar a situação de ordenação dos quesitos utilizando a aba "Data de Criação" conforme imagem abaixo. Funcionalidade não disponível

![ordenacao](https://cloud.githubusercontent.com/assets/6584772/4632940/8ae3d844-53c2-11e4-913e-167d78be005f.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Item verificado e constatado a correção
