### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Ordenação conforme RAP16

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#47]
Prezados
Favor verificar a ordenação dos itens dispostos para a funcionalidade. Segue imagem 

![issue](https://cloud.githubusercontent.com/assets/6584772/4633137/570cdad2-53c4-11e4-9e97-08fdcf962f2f.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Confirmado a correção
