### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Excluir Quesito

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#48]
Prezados
Favor verificar a situação após tentativa de exclusão de um quesito. Segue imagem

![issue](https://cloud.githubusercontent.com/assets/6584772/4633375/cccc7e6a-53c6-11e4-8961-99c388037e92.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jadossantos** [comment]
O erro acontecia por causa da trigger que estava com problemas.

**Comment by jmatil** [comment]
Verificado a correção do item
