### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Atualização da interface (Inclusao/Edicao)

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#49]
Será necessário atualizar a documentação para que os prótotipos das telas de inclusão e edição apresentem o asterísco ao lado dos campos obrigatórios (Nome e Descrição), bem como adicionar a legenda que informa o significado do asterísco.

A tela foi implementada incluindo apenas os asteríscos:
![pic10](https://cloud.githubusercontent.com/assets/7429018/4634089/f2388bd4-53cc-11e4-96c0-142b34fd4d8a.png)

A documentação apresenta o seguinte protótipo:
![pic11](https://cloud.githubusercontent.com/assets/7429018/4634094/fe97ad38-53cc-11e4-9ada-36fea989dd9c.png)

Favor verificar.

**Comment by monicaleite** [comment]
O protótipo é apenas para exemplo e orientação, a documentação já informa que é obrigatório e por padrão colocar o \* nos campos conforme feito para os demais.

**Comment by nandoalmeida** [comment]
Ok, fechando issue.
