### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Editar Tipo de Resposta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#5]
Prezados
Favor verificar o comportamento do sistema, pois está permitindo duplicar cadastro após acionar a edição de um já existente, ou seja, na realização de um novo cadastro o sistema valida a ação e não permite que haja cadastros duplicados, mas ao alterar um cadastro existente o sistema permite que se faça o cadastro com os dados de um item já cadastrado. Segue imagem para as devidas comparações.

![cadastroduplicado](https://cloud.githubusercontent.com/assets/6584772/3648242/48c4b0da-1107-11e4-83de-9ffbd8310eb6.PNG)

**Comment by nandoalmeida** [comment]
Resolvido.

**Comment by jmatil** [comment]
foi verificado a correção do item
