### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Sugestão para a interface do rodapé na grid.

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#50]
A interface foi construída da maneira visualizada na imagem abaixo:

![pic13](https://cloud.githubusercontent.com/assets/7429018/4634231/4ec25a64-53ce-11e4-8380-38144b9a5978.png)

Ainda que não siga exatamente a sugestão do protótipo, a implementação obedece a regra de apresentação RAP008.

Protótipo:
![pic14](https://cloud.githubusercontent.com/assets/7429018/4634245/6610b54e-53ce-11e4-96cf-d95a3b851a0e.png)

<b>RAP008</b>
![pic12](https://cloud.githubusercontent.com/assets/7429018/4634250/725daeba-53ce-11e4-8908-919b204e8dbc.png)

Favor avaliar e se for o caso ajustar o protótipo na documentação.

**Comment by monicaleite** [comment]
A regra diz que o usuário tem que ter a possibilidade de informar o número, a solução dada por vcs está atendendo a regra, acredito que o gestor não irá solicitar que seja como o exemplo do protótipo.

**Comment by nandoalmeida** [comment]
Entendo. Hoje o usuário pode informar o número da página que deseja visualizar através de um combobox,

![pic15](https://cloud.githubusercontent.com/assets/7429018/4635819/74b9badc-53dd-11e4-8e82-a6c18b3e3138.png)

a dúvida ocorre pois o protótipo sugere que é um input normal de texto. Em ambos os casos, a implementação não fere a regra pois possibilita a mesma função para o usuário.

<b><i>" ... permitir que o usuário informe o número da página que deseja listar, ao ser informado o sistema deve exibir a página em questão."</i></b>

Aparentemente o componente que utilizamos não possui originalmente um rodapé para a paginação como o sugerido no protótipo, por isso questionamos se é uma condição relevante para a interface.

**Comment by monicaleite** [comment]
Vou levar a informação para o Elder que o gerente de projeto para vê se ele aprova.

**Comment by jadossantos** [comment]
Mônica,
Conforme conversamos por telefone a implementação atende ao comportamento desejo, ou seja, podemos fechar essa issue.

**Comment by nandoalmeida** [comment]
Em conversa realizada através do Lync ficou decidido que é relevante que a busca seja realizada através de um campo input como sugere o protótipo. Mônica irá criar um fluxo de exceção para quando uma página inexistente for solicitada.

Esta issue será fechada.

Fechando a issue.
