### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Mensagem 002

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#51]
Prezados
Favor verificar a mensagem emitida pelo sistema conforme imagem anexa. Simulação realizada caso não encontre registro com os parâmetros informados pelo usuário.

![issue](https://cloud.githubusercontent.com/assets/6584772/4678148/ddda4b88-55f1-11e4-8c24-e99e2017564c.PNG)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Verificado a correção
