### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Gerar PDF

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#52]
Para conhecimento,
Na tentativa de gerar o Fluxo Alternativo FA 5. Gerar PDF, o sistema apresenta a seguinte tela de mensagem conforme anexo.
![sicel_gerar pdf](https://cloud.githubusercontent.com/assets/9218077/4735482/fc405f20-59e0-11e4-85fb-593f0db7ec44.jpg)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !!!
![gera_pdf](https://cloud.githubusercontent.com/assets/9218077/4790558/8a55317e-5dd2-11e4-94a8-80c876c7b803.jpg)
