### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Mensagem de Hint

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#53]
Prezados
Favor avaliar a solicitação detacada na documentação onde é exigido a apresentação de um "Hint" para a ação de detalhamento da categoria cadastrada. 

![issue](https://cloud.githubusercontent.com/assets/6584772/4735533/607cd7a2-59e1-11e4-9a33-ecfb29d52a30.PNG)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada.

![issue](https://cloud.githubusercontent.com/assets/6584772/4750947/940ccda4-5a98-11e4-9aa9-e05d0b8a7c55.png)
