### ISSUE TITLE
 SICEL_CDU_002_Manter Categoria - Mensagem de Página Inexistente

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#54]
Prezados
Favor avaliar a mensagem emitida ao não encontrar a página solicitada pelo ator.

![issue](https://cloud.githubusercontent.com/assets/6584772/4735890/1e3e1630-59e6-11e4-8d7c-1d1045853c3f.PNG)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Confirmado a correção.

![issue](https://cloud.githubusercontent.com/assets/6584772/4750960/c8fa45d2-5a98-11e4-9d03-09c9987b0def.png)
