### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Opção de cancelamento do cadastramento

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#55]
Prezados
Há necessidade da opção de cancelamento ao realizar o cadastramento da categoria?

![issue](https://cloud.githubusercontent.com/assets/6584772/4736612/2dff25c0-59ee-11e4-8e2a-b39be39404c4.PNG)

**Comment by monicaleite** [comment]
Jailson, 

O correto é RAP005, já atualizei o caso de uso.

**Comment by jmatil** [comment]
Confirmado a atualização

![issue](https://cloud.githubusercontent.com/assets/6584772/4751043/b006cacc-5a99-11e4-803c-7d7625fa1c94.png)
