### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Acionamento da opção Salvar após ter alterado um registro já salvo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#56]
Prezados
Favor avaliar a seguinte simulação:
1º) Foi realizado um cadastramento com sucesso e o sistema disponibilizou a tela com a opção de inclusão do Grupo, juntamente com a opção de "Voltar";
2º) Foi acionado a opção "Voltar" e o sistema disponibilizou novamente a tela de cadastramento, juntamente com as opções de "Salvar" e "Voltar".
3º) Foi alterado o conteúdo que já estava preenchido e acionado a opção "Salvar" e o sistema emitiu a mensagem destacada abaixo.

![issue1](https://cloud.githubusercontent.com/assets/6584772/4739147/56e60328-5a02-11e4-9106-ea4e4eaa605d.PNG)

![issue2](https://cloud.githubusercontent.com/assets/6584772/4739159/758fc548-5a02-11e4-8d03-43f5c7678906.PNG)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Confirmado a correção
