### ISSUE TITLE
SICEL_CDU_003_Manter Grupos - Detalhar Grupo

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#57]
Os fluxos e telas de Detalhamento de Categoria (CDU_002) e Detalhamento de Grupos (CDU_003) estão idênticos. O detalhamento de um grupo irá exibir todos os grupos e quesitos da categoria que ele faz parte ?

**Comment by monicaleite** [comment]
Sim, todos os vínculos que ele possuir deve ser exibido, se não possuir nenhum, detalha somente as informações dele.

**Comment by nandoalmeida** [comment]
Ok, entendido.
