### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Excluir Resposta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#58]
Prezados
Favor avaliar a funcionalidade de Exclusão de uma resposta cadastrada, pois o sistema não está respondendo a solicitação.

![issue](https://cloud.githubusercontent.com/assets/6584772/4758037/0b9ce1f4-5adc-11e4-970d-c1c0e92bfc67.png)

**Comment by nandoalmeida** [comment]
Resolvido, favor verificar.

**Comment by jmatil** [comment]
Verificado a correção
