### ISSUE TITLE
SICEL_CDU_001_Manter Tipo de Resposta - Excluir Respostas que não estão mais vinculadas

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#59]
Prezados
Favor analisar as respostas que não têm mais vínculos com outras funcionalidades, pois o sistema não está permitindo excluí-las, ou seja, o vínculo foi retirado, mas o sistema não permite excluir.

![issue](https://cloud.githubusercontent.com/assets/6584772/4768560/3c80b850-5b6c-11e4-9328-7cd346ed232c.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Verificado a correção
