### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Incluir Tipo de Resposta

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#6]
Verificar o comportamento do sistema, pois não está permitindo cadastrar uma resposta com a classe : Escolha.

**Comment by jadossantos** [comment]
Problema resolvido.

**Comment by jmatil** [comment]
Foi verificado a possibilidade de Cadastramento com a classe "Escolha". Segue imagem com os resultados para as devidas comparações.

![cadastroescolha](https://cloud.githubusercontent.com/assets/6584772/3673112/0687d7f2-1269-11e4-98e4-ad93434a71f3.PNG)
