### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Editar Quesito

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#60]
Prezados,
Ao realizar a edição de um Quesito cadastrado acionando a opção "Editar Quesito", editando os campos *Nome ou *Nota e acionando a opção "VOLTAR"  a aplicação salva o que foi editado, porem ao acionar  "PESQUISAR" novamente, supostamente o que foi salvo acionando o "PESQUISAR" a aplicação retorna como se não tivesse realizando nenhuma edição.
![editar_quesito](https://cloud.githubusercontent.com/assets/9218077/4769434/cb7e0cb2-5b79-11e4-828c-f2580086d4cc.jpg)

**Comment by vogoncalves** [comment]
Problema resolvido. Favor verificar.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !
