### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Cabeçalho

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#61]
Prezados
Favor avaliar a inclusão do cabeçalho da funcionalidade de detalhamento do quesito.

![sistema](https://cloud.githubusercontent.com/assets/6584772/4769686/842cf68a-5b7d-11e4-90b0-c5f9040354b2.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção verificada

![issue](https://cloud.githubusercontent.com/assets/6584772/4793313/06080c14-5ded-11e4-849c-62a7c7355472.png)
