### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Excluir Categoria

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#62]
Prezados,

Ao excluir uma categoria relacionada a um grupo, a aplicação apresenta a mensagem conforme print em anexo.
![exclusao_categoria](https://cloud.githubusercontent.com/assets/9218077/4774314/09ecadaa-5bac-11e4-9e12-ef3334029076.jpg)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !
