### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Inclusão da categoria

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#63]
Prezados
Favor avaliar o comportamento do sistema após realizar o cadastramento de uma categoria. Segue imagem.

![issue](https://cloud.githubusercontent.com/assets/6584772/4806423/4f8b0552-5e89-11e4-8eb0-11ebbe9724d7.png)

**Comment by jadossantos** [comment]
O problema do banco de dados foi resolvido.

**Comment by jmatil** [comment]
Correção confirmada
