### ISSUE TITLE
SICEL_CDU_002_Manter Categoria - Exclusão da categoria

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#64]
Prezados
Verificar a ação do sistema ao simular a exclusão de um registro
![issue](https://cloud.githubusercontent.com/assets/6584772/4806465/cbf14354-5e89-11e4-91ae-e284e905b8f5.png)

**Comment by jadossantos** [comment]
O problema do banco de dados foi resolvido.

**Comment by jmatil** [comment]
Confirmado a correção
