### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Apresentação do item atualizado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#65]
Prezados
Verificar o comportamento do sistema, pois na tentativa de atualizar um quesito através da funcionalidade "Manter Grupo", o sistema atualizou, apresentou a mensagem de sucesso, mas não apresentou o item com as características informadas após confirmação do usuário. A visualização da alteração somente poderá ser visualizada se acionarmos o detalhamento ou solicitarmos novamente uma alteração.

![issue](https://cloud.githubusercontent.com/assets/6584772/4808532/bf8b683e-5ea1-11e4-955f-0b961f1c8fc5.png)

**Comment by vogoncalves** [comment]
Corrigido. Favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
