### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Detalhamento

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#66]
Prezados
Favor verificar a ação de detalhamento da categoria, pois ao acionar a opção para detalhar apenas um Grupo e seu conteúco, o sistema está detalhando todos os grupos cadastrado na aplicação com seus respectivos conteúdos. Segue exemplo:

![issue2](https://cloud.githubusercontent.com/assets/6584772/4811228/f35b1918-5eb8-11e4-9d30-1b4016a99f60.png)

**Comment by vogoncalves** [comment]
Este é o comportamento que está descrito na FA 4. Detalhar Grupo, mais especificamente na RAP006. Qualquer dúvida contactar Monica.

**Comment by vogoncalves** [comment]
Este questionamento foi levantado à Monica. Veja a issue referente ao problema.

SICEL_CDU_003_Manter Grupos - Detalhar Grupo #57

Essa issue responde sua pergunta?

No aguardo.

**Comment by monicaleite** [comment]
Victor,

Acho então que eu não entendi sua colocação nesse issue.! Se eu detalhar uma categoria, vou exibir todos grupos e quesito pertencentes a ela, se eu detalhar o grupo então eu mostro a categoria a que ele pertence e todos os quesitos que estão vinculados a ele.

**Comment by monicaleite** [comment]
Victor, 

Conforme conversamos por telefone, meu entendimento na issue 57 era sobre a forma como a informação deveria ser exibida e não o que deveria ser exibida (conteúdo), gerando esse desentendimento. Ao verificar o protótipo do caso de uso percebi que ele também passou o entendimento errado, fiz a atualização do mesmo, para que fique conforme afirmei acima, no detalhamento do grupo mostro a categoria a que ele pertence e todos os quesitos que estão vinculados a ele.

**Comment by vogoncalves** [comment]
Ok @monicaleite . Só confirmando, no detalhar Grupo serão exibidos somente os quesitos deste e o nome da Categoria associada. Faremos uma estimativa de desenvolvimento desse comportamento repassando assim que finalizar.

**Comment by jmatil** [comment]
Foi constatado que o comportamento da funcionalidade está de acordo com a solicitação do caso de uso.
