### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Registro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#67]
Favor verificar o comportamento do sistema, pois ao simular o registro com dados duplicados o sistema emitiu a mensagem conforme imagem abaixo:

![issue2](https://cloud.githubusercontent.com/assets/6584772/4811450/5b9f35d0-5eba-11e4-8109-09751ca6069a.png)

**Comment by vogoncalves** [comment]
Corrigido. Favor verificar.

**Comment by jmatil** [comment]
Correção verificada
