### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Mensagem de Registro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#68]
Favor verificar a mensagem emitida ao Cadastrar um "Grupo" com o mesmo nome.

![issue](https://cloud.githubusercontent.com/assets/6584772/4832034/013eb4a0-5f99-11e4-936e-06c09be6d64f.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
![issue](https://cloud.githubusercontent.com/assets/6584772/4841644/bf546a06-601c-11e4-8a00-7c1c56a7769a.png)
