### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Detalhamento do Quesito

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#69]
Favor visualizar a tela apresentada ao acionar o Detalhamento de um Quesito dentro da funcionalidade "Manter Grupo". Está apresentando o botão "Salvar".

![issue](https://cloud.githubusercontent.com/assets/6584772/4832262/9a463578-5f9a-11e4-823c-bf75bf753055.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Verificado a correção
