### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] É Necessário Incluir ao Menos uma Escolha

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#7]
Comparar a mensagem emitida pelo sistema ao escolher a classe: "Escolha" e acionar a opção: "Salvar" sem adicionar o peso e o texto. "Inclua PELA menos uma Escolha." 
Segue imagem para as devidas comparações.

![i1](https://cloud.githubusercontent.com/assets/6584772/3648358/54ef0558-1108-11e4-80b5-068d11e61600.png)

**Comment by nandoalmeida** [comment]
Problema resolvido.

**Comment by jmatil** [comment]
Verificado a alteração da mensagem. Segue imagem para devidas comparações.

![mensagem](https://cloud.githubusercontent.com/assets/6584772/3672756/67a4d0d0-1264-11e4-869f-2536881bd5fd.PNG)
