### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Gerar PDF

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#70]
Prezados,

Em Categoria na tela de "Listagem de Categorias Cadastradas" no detalhamento de uma categoria cadastrada e ao realizar a ação de Gerar PDF, ocorre a informação na tela conforme descrito na imagem em anexo.
![gerar_pdf](https://cloud.githubusercontent.com/assets/9218077/4832410/ec4326d2-5f9b-11e4-96d6-d23f3cafa034.jpg)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !
