### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Validação dos Campos no Cadastramento dos Quesitos

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#71]
Verificar a situação do sistema no que diz respeito a validação dos itens obrigatórios para cadastramento dos quesitos através do caso de uso Manter Grupo. Sistema não está executando a validação.

![issue](https://cloud.githubusercontent.com/assets/6584772/4842782/794aad6a-6029-11e4-9121-a36f978e743f.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção verificada
