### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Quantidade de quesitos apresentados para seleção

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#72]
Favor verificar a quantidade de quesitos solicitada para realização da seleção.

![issue](https://cloud.githubusercontent.com/assets/6584772/4843222/51826bbe-602f-11e4-9213-f108d9792a1d.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Item verificado. Favor revisar a quantidade novamente, pois está sendo disponibilizada quantidade superior.
![issue](https://cloud.githubusercontent.com/assets/6584772/4848998/6bd831d6-605e-11e4-9747-00a675287ec5.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Prezados
Favor revisar a quantidade disponível atualmente, pois o sistema continua exibindo 11 Quesitos conforme destacado na imagem atual.

![issue](https://cloud.githubusercontent.com/assets/6584772/4885154/4e1b083c-6372-11e4-8d50-f0efe61dee80.png)

**Comment by nandoalmeida** [comment]
Continuo não conseguindo verificar o problema, estou usando o Firefox 24.

![evidencia](https://cloud.githubusercontent.com/assets/7429018/4889687/45c2c5c8-6398-11e4-8d16-6efd5d218ebb.png)

**Comment by jmatil** [comment]
Prezados
Após atualização da versão do Browser, o sistema realmente mostrou a quantidade de 10 itens conforme solicitado pela documentação. Segue confirmação:

![issue](https://cloud.githubusercontent.com/assets/6584772/4889814/771483fe-6399-11e4-8790-0859976f51ac.png)
