### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Campo Obrigatório & Registro Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#73]
Prezados
Favor atualizar o comportamento do sistema para realização dos fluxos [FE1. Campo Obrigatório] e [FE2. Registro Duplicado] no que for referente a edição ou cadastramento do QUESITO no caso de uso Manter Grupo. Ao simular estas ações o sistema deverá permanecer na mesma página em que estão, e não retornar ao passo em que foram chamados.
Obs.: A Mônica atualizou o caso de uso, mas estamos tendo problemas para disponibilizá-la no repositório.
SEGUE EXEMPLO
![issue](https://cloud.githubusercontent.com/assets/6584772/4843722/734f0eae-6035-11e4-834b-cf0b31c4b587.png)

**Comment by monicaleite** [comment]
Victor,

Conforme verificado pelo Jailson, é importante que o sistema permaneça na tela do erro para que o usuário possa corrigir e entender, eu fiz a alteração no caso de uso. Não atualizei no git ainda, pq continuamos com problemas aqui para realizar o push.

**Comment by nandoalmeida** [comment]
Jailson, favor verificar pois a correção da issue #71 corrigiu também esta issue.

**Comment by jmatil** [comment]
Foi verificado a correção do item.
