### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Tela Incluir Grupo_Campos Voltar e Salvar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SICEL#74]
Prezados,
Ao incluir um grupo, e acionar a opção salva o sistema apresenta os campos "Voltar e Salvar" no roda pé da página.
![111111111111](https://cloud.githubusercontent.com/assets/9218077/4844465/8ad4e81c-603c-11e4-8b24-cbd9c278b5e6.jpg)

**Comment by nandoalmeida** [comment]
Não consegui reproduzir o problema. Favor verificar novamente pois talvez já tenha sido corrigido.

**Comment by kleiberfaria** [comment]
Verificado. Problema resolvido.
