### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Quesitos que já excluídos

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#75]
Prezados
Ao excluir todos os registros (Quesitos) através da opção: Cadastro / Quesitos, o sistema limpou corretamente os registros que estavam visíveis para o usuário, mas ao acessar a opção Cadastro/ Categoria e editar um grupo que estava disponível, o sistema demonstrou que os registros (Quesitos) que haviam sido excluídos ainda constavam nos grupos cadastrados, ou seja, supostamente ficou uma imagem do registro (Quesito) que já fazia parte daquele grupo. Sendo assim, foi realizado a inclusão de um quesito através da funcionalidade Manter Grupo e foi aceito a duplicidade conforme imagem abaixo. Pergunta: Os itens (Quesitos) que foram excluídos através do menu Cadastrar / Quesito não deveriam ser excluídos também aos Grupos aos quais pertenciam?

![issue](https://cloud.githubusercontent.com/assets/6584772/4846636/f7951a48-604c-11e4-9610-3a436e28b93c.png)

**Comment by jmatil** [comment]
Prezados
Ao executar a exclusão dos quesitos através do menu Cadastrar / Quesito, o sistema realmente deverá excluir (Limpar) os registros (quesitos) que estão disponíveis na funcionalidade Manter Grupo

**Comment by nandoalmeida** [comment]
Comportamento corrigido.
A implementação foi realizada seguindo a sugestão dada por Mônica, na issue #79 .
Favor verificar.

**Comment by jmatil** [comment]
Mudança confirmada.
