### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Cadastrar Grupo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#76]
Favor verificar o comportamento do sistema, pois foi inicializado o cadastramento do Grupo, preenchido o campo "nome" e acionado o botão "Enter" (do Teclado). O sistema direcionou o usuário à página de listagem de categoria e informou que a atualização ocorreu com sucesso. Segue imagem:

![issue](https://cloud.githubusercontent.com/assets/6584772/4848516/fa53445e-605a-11e4-82e7-fd79a70fe13c.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
