### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Inclusão do Quesito / Nome da Categoria relacionada

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#77]
A funcionalidade para inclusão do Quesito foi acionado conforme relato da regra de negócio 10, onde não constava(m) quesito(s) na lista. Mas não foi apresentado o nome da Categoria conforme solicitado na RN10.

![issue](https://cloud.githubusercontent.com/assets/6584772/4849902/2d862512-6065-11e4-8fbd-7d2632c39516.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
