### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Cadastramento dos Quesitos em ordem alfabética

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#78]
Verificar a solicitação da RAP16 citada no fluxo no que diz respeito a cadastramento em ordem alfabética. Segue exemplo de cadastramento de quesitos
![issue](https://cloud.githubusercontent.com/assets/6584772/4850054/be364a78-6066-11e4-9b0f-d7c6c13b590f.png)

**Comment by nandoalmeida** [comment]
Jailson, creio que a referida lista em <b>FA 5.3</b> seja aquela que é exibida pela grid logo abaixo do multiselect destacado na sua imagem, e nesta grid a RAP016 é seguida. Favor avaliar.

**Comment by jmatil** [comment]
Conforme conversado aguardamos a correção do item

**Comment by nandoalmeida** [comment]
Resolvido, favor verificar.

**Comment by jmatil** [comment]
Confirmado a adaptação conforme solicitado pela documentação
