### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Necessidade de fluxo de exceção ao remover último quesito vinculado à um grupo.

### ISSUE THREAD

**Issue by nandoalmeida** [islssa/SICEL#79]
Segundo o comentário da issue #75 

<b><i>"Prezados
Ao executar a exclusão dos quesitos através do menu Cadastrar / Quesito, o sistema realmente deverá excluir (Limpar) os registros (quesitos) que estão disponíveis na funcionalidade Manter Grupo"</i></b>

Como deverá ser o fluxo de exceção no momento em que, na tela de Manter Quesito, um quesito que seja o único de um determinado Grupo for removido ?

Deverá ser lançada uma mensagem ? Se sim, qual ?

Essa dúvida surge devido à regra de obrigatoriedade do item Quesito em Manter Grupo.

**Comment by monicaleite** [comment]
Fernando, 

Conversei com o gestor sobre o furo nessa regra e a mesma será ajustada em uma SM futura, pois ele quer analisar qual vai ser a melhor mudança nesse cenário.
Então fica assim na inclusão de um grupo o quesito é obrigatório.
Porém se houver uma exclusão de um quesito que era único naquele grupo o grupo ficar sem nenhum quesito.

**Comment by nandoalmeida** [comment]
Ok, entendido.
A implementação foi realizada seguindo essa lógica.
Irei fechar a issue.
