### ISSUE TITLE
[CDU_SICEL_001_Manter Tipo de Resposta] Campos Obrigatórios

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#8]
Favor verificar qual das mensagens deverá estar disponível ao acionar a opção "Salvar" sem preencher os campos considerados obrigatórios.

![campoobrigatorio](https://cloud.githubusercontent.com/assets/6584772/3648749/3fbc376a-110c-11e4-9207-2c2753302920.png)

**Comment by nandoalmeida** [comment]
Problema resolvido.

**Comment by jmatil** [comment]
Foi verificado a correção. Segue imagem para as devidas comparações.

![camposobrigatrios](https://cloud.githubusercontent.com/assets/6584772/3672649/2a10d74c-1263-11e4-85a3-e6eddbe351af.PNG)
