### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Configuração da Fonte com acentuação

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#80]
Verificar o comportamento do sistema ao utilizar caracteres com acentuação no cadastramento. 

![issue](https://cloud.githubusercontent.com/assets/6584772/4886819/a5784e0c-637f-11e4-8022-fd2f65dd1792.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Confirmado a correção
