### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Vínculo de quesitos ao Grupo

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#81]
Prezados
Favor verificar a possibilidade de disponibilização de quesitos para a mesma categoria conforme solicitado na Regra 010 e 016, pois o sistema não está permitindo que os quesitos que forem selecionados para um Grupo A com categoria A, sejam selecionados para um Grupo B com categoria B. Segue regras:

![issue](https://cloud.githubusercontent.com/assets/6584772/4888380/60e0094e-638c-11e4-9d88-f20fe1645807.png)

**Comment by nandoalmeida** [comment]
Jailson,

Aparentemente está acontecendo uma contradição entre uma RN e uma RAP.

O Multi-select <b>Quesito</b> dentro de Manter Grupos referencia a RAP012, verifique:

![evidencia_001](https://cloud.githubusercontent.com/assets/7429018/4891755/7756f7a4-63ab-11e4-80c8-e5be20f3ba68.png)

![evidencia_002](https://cloud.githubusercontent.com/assets/7429018/4891761/7c72ece8-63ab-11e4-9f7e-1fd7a933e40d.png)

Ou seja, de acordo com essa RAP deverão ser disponibilizados somente Quesitos que pertençam à Categoria em questão ou que não possuam vínculo algum. Sendo assim um Quesito associado à uma Categoria A não surgirá disponível para uma Categoria B.

Favor avaliar.

**Comment by monicaleite** [comment]
Fernando,

Esse entendimento de quem quesito será "reutilizado" em outros grupos, foi um entendimento que foi amadurecido depois dos casos de uso homologados, na época conversei com o Joel e Alex Gomides sobre isso, essa regra deverá ser alterada, para que o quesito possa pertencer a mais de um grupo/categoria. Vou alterar essa regra para que ela fique de acordo com a citada pelo Jailson na RN010, em casos de divergências nas regras nom momento do desenvolvimento, peço que me sinalizem, que me procurem para que eu corrija e explique, tire as dúvidas. A RAP012 foi alterada, para que sejam exibidos todos os quesitos, acredito que isso resolva, lembrando que conforme o Joel havia pedido, os quesitos que foram adicionados ao grupo não aparecem mais somente para aquele grupo.

**Comment by nandoalmeida** [comment]
Entendo, vou alterar a funcionalidade.

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Confirmado a correção
