### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - mensagem ao acionar a opção "Voltar"

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#82]
Prezados
Ao selecionar a opção "Todos" sem informar o "Nome" do grupo e acionar a opção "Voltar", o sistema emite a mensagem conforme imagem anexa:

![issue](https://cloud.githubusercontent.com/assets/6584772/4889189/b4d4b7f0-6393-11e4-8eb8-95f7005a0498.png)

**Comment by jadossantos** [comment]
Resolvido.

**Comment by jmatil** [comment]
Favor verificar o comportamento do sistema, pois a mesma situação está ocorrendo ao acionar o botão Salvar.

**Comment by jadossantos** [comment]
Aparentemente foi um problema no servidor, pois não estou conseguindo simular o problema.

**Comment by jadossantos** [comment]
Resolvido. O problema era por causa dos caracteres especiais.

**Comment by jmatil** [comment]
Confirmado a correção

![issue](https://cloud.githubusercontent.com/assets/6584772/4902304/7de1c2ba-6438-11e4-895e-0d40c104bee3.png)
