### ISSUE TITLE
SICEL_CDU_003_Manter Grupo - Campos Obrigatórios e validação de funcionalidades

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#84]
Na tentativa de simular o Fluxo de exceção 1 "Campos Obrigatórios" para o cadastramento de quesitos dentro da funcionalidade Manter Grupo, o sistema emitiu mensagens de obrigatoriedade para ambas as janelas (Funcionalidades) Cadastramento do Quesito e Cadastramento do Grupo. Segue imagem.
Obs: Este novo tipo de janela de cadastramento dos quesitos não estava disponíveis para versões de testes anteriores.

![issue](https://cloud.githubusercontent.com/assets/6584772/4890686/25b9cf48-63a1-11e4-9bad-4192e92166da.png)

**Comment by vogoncalves** [comment]
Corrigido. Favor verificar.

**Comment by jmatil** [comment]
Correção confirmada

![issue](https://cloud.githubusercontent.com/assets/6584772/4901948/8a9d4f72-6435-11e4-98f4-5a5f26cab5d8.png)
