### ISSUE TITLE
SICEL_CDU_004_Manter Quesito - Pagina não encontrada

### ISSUE THREAD

**Issue by jmatil** [islssa/SICEL#85]
Mensagem emitida ao simular uma página não existente para localização. Fluxo FE4. Pagina não encontrada.

![issue](https://cloud.githubusercontent.com/assets/6584772/4891576/8bfc6790-63a9-11e4-8490-b2a8a2b42fd0.png)

**Comment by nandoalmeida** [comment]
Corrigido, favor verificar.

**Comment by jmatil** [comment]
Correção confirmada
