### ISSUE TITLE
SICEL_CDU_006_Manter Tipo de Procedimento - FA 3 - Excluir Tipo de Procedimentos

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#86]
No passo 2 do Fluxo Alternativo 3 não deixa explícito em qual momento as mensagens MSG006 e MSG011 irão aparecer.

**Comment by espinola** [comment]
não existe MSG011 e sim MSG009, a RN014 explica

**Comment by jadossantos** [comment]
Ok!
