### ISSUE TITLE
 SICEL_CDU_006_Manter Tipo de Procedimento - Tabelas incompletas

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#87]
A coluna <b>Roteiro</b> que está nas tabelas das telas PT2, PT3 e PT4 está com valor <b>XXXX</b>.

**Comment by espinola** [comment]
Sera o tamanho da descrição do roteiro = 300

**Comment by jadossantos** [comment]
Ok. Estamos aguardando a atualização do documento.
