### ISSUE TITLE
 SICEL_CDU_006_Manter Tipo de Procedimento - RN25

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#88]
Acredito que poderíamos melhorar o trecho <b>"Alterar os campos “Descrição” e “Roteiros” dos Tipos de procedimentos <u>que são fixos no banco.</u>"</b>, pois está confuso. 

Lendo a documentação identificamos a RAP018, que lista os valores:
- Relatório Anual de Atividades;
- Relatório Mensal de Atividades;
- Correição Ordinária;
- Correição Extraordinária;
- Inspeção.

Ou seja, esses valores farão parte de uma carga inicial do sistema, que o usuário não poderá editar o campo<b> Descrição</b>.

**Comment by espinola** [comment]
nao entendi a dúvida

**Comment by espinola** [comment]
feito

**Comment by jadossantos** [comment]
Ok!
