### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - RAP043 - Vínculo com Tipo de Procedimento

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#92]
Segundo a documentação, o <b>Roteiro</b> tem um vínculo oibrigatório com campo <b>Tipo</b>. Porém, na tela de cadastro do <b>Tipo de Procedimento</b> tem uma <u>Lista Dupla</u> e não existe nenhuma restrição para que o Roteiro tenha mais de um <b>Tipo</b>. 
Isso está correto?

**Comment by monicaleite** [comment]
Um roteiro pode pertencer ao mais de um procedimento, ele pode ser executado em vários procedimentos.

**Comment by jadossantos** [comment]
Você falou que o <u>Roteiro</u> pertence a mais de um <b>Procedimento</b>, mas a tela que questionei é a de <b>Tipo de Procedimento</b>.

**Comment by monicaleite** [comment]
O roteiro pode pertencer a mais um tipo, o que ocorre nesse caso de uso é que os roteiros criados aí quando colocados como ordinário eles serão de execução obrigatória pelas unidades.

**Comment by jadossantos** [comment]
Na verdade a palavra <u>pertence</u> deve ser substituída pela <u>tem</u>.
Segundo a documentação (SICEL_CDU_005_Manter Roteiro) um <b>Roteiro</b> tem apenas um <b>Tipo</b> por vez, ou seja, só é possível selecionar um.

**Comment by monicaleite** [comment]
Então, no roteiro esse é o comportamento, já no Manter tipo ele pode está em mais de um tipo.

**Comment by jadossantos** [comment]
Então como será esse comportamento? Isso tá estranho!

**Comment by monicaleite** [comment]
Eu crio o roteiro falando para qual tipo ele foi criado, o que não impede que o mesmo seja usado em um tipo diferente.

**Comment by monicaleite** [comment]
Joel, 

Em reunião com o Elder ficou definido que não posso excluir um tipo de procedimento que esteja associado ao um roteiro, será necessário retirar o vínculo, então terei que acrescentar esse fluxo exceção no Manter Tipo de Procedimento.
Quanto a ter a associação de um roteiro no Manter Tipo de Procedimento e no Manter Roteiro, ficará como está, quando eu crio um roteiro eu informo qual tipo de roteiro estou criando, e no Manter Tipo posso utilizar um roteiro que foi criado para o propósito de um tipo e ser utilizado em outro caso o usuário queria.

**Comment by jadossantos** [comment]
Ok.
