### ISSUE TITLE
SICEL_CDU_005_Manter Roteiro - RAP035 - Mudança na Estrutura

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#93]
Com o tipo <b>Ordinário</b> poderemos usar toda a estrutura de dados desenvolvida na <u>iteração 2</U>, mas com o tipo diferente de <b>Ordinário</b> não existe estrutura ou vínculo entre as entidades (Categoria -> Grupo -> Quesito) com <b>Roteiro</b>. Podendo assumir qualquer relacionamento. É isso mesmo que o cliente quer?

As informações vinculadas ao tipo diferente de <b>Ordinário</b> serão visiveis nas telas dos CDUs abaixo?
- SICEL_CDU_002_Manter Categoria;
- SICEL_CDU_003_Manter Grupo;
- SICEL_CDU_004_Manter Quesito;

**Comment by monicaleite** [comment]
O tipo ordinário terá obrigatoriamente a estrutura de categoria/grupo/quesito, o que for diferente de ordinário pode ser feito sem essa obrigatoriedade porém seguindo a regra em que fala que não existe um roteiro só com categoria e nem grupo sem categoria e nem roteiro sem ao menos um quesito. O que for feito no roteiro será mantido no roteiro, não impactando no que foi feito nos cadastros base, de categoria, grupo e quesito.

**Comment by jadossantos** [comment]
Ou seja, apesar de terem o mesmo "<u>nome</u>" não serão tratados da mesma maneira. Ok?

**Comment by monicaleite** [comment]
Os roteiros possuem tipos diferentes e os do tipo ordinário é que terão obrigatoriedade de estrutura.
