### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Aba Unidade Eleitoral - Totalitário

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#97]
Como iremos recuperar o campo <b>Totalitário</b>?

**Comment by espinola** [comment]
pela quantidade de respostas salvas no caso de uso executar procedimento, realmente faltou essa regra.

**Comment by jadossantos** [comment]
Ok. Poderia atualizar a documentação?

**Comment by espinola** [comment]
atualizado

**Comment by jadossantos** [comment]
A RN49 foi adicionada.
