### ISSUE TITLE
SICEL_CDU_007_Manter Procedimento - Aba Unidade Eleitoral - Botão Excluir

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#98]
A exclusão do registro da aba Unidade Eleitoral é <b>física</b> ou <b>Lógica</b>?

**Comment by espinola** [comment]
como assim? neste caso ele retira a associação da zona com aquele procedimento

**Comment by jadossantos** [comment]
Exclusão Física: Remove o registro do banco de dados.
Exclusão Lógica: Atualizado o status do registro para excluído, ou seja, teremos uma coluna para tratar isso.

Esse trecho também não faz referência a RN003, que trata da exclusão lógica

**Comment by espinola** [comment]
a funcionalidade nao trata de uma exclusão física nem logica e sim trata de uma retirada de vinculo

**Comment by jadossantos** [comment]
Se temos um vínculo na aplicação precisaremos registrar no banco de dados. Caso seja removido tal vínculo, ele pode ser de duas formas:
- Exclusão Lógica
- Eclusão Física

**Comment by espinola** [comment]
Então é fisica

**Comment by jadossantos** [comment]
ok.
