### ISSUE TITLE
SICEL_CDU_008_Executar Procedimento - RAP050 - Dias Úteis

### ISSUE THREAD

**Issue by jadossantos** [islssa/SICEL#99]
O que é considerado dia útil no sistema? Temos duas opções:
- De segunda a sexta;
- De segunda a sexta menos os feriados;

Caso considere os feriados, em qual base iremos recuperar essas datas?

**Comment by monicaleite** [comment]
De segunda a sexta menos os feriados.

**Comment by jadossantos** [comment]
Em qual base iremos recuperar essas datas?

**Comment by monicaleite** [comment]
Na regra fala como será calculada a data, como assim de que base?

**Comment by jadossantos** [comment]
Para calcularmos a quantidade de dias úteis de um determinado período é necessário identificarmos as datas que são <u>feriados</u> para desconsiderar no cálculo. Ok?

**Comment by monicaleite** [comment]
Não sei dizer, verifica com o Leandro da SEDESC4.

**Comment by jadossantos** [comment]
Ok. Entraremos em contato com ele.
